# Load data

In [5]:
# Append
import sys
sys.path.append("../Common/")

# Import de lay du lieu
import CommonYFinance, CommonBinance, CommonMT5, CommonBacktest, CommonSSI

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Bước 1: Nhập Thư Viện và Chuẩn Bị Dữ Liệu

In [4]:
symbol = 'VCB.VN'
from_date = '2025-06-01'
to_date = '2025-11-08'
interval = '1d'
data = CommonYFinance.CommonYFinance.loaddataYFinance(symbol, from_date, to_date, interval)

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['VCB.VN']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

# CommonSSI

In [13]:
symbol = 'VCB'
from_date = '2025-08-01'
to_date = '2025-11-07'
interval = '1d'
data = CommonSSI.CommonSSI.loaddataSSI(symbol, from_date, to_date)

daily_ohlc(symbol='VCB', fromDate='01/08/2025', toDate='07/11/2025', pageIndex=1, pageSize=100, ascending=True)
{'data': [{'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '01/08/2025', 'Time': None, 'Open': '59866', 'High': '60164', 'Low': '59270', 'Close': '59767', 'Volume': '4751600', 'Value': '285499090000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '04/08/2025', 'Time': None, 'Open': '59667', 'High': '60958', 'Low': '59568', 'Close': '60660', 'Volume': '4462400', 'Value': '271298380000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '05/08/2025', 'Time': None, 'Open': '61057', 'High': '63241', 'Low': '60759', 'Close': '61057', 'Volume': '18590000', 'Value': '1159664360000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '06/08/2025', 'Time': None, 'Open': '61653', 'High': '62348', 'Low': '61454', 'Close': '61851', 'Volume': '4677500', 'Value': '291502420000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '07/08/2025', 'Time': None, 'Open': '62447', 'High': '62447', 'Low': '60859', 'Close': '61256', 'Volume': '9498700', 'Value': '587678430000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '08/08/2025', 'Time': None, 'Open': '61752', 'High': '62844', 'Low': '61156', 'Close': '61454', 'Volume': '10679800', 'Value': '665503890000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '11/08/2025', 'Time': None, 'Open': '61653', 'High': '62745', 'Low': '61653', 'Close': '62050', 'Volume': '7266300', 'Value': '454515450000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '12/08/2025', 'Time': None, 'Open': '62348', 'High': '64333', 'Low': '62249', 'Close': '62546', 'Volume': '12129000', 'Value': '770169850000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '13/08/2025', 'Time': None, 'Open': '63043', 'High': '63142', 'Low': '61554', 'Close': '62050', 'Volume': '7519800', 'Value': '470654320000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '14/08/2025', 'Time': None, 'Open': '63241', 'High': '65823', 'Low': '62844', 'Close': '64731', 'Volume': '19003100', 'Value': '1227651390000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '15/08/2025', 'Time': None, 'Open': '66915', 'High': '67014', 'Low': '63738', 'Close': '63837', 'Volume': '16667800', 'Value': '1098675630000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '18/08/2025', 'Time': None, 'Open': '64333', 'High': '65128', 'Low': '63539', 'Close': '64036', 'Volume': '8297300', 'Value': '536929470000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '19/08/2025', 'Time': None, 'Open': '64036', 'High': '64929', 'Low': '63738', 'Close': '63738', 'Volume': '9191400', 'Value': '593569360000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '20/08/2025', 'Time': None, 'Open': '64036', 'High': '64135', 'Low': '61752', 'Close': '62546', 'Volume': '10537600', 'Value': '667369550000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '21/08/2025', 'Time': None, 'Open': '62844', 'High': '64532', 'Low': '62844', 'Close': '63738', 'Volume': '9639300', 'Value': '620318450000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '22/08/2025', 'Time': None, 'Open': '63539', 'High': '66716', 'Low': '63241', 'Close': '64135', 'Volume': '18944300', 'Value': '1245865980000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '25/08/2025', 'Time': None, 'Open': '65326', 'High': '65326', 'Low': '62944', 'Close': '63142', 'Volume': '7750800', 'Value': '498260000000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '26/08/2025', 'Time': None, 'Open': '63142', 'High': '64532', 'Low': '62447', 'Close': '64135', 'Volume': '7988400', 'Value': '507780740000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '27/08/2025', 'Time': None, 'Open': '64532', 'High': '68602', 'Low': '64532', 'Close': '68602', 'Volume': '31048100', 'Value': '2128073130000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '28/08/2025', 'Time': None, 'Open': '69000', 'High': '70092', 'Low': '68205', 'Close': '68503', 'Volume': '8799400', 'Value': '611089560000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '29/08/2025', 'Time': None, 'Open': '68702', 'High': '69595', 'Low': '68007', 'Close': '68106', 'Volume': '14696100', 'Value': '1017860550000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '03/09/2025', 'Time': None, 'Open': '68305', 'High': '68305', 'Low': '66518', 'Close': '66518', 'Volume': '14216900', 'Value': '962297890000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '04/09/2025', 'Time': None, 'Open': '67014', 'High': '68503', 'Low': '66418', 'Close': '68404', 'Volume': '8942100', 'Value': '607466390000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '05/09/2025', 'Time': None, 'Open': '69000', 'High': '69099', 'Low': '67014', 'Close': '67014', 'Volume': '11047800', 'Value': '759069220000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '08/09/2025', 'Time': None, 'Open': '66617', 'High': '67014', 'Low': '64830', 'Close': '64830', 'Volume': '11249800', 'Value': '745660080000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '09/09/2025', 'Time': None, 'Open': '65028', 'High': '65723', 'Low': '64036', 'Close': '64433', 'Volume': '6192300', 'Value': '402660300000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '10/09/2025', 'Time': None, 'Open': '65128', 'High': '65525', 'Low': '64333', 'Close': '65326', 'Volume': '5006400', 'Value': '326945700000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '11/09/2025', 'Time': None, 'Open': '65128', 'High': '65525', 'Low': '63738', 'Close': '65227', 'Volume': '6349100', 'Value': '413050950000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '12/09/2025', 'Time': None, 'Open': '65723', 'High': '65723', 'Low': '64532', 'Close': '65326', 'Volume': '5694200', 'Value': '373462790000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '15/09/2025', 'Time': None, 'Open': '65525', 'High': '65525', 'Low': '65028', 'Close': '65326', 'Volume': '5367400', 'Value': '352711800000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '16/09/2025', 'Time': None, 'Open': '65525', 'High': '66120', 'Low': '65128', 'Close': '65128', 'Volume': '6765400', 'Value': '447031130000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '17/09/2025', 'Time': None, 'Open': '65028', 'High': '65326', 'Low': '64333', 'Close': '64333', 'Volume': '5627200', 'Value': '366683420000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '18/09/2025', 'Time': None, 'Open': '64433', 'High': '64433', 'Low': '63142', 'Close': '63440', 'Volume': '8783400', 'Value': '563070810000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '19/09/2025', 'Time': None, 'Open': '63738', 'High': '64036', 'Low': '62546', 'Close': '62546', 'Volume': '6932700', 'Value': '438861190000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '22/09/2025', 'Time': None, 'Open': '62546', 'High': '62745', 'Low': '61355', 'Close': '61554', 'Volume': '6061300', 'Value': '377811750000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '23/09/2025', 'Time': None, 'Open': '61951', 'High': '62646', 'Low': '61752', 'Close': '61752', 'Volume': '3267800', 'Value': '204691380000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '24/09/2025', 'Time': None, 'Open': '61951', 'High': '62249', 'Low': '61355', 'Close': '62249', 'Volume': '3879200', 'Value': '241048440000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '25/09/2025', 'Time': None, 'Open': '62844', 'High': '62944', 'Low': '62249', 'Close': '62546', 'Volume': '3870300', 'Value': '244105000000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '26/09/2025', 'Time': None, 'Open': '62745', 'High': '62944', 'Low': '62447', 'Close': '62546', 'Volume': '3981900', 'Value': '251215760000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '29/09/2025', 'Time': None, 'Open': '62447', 'High': '62447', 'Low': '61951', 'Close': '62149', 'Volume': '2782900', 'Value': '174229910000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '30/09/2025', 'Time': None, 'Open': '62348', 'High': '62447', 'Low': '61355', 'Close': '61554', 'Volume': '4104100', 'Value': '255132620000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '01/10/2025', 'Time': None, 'Open': '62249', 'High': '62249', 'Low': '61554', 'Close': '61951', 'Volume': '3022000', 'Value': '188400460000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '02/10/2025', 'Time': None, 'Open': '61951', 'High': '62646', 'Low': '61653', 'Close': '61653', 'Volume': '3657500', 'Value': '229086420000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '03/10/2025', 'Time': None, 'Open': '62000', 'High': '62000', 'Low': '61400', 'Close': '61700', 'Volume': '2821100', 'Value': '174222830000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '06/10/2025', 'Time': None, 'Open': '62800', 'High': '64000', 'Low': '62800', 'Close': '64000', 'Volume': '7461700', 'Value': '474017050000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '07/10/2025', 'Time': None, 'Open': '64100', 'High': '64100', 'Low': '63300', 'Close': '63700', 'Volume': '4229300', 'Value': '269759710000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '08/10/2025', 'Time': None, 'Open': '64200', 'High': '64900', 'Low': '63600', 'Close': '64600', 'Volume': '8113800', 'Value': '520241720000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '09/10/2025', 'Time': None, 'Open': '64500', 'High': '65200', 'Low': '63800', 'Close': '63800', 'Volume': '5734200', 'Value': '368139750000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '10/10/2025', 'Time': None, 'Open': '63900', 'High': '64400', 'Low': '63600', 'Close': '64200', 'Volume': '4985600', 'Value': '319565470000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '13/10/2025', 'Time': None, 'Open': '63400', 'High': '63800', 'Low': '62800', 'Close': '63100', 'Volume': '7992500', 'Value': '505177750000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '14/10/2025', 'Time': None, 'Open': '63500', 'High': '64000', 'Low': '62900', 'Close': '63100', 'Volume': '7008900', 'Value': '443354140000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '15/10/2025', 'Time': None, 'Open': '63100', 'High': '63400', 'Low': '62500', 'Close': '62500', 'Volume': '5218800', 'Value': '329246580000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '16/10/2025', 'Time': None, 'Open': '62700', 'High': '63000', 'Low': '62500', 'Close': '62900', 'Volume': '4634400', 'Value': '290527390000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '17/10/2025', 'Time': None, 'Open': '62900', 'High': '62900', 'Low': '61800', 'Close': '61900', 'Volume': '5405900', 'Value': '336717510000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '20/10/2025', 'Time': None, 'Open': '61800', 'High': '62200', 'Low': '58600', 'Close': '59400', 'Volume': '12115600', 'Value': '740009000000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '21/10/2025', 'Time': None, 'Open': '59700', 'High': '60700', 'Low': '59300', 'Close': '59300', 'Volume': '8416700', 'Value': '504612010000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '22/10/2025', 'Time': None, 'Open': '60100', 'High': '60200', 'Low': '58500', 'Close': '59600', 'Volume': '4664800', 'Value': '276154650000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '23/10/2025', 'Time': None, 'Open': '58900', 'High': '60300', 'Low': '58900', 'Close': '59800', 'Volume': '4227100', 'Value': '252653200000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '24/10/2025', 'Time': None, 'Open': '59800', 'High': '59900', 'Low': '58800', 'Close': '59500', 'Volume': '4372700', 'Value': '260109200000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '27/10/2025', 'Time': None, 'Open': '60000', 'High': '60000', 'Low': '59200', 'Close': '59200', 'Volume': '2640000', 'Value': '157145230000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '28/10/2025', 'Time': None, 'Open': '59200', 'High': '60200', 'Low': '59100', 'Close': '60000', 'Volume': '2789700', 'Value': '166577550000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '29/10/2025', 'Time': None, 'Open': '60000', 'High': '61000', 'Low': '59800', 'Close': '60700', 'Volume': '3716000', 'Value': '223920940000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '30/10/2025', 'Time': None, 'Open': '61000', 'High': '61200', 'Low': '60300', 'Close': '60600', 'Volume': '1946600', 'Value': '118304140000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '31/10/2025', 'Time': None, 'Open': '60800', 'High': '60800', 'Low': '59600', 'Close': '59600', 'Volume': '2117800', 'Value': '127319000000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '03/11/2025', 'Time': None, 'Open': '60000', 'High': '60300', 'Low': '59300', 'Close': '59300', 'Volume': '2800100', 'Value': '167153680000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '04/11/2025', 'Time': None, 'Open': '59200', 'High': '60400', 'Low': '59100', 'Close': '60100', 'Volume': '2952400', 'Value': '176177680000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '05/11/2025', 'Time': None, 'Open': '60000', 'High': '61100', 'Low': '59900', 'Close': '60800', 'Volume': '4601700', 'Value': '278521160000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '06/11/2025', 'Time': None, 'Open': '60900', 'High': '61300', 'Low': '60200', 'Close': '60300', 'Volume': '2821200', 'Value': '171095140000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '07/11/2025', 'Time': None, 'Open': '60000', 'High': '60000', 'Low': '59000', 'Close': '59300', 'Volume': '3586300', 'Value': '213567960000'}], 'message': 'Success', 'status': 'Success', 'totalRecord': 69}

In [14]:
data

      Datetime   Open   High    Low  Close    Volume
0   01/08/2025  59866  60164  59270  59767   4751600
1   04/08/2025  59667  60958  59568  60660   4462400
2   05/08/2025  61057  63241  60759  61057  18590000
3   06/08/2025  61653  62348  61454  61851   4677500
4   07/08/2025  62447  62447  60859  61256   9498700
..         ...    ...    ...    ...    ...       ...
64  03/11/2025  60000  60300  59300  59300   2800100
65  04/11/2025  59200  60400  59100  60100   2952400
66  05/11/2025  60000  61100  59900  60800   4601700
67  06/11/2025  60900  61300  60200  60300   2821200
68  07/11/2025  60000  60000  59000  59300   3586300

[69 rows x 6 columns]

# Bước 2: Tải và Tiền Xử Lý Dữ Liệu

### # X là các đặc trưng, y là biến mục tiêu (Feature và Target)
### Chọn các cột đặc trưng và biến mục tiêu

In [16]:
### X la dac trung
X = data.drop('Close', axis=1) # D, O, H, L, V
X = X.drop('Datetime', axis=1) # D, O, H, L, V
# X = X.drop('Adj Close', axis=1) # D, O, H, L, V
X

     Open   High    Low    Volume
0   59866  60164  59270   4751600
1   59667  60958  59568   4462400
2   61057  63241  60759  18590000
3   61653  62348  61454   4677500
4   62447  62447  60859   9498700
..    ...    ...    ...       ...
64  60000  60300  59300   2800100
65  59200  60400  59100   2952400
66  60000  61100  59900   4601700
67  60900  61300  60200   2821200
68  60000  60000  59000   3586300

[69 rows x 4 columns]

In [17]:
y = data['Close'] # Close
y

0     59767
1     60660
2     61057
3     61851
4     61256
      ...
64    59300
65    60100
66    60800
67    60300
68    59300
Name: Close, Length: 69, dtype: object

# Chia dữ liệu thành tập huấn luyện và kiểm thử

In [18]:
# Chia dữ liệu thành tập huấn luyện và kiểm thử
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Chuyển cột Datetime sang Timestamp
# X_train['Datetime'] = X_train['Datetime'].astype(np.int64) // 10**9  # Chuyển thành timestamp
# X_test['Datetime'] = X_test['Datetime'].astype(np.int64) // 10**9

In [21]:
print(X)

     Open   High    Low    Volume
0   59866  60164  59270   4751600
1   59667  60958  59568   4462400
2   61057  63241  60759  18590000
3   61653  62348  61454   4677500
4   62447  62447  60859   9498700
..    ...    ...    ...       ...
64  60000  60300  59300   2800100
65  59200  60400  59100   2952400
66  60000  61100  59900   4601700
67  60900  61300  60200   2821200
68  60000  60000  59000   3586300

[69 rows x 4 columns]

In [22]:
print(y)

0     59767
1     60660
2     61057
3     61851
4     61256
      ...
64    59300
65    60100
66    60800
67    60300
68    59300
Name: Close, Length: 69, dtype: object

# Bước 3: Huấn Luyện Mô Hình

In [ ]:
# Huấn luyện mô hình Hồi Quy Tuyến Tính
model_lr = LinearRegression()
model_lr.fit(X_train, y_train)

# Huấn luyện mô hình Cây Quyết Định
model_dt = DecisionTreeRegressor(random_state=42) # random_state
model_dt.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [24]:
model_lr

LinearRegression()

# Bước 4: Dự Đoán và Đánh Giá Mô Hình

In [25]:
print(X_test)

     Open   High    Low    Volume
22  67014  68503  66418   8942100
0   59866  60164  59270   4751600
47  64500  65200  63800   5734200
4   62447  62447  60859   9498700
53  62900  62900  61800   5405900
18  64532  68602  64532  31048100
10  66915  67014  63738  16667800
33  63738  64036  62546   6932700
44  62800  64000  62800   7461700
12  64036  64929  63738   9191400
31  65028  65326  64333   5627200
9   63241  65823  62844  19003100
59  60000  60000  59200   2640000
5   61752  62844  61156  10679800

In [26]:
# Dự đoán trên tập kiểm thử
predictions_lr = model_lr.predict(X_test)
predictions_dt = model_dt.predict(X_test)

# Tính toán MSE và R-squared cho Hồi Quy Tuyến Tính
mse_lr = mean_squared_error(y_test, predictions_lr)
r2_lr = r2_score(y_test, predictions_lr)

# Tính toán MSE và R-squared cho Cây Quyết Định
mse_dt = mean_squared_error(y_test, predictions_dt)
r2_dt = r2_score(y_test, predictions_dt)

# In kết quả
print(f"Linear Regression - MSE: {mse_lr}, R2: {r2_lr}")
print(f"Decision Tree - MSE: {mse_dt}, R2: {r2_dt}")

Linear Regression - MSE: 1199707.9764672273, R2: 0.8282093801640676
Decision Tree - MSE: 2561206.3571428573, R2: 0.6332513942960176

# Bước 5: So Sánh và Phân Tích

Sử dụng các chỉ số MSE (Mean Squared Error) và R² (R-squared) để so sánh hiệu suất của hai mô hình.

# MSE thấp và R² cao cho thấy mô hình có hiệu suất tốt hơn.

Kết quả của việc đánh giá hai mô hình - Hồi Quy Tuyến Tính (Linear Regression) và Cây Quyết Định (Decision Tree) - trên tập kiểm thử của bạn cho thấy:

Hồi Quy Tuyến Tính:
MSE (Mean Squared Error): 169492.43. Đây là giá trị trung bình của bình phương sai số giữa giá trị dự đoán và giá trị thực tế. MSE càng thấp, mô hình càng chính xác.
R² (R-squared): 0.9576. Đây là tỉ lệ phần trăm biến đổi của biến mục tiêu được giải thích bởi mô hình. R² càng gần 1, mô hình càng phù hợp với dữ liệu.

Cây Quyết Định:
MSE: 911540.78. MSE cao hơn nhiều so với Hồi Quy Tuyến Tính, điều này cho thấy mô hình Cây Quyết Định có sai số dự đoán cao hơn.
R²: 0.7721. Dù vẫn khá cao, nhưng R² thấp hơn so với Hồi Quy Tuyến Tính, cho thấy mô hình này giải thích ít biến đổi của dữ liệu hơn.

Phân Tích và Kết Luận:
Dựa trên MSE và R², mô hình Hồi Quy Tuyến Tính (Linear Regression) có vẻ phù hợp hơn với dữ liệu kiểm thử so với mô hình Cây Quyết Định (Decision Tree). Nó có sai số thấp hơn và giải thích được một tỉ lệ lớn hơn biến đổi của dữ liệu.
Tuy nhiên, cần lưu ý rằng việc chọn mô hình phù hợp không chỉ dựa trên số liệu đánh giá mà còn phụ thuộc vào bối cảnh cụ thể của bài toán, bản chất của dữ liệu và yêu cầu về độ chính xác cũng như tính hiệu quả trong thực tiễn.
Nếu mô hình Cây Quyết Định có R² thấp và MSE cao, có thể xem xét việc điều chỉnh các tham số của mô hình như độ sâu của cây, số lượng lá tối thiểu, v.v., hoặc xem xét việc sử dụng một thuật toán khác.
Nhìn chung, kết quả cho thấy Hồi Quy Tuyến Tính là lựa chọn tốt hơn trong trường hợp này. Tuy nhiên, cần phải xem xét kỹ lưỡng hơn về dữ liệu và yêu cầu của bài toán để đưa ra quyết định cuối cùng.