# Lay du lieu

In [5]:
from datetime import datetime
import MetaTrader5 as mt5
# display data on the MetaTrader 5 package
print("MetaTrader5 package author: ",mt5.__author__)
print("MetaTrader5 package version: ",mt5.__version__)
 
# import the 'pandas' module for displaying data obtained in the tabular form
import pandas as pd
pd.set_option('display.max_columns', 500) # number of columns to be displayed
pd.set_option('display.width', 1500)      # max table width to display
 
# establish connection to MetaTrader 5 terminal
if not mt5.initialize():
    print("initialize() failed, error code =",mt5.last_error())
    quit()

symbol = "GBPUSD.sml"
timeframe = mt5.TIMEFRAME_M1

# get 10 GBPUSD D1 bars from the current day
rates = mt5.copy_rates_from_pos(symbol, timeframe, 0, 101)
 
# shut down connection to the MetaTrader 5 terminal
mt5.shutdown()
# display each element of obtained data in a new line
print("Display obtained data 'as is'")
for rate in rates:
    print(rate)
 
# create DataFrame out of the obtained data
rates_frame = pd.DataFrame(rates)
# convert time in seconds into the datetime format
rates_frame['time']=pd.to_datetime(rates_frame['time'], unit='s')
 
# display data
print("\nDisplay dataframe with data")
print(rates_frame)

MetaTrader5 package author:  MetaQuotes Ltd.
MetaTrader5 package version:  5.0.45
Display obtained data 'as is'
(1758730980, 1.34417, 1.34417, 1.34387, 1.34396, 217, 9, 0)
(1758731040, 1.34396, 1.34412, 1.34396, 1.34406, 177, 10, 0)
(1758731100, 1.34406, 1.34414, 1.34382, 1.34384, 209, 9, 0)
(1758731160, 1.34383, 1.34383, 1.34354, 1.34365, 214, 8, 0)
(1758731220, 1.34365, 1.34378, 1.34362, 1.34368, 136, 9, 0)
(1758731280, 1.34368, 1.344, 1.34361, 1.34398, 155, 10, 0)
(1758731340, 1.34398, 1.34402, 1.34388, 1.34395, 187, 10, 0)
(1758731400, 1.34392, 1.34392, 1.34375, 1.34376, 284, 10, 0)
(1758731460, 1.34376, 1.34377, 1.3435, 1.34358, 295, 10, 0)
(1758731520, 1.34358, 1.34358, 1.34332, 1.34336, 226, 10, 0)
(1758731580, 1.34336, 1.3434, 1.34291, 1.34291, 204, 9, 0)
(1758731640, 1.34289, 1.34298, 1.34267, 1.34268, 253, 8, 0)
(1758731700, 1.34268, 1.34299, 1.34266, 1.34298, 240, 8, 0)
(1758731760, 1.34298, 1.34315, 1.34286, 1.34295, 209, 9, 0)
(1758731820, 1.34294, 1.34295, 1.34273, 1.34284, 220, 10, 0)
(1758731880, 1.34284, 1.34307, 1.34276, 1.34306, 245, 9, 0)
(1758731940, 1.34305, 1.34329, 1.34295, 1.34329, 264, 11, 0)
(1758732000, 1.34328, 1.34337, 1.34316, 1.34333, 228, 9, 0)
(1758732060, 1.34331, 1.34338, 1.34314, 1.34328, 237, 8, 0)
(1758732120, 1.34328, 1.34339, 1.34327, 1.34338, 152, 8, 0)
(1758732180, 1.34339, 1.34347, 1.34309, 1.34309, 250, 8, 0)
(1758732240, 1.34309, 1.3431, 1.34276, 1.34283, 315, 8, 0)
(1758732300, 1.34282, 1.34309, 1.34277, 1.34278, 302, 8, 0)
(1758732360, 1.34277, 1.34302, 1.34276, 1.34295, 267, 9, 0)
(1758732420, 1.34295, 1.34318, 1.34294, 1.34317, 235, 10, 0)
(1758732480, 1.34317, 1.34348, 1.34312, 1.34323, 249, 10, 0)
(1758732540, 1.3432, 1.34356, 1.34315, 1.34345, 255, 9, 0)
(1758732600, 1.34345, 1.34368, 1.34334, 1.34367, 283, 10, 0)
(1758732660, 1.34368, 1.34394, 1.34362, 1.34386, 290, 9, 0)
(1758732720, 1.34385, 1.34398, 1.34376, 1.34386, 244, 9, 0)
(1758732780, 1.34385, 1.34386, 1.34348, 1.34369, 256, 8, 0)
(1758732840, 1.34368, 1.34388, 1.34366, 1.34367, 197, 10, 0)
(1758732900, 1.34368, 1.34408, 1.34368, 1.34403, 295, 10, 0)
(1758732960, 1.34403, 1.34425, 1.34403, 1.34425, 203, 9, 0)
(1758733020, 1.34425, 1.34428, 1.34382, 1.34397, 268, 8, 0)
(1758733080, 1.34396, 1.34397, 1.34383, 1.34385, 177, 8, 0)
(1758733140, 1.34384, 1.34395, 1.34375, 1.34375, 167, 8, 0)
(1758733200, 1.34379, 1.34379, 1.34304, 1.34305, 274, 8, 0)
(1758733260, 1.34305, 1.34316, 1.3428, 1.34282, 246, 8, 0)
(1758733320, 1.34283, 1.34334, 1.34268, 1.34332, 388, 8, 0)
(1758733380, 1.34332, 1.34332, 1.34302, 1.34325, 337, 10, 0)
(1758733440, 1.34325, 1.34334, 1.34305, 1.34325, 235, 8, 0)
(1758733500, 1.34327, 1.34336, 1.34292, 1.34316, 268, 8, 0)
(1758733560, 1.34315, 1.34325, 1.343, 1.34325, 228, 8, 0)
(1758733620, 1.34324, 1.34335, 1.34296, 1.34307, 281, 8, 0)
(1758733680, 1.34306, 1.34318, 1.34293, 1.34296, 274, 9, 0)
(1758733740, 1.34296, 1.34325, 1.34295, 1.34317, 274, 8, 0)
(1758733800, 1.34316, 1.34336, 1.34311, 1.34324, 328, 8, 0)
(1758733860, 1.34323, 1.34358, 1.34311, 1.34357, 214, 8, 0)
(1758733920, 1.34357, 1.34358, 1.34343, 1.34356, 234, 9, 0)
(1758733980, 1.34356, 1.34357, 1.3432, 1.34345, 280, 9, 0)
(1758734040, 1.34344, 1.34369, 1.34344, 1.3435, 300, 10, 0)
(1758734100, 1.34348, 1.34376, 1.34348, 1.34367, 240, 9, 0)
(1758734160, 1.34367, 1.3437, 1.34347, 1.34366, 208, 10, 0)
(1758734220, 1.34366, 1.34367, 1.34348, 1.34359, 246, 9, 0)
(1758734280, 1.34358, 1.34358, 1.34329, 1.34334, 227, 11, 0)
(1758734340, 1.34333, 1.34359, 1.3433, 1.34346, 164, 11, 0)
(1758734400, 1.34346, 1.34349, 1.34303, 1.34316, 334, 8, 0)
(1758734460, 1.34316, 1.34335, 1.34312, 1.34325, 210, 8, 0)
(1758734520, 1.34326, 1.34357, 1.34324, 1.34343, 247, 9, 0)
(1758734580, 1.34343, 1.34352, 1.34329, 1.34335, 170, 9, 0)
(1758734640, 1.34335, 1.34344, 1.3433, 1.34341, 214, 10, 0)
(1758734700, 1.3434, 1.34366, 1.34337, 1.34354, 252, 9, 0)
(1758734760, 1.34354, 1.34363, 1.34349, 1.34355, 199, 9, 0)
(1758734820, 1.34356, 1.34401, 1.34356, 1.34401, 201, 9, 0)
(1758734880, 1.34401, 1.34444, 1.34395, 1.34438, 288, 8, 0)
(1758734940, 1.34437, 1.34448, 1.34433, 1.34437, 210, 10, 0)
(1758735000, 1.34436, 1.34459, 1.34435, 1.34447, 220, 9, 0)
(1758735060, 1.34447, 1.3446, 1.34435, 1.34448, 200, 9, 0)
(1758735120, 1.34448, 1.3447, 1.34435, 1.34446, 235, 9, 0)
(1758735180, 1.34445, 1.34455, 1.34429, 1.3443, 186, 10, 0)
(1758735240, 1.34431, 1.34445, 1.3443, 1.34443, 166, 9, 0)
(1758735300, 1.34443, 1.34468, 1.34438, 1.34463, 196, 8, 0)
(1758735360, 1.34463, 1.34465, 1.34443, 1.34445, 181, 9, 0)
(1758735420, 1.34446, 1.34447, 1.34433, 1.34434, 137, 10, 0)
(1758735480, 1.34434, 1.34435, 1.34423, 1.34425, 144, 10, 0)
(1758735540, 1.34424, 1.34496, 1.34418, 1.34495, 152, 10, 0)
(1758735600, 1.34492, 1.34539, 1.34489, 1.345, 246, 10, 0)
(1758735660, 1.34499, 1.3456, 1.34496, 1.34547, 248, 8, 0)
(1758735720, 1.34546, 1.34556, 1.34527, 1.34528, 220, 8, 0)
(1758735780, 1.34529, 1.34556, 1.34523, 1.34534, 271, 10, 0)
(1758735840, 1.34534, 1.34563, 1.34527, 1.34559, 308, 8, 0)
(1758735900, 1.34561, 1.34566, 1.34545, 1.34558, 200, 11, 0)
(1758735960, 1.34558, 1.34559, 1.34546, 1.34547, 158, 8, 0)
(1758736020, 1.34546, 1.34565, 1.34546, 1.34555, 184, 8, 0)
(1758736080, 1.34555, 1.34577, 1.34552, 1.34557, 205, 8, 0)
(1758736140, 1.34557, 1.34569, 1.34546, 1.34554, 198, 9, 0)
(1758736200, 1.34555, 1.34572, 1.34541, 1.34544, 252, 9, 0)
(1758736260, 1.34544, 1.34553, 1.34536, 1.34542, 261, 8, 0)
(1758736320, 1.34542, 1.34563, 1.34542, 1.34556, 274, 8, 0)
(1758736380, 1.34556, 1.34556, 1.34505, 1.34523, 383, 8, 0)
(1758736440, 1.34523, 1.34529, 1.34505, 1.34514, 297, 8, 0)
(1758736500, 1.34511, 1.34511, 1.34494, 1.34509, 231, 8, 0)
(1758736560, 1.34509, 1.34521, 1.34504, 1.34517, 270, 10, 0)
(1758736620, 1.34516, 1.34516, 1.34496, 1.34506, 374, 8, 0)
(1758736680, 1.34506, 1.34517, 1.34503, 1.3451, 235, 8, 0)
(1758736740, 1.3451, 1.34517, 1.34505, 1.34513, 189, 8, 0)
(1758736800, 1.34513, 1.34547, 1.34513, 1.34543, 247, 8, 0)
(1758736860, 1.34542, 1.34567, 1.34542, 1.34557, 215, 8, 0)
(1758736920, 1.34557, 1.34558, 1.34542, 1.34546, 259, 8, 0)
(1758736980, 1.34546, 1.34548, 1.34538, 1.34543, 35, 9, 0)

Display dataframe with data
                   time     open     high      low    close  tick_volume  spread  real_volume
0   2025-09-24 16:23:00  1.34417  1.34417  1.34387  1.34396          217       9            0
1   2025-09-24 16:24:00  1.34396  1.34412  1.34396  1.34406          177      10            0
2   2025-09-24 16:25:00  1.34406  1.34414  1.34382  1.34384          209       9            0
3   2025-09-24 16:26:00  1.34383  1.34383  1.34354  1.34365          214       8            0
4   2025-09-24 16:27:00  1.34365  1.34378  1.34362  1.34368          136       9            0
..                  ...      ...      ...      ...      ...          ...     ...          ...
96  2025-09-24 17:59:00  1.34510  1.34517  1.34505  1.34513          189       8            0
97  2025-09-24 18:00:00  1.34513  1.34547  1.34513  1.34543          247       8            0
98  2025-09-24 18:01:00  1.34542  1.34567  1.34542  1.34557          215       8            0
99  2025-09-24 18:02:00  1.34557  1.34558  1.34542  1.34546          259       8            0
100 2025-09-24 18:03:00  1.34546  1.34548  1.34538  1.34543           35       9            0

[101 rows x 8 columns]

In [6]:
# Doi ten cot
rates_frame.rename(columns={'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Close', 'tick_volume': 'Volume', 'spread': 'Spread', 'real_volume': 'Real Volume'}, inplace=True)

In [7]:
# In ra dataframe
print(rates_frame)

                   time     Open     High      Low    Close  Volume  Spread  Real Volume
0   2025-09-24 16:23:00  1.34417  1.34417  1.34387  1.34396     217       9            0
1   2025-09-24 16:24:00  1.34396  1.34412  1.34396  1.34406     177      10            0
2   2025-09-24 16:25:00  1.34406  1.34414  1.34382  1.34384     209       9            0
3   2025-09-24 16:26:00  1.34383  1.34383  1.34354  1.34365     214       8            0
4   2025-09-24 16:27:00  1.34365  1.34378  1.34362  1.34368     136       9            0
..                  ...      ...      ...      ...      ...     ...     ...          ...
96  2025-09-24 17:59:00  1.34510  1.34517  1.34505  1.34513     189       8            0
97  2025-09-24 18:00:00  1.34513  1.34547  1.34513  1.34543     247       8            0
98  2025-09-24 18:01:00  1.34542  1.34567  1.34542  1.34557     215       8            0
99  2025-09-24 18:02:00  1.34557  1.34558  1.34542  1.34546     259       8            0
100 2025-09-24 18:03:00  1.34546  1.34548  1.34538  1.34543      35       9            0

[101 rows x 8 columns]

In [9]:
data = rates_frame.copy()
data

                   time     Open     High      Low    Close  Volume  Spread  Real Volume
0   2025-09-24 16:23:00  1.34417  1.34417  1.34387  1.34396     217       9            0
1   2025-09-24 16:24:00  1.34396  1.34412  1.34396  1.34406     177      10            0
2   2025-09-24 16:25:00  1.34406  1.34414  1.34382  1.34384     209       9            0
3   2025-09-24 16:26:00  1.34383  1.34383  1.34354  1.34365     214       8            0
4   2025-09-24 16:27:00  1.34365  1.34378  1.34362  1.34368     136       9            0
..                  ...      ...      ...      ...      ...     ...     ...          ...
96  2025-09-24 17:59:00  1.34510  1.34517  1.34505  1.34513     189       8            0
97  2025-09-24 18:00:00  1.34513  1.34547  1.34513  1.34543     247       8            0
98  2025-09-24 18:01:00  1.34542  1.34567  1.34542  1.34557     215       8            0
99  2025-09-24 18:02:00  1.34557  1.34558  1.34542  1.34546     259       8            0
100 2025-09-24 18:03:00  1.34546  1.34548  1.34538  1.34543      35       9            0

[101 rows x 8 columns]

In [11]:
data.head(10)

                 time     Open     High      Low    Close  Volume  Spread  Real Volume
0 2025-09-24 16:23:00  1.34417  1.34417  1.34387  1.34396     217       9            0
1 2025-09-24 16:24:00  1.34396  1.34412  1.34396  1.34406     177      10            0
2 2025-09-24 16:25:00  1.34406  1.34414  1.34382  1.34384     209       9            0
3 2025-09-24 16:26:00  1.34383  1.34383  1.34354  1.34365     214       8            0
4 2025-09-24 16:27:00  1.34365  1.34378  1.34362  1.34368     136       9            0
5 2025-09-24 16:28:00  1.34368  1.34400  1.34361  1.34398     155      10            0
6 2025-09-24 16:29:00  1.34398  1.34402  1.34388  1.34395     187      10            0
7 2025-09-24 16:30:00  1.34392  1.34392  1.34375  1.34376     284      10            0
8 2025-09-24 16:31:00  1.34376  1.34377  1.34350  1.34358     295      10            0
9 2025-09-24 16:32:00  1.34358  1.34358  1.34332  1.34336     226      10            0

In [10]:
# Parse du lieu tu data (co 101 record) 1m thanh 5m
data_5m = data.resample('5min', on='time').agg({
    'Open': 'first',
    'High': 'max',
    'Low': 'min',
    'Close': 'last',
    'Volume': 'sum'
})
data_5m

                        Open     High      Low    Close  Volume
time
2025-09-24 16:20:00  1.34417  1.34417  1.34387  1.34406     394
2025-09-24 16:25:00  1.34406  1.34414  1.34354  1.34395     901
2025-09-24 16:30:00  1.34392  1.34392  1.34267  1.34268    1262
2025-09-24 16:35:00  1.34268  1.34329  1.34266  1.34329    1178
2025-09-24 16:40:00  1.34328  1.34347  1.34276  1.34283    1182
2025-09-24 16:45:00  1.34282  1.34356  1.34276  1.34345    1308
2025-09-24 16:50:00  1.34345  1.34398  1.34334  1.34367    1270
2025-09-24 16:55:00  1.34368  1.34428  1.34368  1.34375    1110
2025-09-24 17:00:00  1.34379  1.34379  1.34268  1.34325    1480
2025-09-24 17:05:00  1.34327  1.34336  1.34292  1.34317    1325
2025-09-24 17:10:00  1.34316  1.34369  1.34311  1.34350    1356
2025-09-24 17:15:00  1.34348  1.34376  1.34329  1.34346    1085
2025-09-24 17:20:00  1.34346  1.34357  1.34303  1.34341    1175
2025-09-24 17:25:00  1.34340  1.34448  1.34337  1.34437    1150
2025-09-24 17:30:00  1.34436  1.34470  1.34429  1.34443    1007
2025-09-24 17:35:00  1.34443  1.34496  1.34418  1.34495     810
2025-09-24 17:40:00  1.34492  1.34563  1.34489  1.34559    1293
2025-09-24 17:45:00  1.34561  1.34577  1.34545  1.34554     945
2025-09-24 17:50:00  1.34555  1.34572  1.34505  1.34514    1467
2025-09-24 17:55:00  1.34511  1.34521  1.34494  1.34513    1299
2025-09-24 18:00:00  1.34513  1.34567  1.34513  1.34543     756

In [ ]:
# Toi muon tinh theo boi so cua 5, bo cac cay dau tien du ra, group theo 5

# Process

In [203]:
# Them/ Cai talib
import talib
data["MA10"] = talib.SMA(data["Close"], timeperiod=10)
data["MA20"] = talib.SMA(data["Close"], timeperiod=20)
data

                  time     Open     High      Low    Close  Volume  Spread  Real Volume      MA10      MA20
0  2025-09-24 15:54:00  1.34416  1.34431  1.34385  1.34394     236      10            0       NaN       NaN
1  2025-09-24 15:55:00  1.34393  1.34413  1.34365  1.34412     313       8            0       NaN       NaN
2  2025-09-24 15:56:00  1.34411  1.34411  1.34369  1.34400     293       8            0       NaN       NaN
3  2025-09-24 15:57:00  1.34400  1.34448  1.34399  1.34442     351       8            0       NaN       NaN
4  2025-09-24 15:58:00  1.34441  1.34458  1.34434  1.34449     250       9            0       NaN       NaN
..                 ...      ...      ...      ...      ...     ...     ...          ...       ...       ...
95 2025-09-24 17:29:00  1.34437  1.34448  1.34433  1.34437     210      10            0  1.343645  1.343575
96 2025-09-24 17:30:00  1.34436  1.34459  1.34435  1.34447     220       9            0  1.343776  1.343636
97 2025-09-24 17:31:00  1.34447  1.34460  1.34435  1.34448     200       9            0  1.343899  1.343682
98 2025-09-24 17:32:00  1.34448  1.34470  1.34435  1.34446     235       9            0  1.344002  1.343727
99 2025-09-24 17:33:00  1.34445  1.34455  1.34434  1.34438      90      11            0  1.344105  1.343773

[100 rows x 10 columns]

# Tinh toan chien luoc

In [204]:
import numpy as np
data["Buy_Signal"] = (data["MA10"] > data["MA20"])
data["Sell_Signal"] = (data["MA10"] < data["MA20"])
data
# In ra dataframe

                  time     Open     High      Low    Close  Volume  Spread  Real Volume      MA10      MA20  Buy_Signal  Sell_Signal
0  2025-09-24 15:54:00  1.34416  1.34431  1.34385  1.34394     236      10            0       NaN       NaN       False        False
1  2025-09-24 15:55:00  1.34393  1.34413  1.34365  1.34412     313       8            0       NaN       NaN       False        False
2  2025-09-24 15:56:00  1.34411  1.34411  1.34369  1.34400     293       8            0       NaN       NaN       False        False
3  2025-09-24 15:57:00  1.34400  1.34448  1.34399  1.34442     351       8            0       NaN       NaN       False        False
4  2025-09-24 15:58:00  1.34441  1.34458  1.34434  1.34449     250       9            0       NaN       NaN       False        False
..                 ...      ...      ...      ...      ...     ...     ...          ...       ...       ...         ...          ...
95 2025-09-24 17:29:00  1.34437  1.34448  1.34433  1.34437     210      10            0  1.343645  1.343575        True        False
96 2025-09-24 17:30:00  1.34436  1.34459  1.34435  1.34447     220       9            0  1.343776  1.343636        True        False
97 2025-09-24 17:31:00  1.34447  1.34460  1.34435  1.34448     200       9            0  1.343899  1.343682        True        False
98 2025-09-24 17:32:00  1.34448  1.34470  1.34435  1.34446     235       9            0  1.344002  1.343727        True        False
99 2025-09-24 17:33:00  1.34445  1.34455  1.34434  1.34438      90      11            0  1.344105  1.343773        True        False

[100 rows x 12 columns]

# Day sang redis

In [205]:
last_record = data.iloc[-2]
last_record

time           2025-09-24 17:32:00
Open                       1.34448
High                        1.3447
Low                        1.34435
Close                      1.34446
Volume                         235
Spread                           9
Real Volume                      0
MA10                      1.344002
MA20                      1.343727
Buy_Signal                    True
Sell_Signal                  False
Name: 98, dtype: object

In [206]:
# if last_record["Buy_Signal"]:
#     print("Buy Signal")
# else:
#     print("Sell Signal")

# Luu du lieu
import redis
# ##############################################Step 3: Đẩy dữ liệu qua Redis##############################################
# Nếu có tín hiệu thì đẩy qua Redis
# Datetime  Open    High    Low	Close   Volume  SMA short_ema   long_ema    MACD    Signal_Line     Buy_Signal      Sell_Signal
# Tạo kết nối Redis
r = redis.Redis(host='localhost', port=6379, db=15) # 0-5 CK, 6-10 Crypto, 11-15 Forex
# Tạo hash key
hash_key = 'OG_FX_Buoi 5'
last_record = data.iloc[-2]

# Chuyển đổi record cuối cùng thành từ điển và lưu vào Redis dưới dạng hash
if(last_record['Buy_Signal'] == True or last_record['Sell_Signal'] == True):
    for field, value in last_record.to_dict().items():
        # Chuyển đổi giá trị uint64 và Timestamp thành chuỗi
        if isinstance(value, pd.Timestamp):
            value = value.isoformat()
        elif isinstance(value, (int, np.uint64)):
            value = str(value)
        r.hset(hash_key, field, value)  
        r.hset(hash_key, 'Symbol', symbol)
        r.hset(hash_key, 'Insertdate', datetime.now().isoformat())
        last_record['Insertdate'] = datetime.now().isoformat()
    print(last_record)   
else:
    print(last_record)   
    print('Không có tín hiệu!')

time                  2025-09-24 17:32:00
Open                              1.34448
High                               1.3447
Low                               1.34435
Close                             1.34446
Volume                                235
Spread                                  9
Real Volume                             0
MA10                             1.344002
MA20                             1.343727
Buy_Signal                           True
Sell_Signal                         False
Insertdate     2025-09-24T21:33:32.461491
Name: 98, dtype: object

C:\Users\Administrator\AppData\Local\Temp\ipykernel_13020\2957446752.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_record['Insertdate'] = datetime.now().isoformat()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13020\2957446752.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_record['Insertdate'] = datetime.now().isoformat()