# --------------Chiến lược giao dịch theo chỉ số biến động------------------------------------------

# 1. Mã và thời gian: Du lieu cua SPY (S & P 500)

# Buoc 1: Load du lieu

In [1]:
import pandas as pd
import yfinance as yf

symbols = ['SPY', '^VIX']  # Danh sách các ký hiệu bạn muốn lấy dữ liệu
start_date = "2024-01-01"
end_date = "2024-03-14"
timeframe = '1d'

def load_data(symbols, start_date, end_date):
    data = yf.download(symbols, start=start_date, end=end_date, interval=timeframe)
    
    return data

data = load_data(symbols, start_date, end_date)

data

[*********************100%%**********************]  2 of 2 completed

             Adj Close              Close               High             \
                   SPY   ^VIX         SPY   ^VIX         SPY       ^VIX
Date
2024-01-02  472.649994  13.20  472.649994  13.20  473.670013  14.230000
2024-01-03  468.790009  14.04  468.790009  14.04  471.190002  14.220000
2024-01-04  467.279999  14.13  467.279999  14.13  470.959991  14.200000
2024-01-05  467.920013  13.35  467.920013  13.35  470.440002  14.580000
2024-01-08  474.600006  13.08  474.600006  13.08  474.750000  14.180000
2024-01-09  473.880005  12.76  473.880005  12.76  474.929993  13.450000
2024-01-10  476.559998  12.69  476.559998  12.69  477.450012  12.950000
2024-01-11  476.350006  12.44  476.350006  12.44  478.119995  13.310000
2024-01-12  476.679993  12.70  476.679993  12.70  478.600006  13.080000
2024-01-16  474.929993  13.84  474.929993  13.84  476.609985  14.350000
2024-01-17  472.290009  14.79  472.290009  14.79  472.790009  15.400000
2024-01-18  476.489990  14.13  476.489990  14.13  477.059998  14.890000
2024-01-19  482.429993  13.30  482.429993  13.30  482.720001  14.580000
2024-01-22  483.450012  13.19  483.450012  13.19  485.220001  13.840000
2024-01-23  484.859985  12.55  484.859985  12.55  485.109985  13.290000
2024-01-24  485.390015  13.14  485.390015  13.14  488.769989  13.180000
2024-01-25  488.029999  13.45  488.029999  13.45  488.309998  13.580000
2024-01-26  487.410004  13.26  487.410004  13.26  489.119995  14.100000
2024-01-29  491.269989  13.60  491.269989  13.60  491.420013  15.350000
2024-01-30  490.890015  13.31  490.890015  13.31  491.619995  13.740000
2024-01-31  482.880005  14.35  482.880005  14.35  489.079987  14.610000
2024-02-01  489.200012  13.88  489.200012  13.88  489.230011  14.630000
2024-02-02  494.350006  13.85  494.350006  13.85  496.049988  14.230000
2024-02-05  492.549988  13.67  492.549988  13.67  494.380005  14.530000
2024-02-06  493.980011  13.06  493.980011  13.06  494.320007  13.780000
2024-02-07  498.100006  12.83  498.100006  12.83  498.529999  13.130000
2024-02-08  498.320007  12.79  498.320007  12.79  498.709991  13.170000
2024-02-09  501.200012  12.93  501.200012  12.93  501.649994  13.010000
2024-02-12  500.980011  13.93  500.980011  13.93  503.500000  13.940000
2024-02-13  494.079987  15.85  494.079987  15.85  497.089996  17.940001
2024-02-14  498.570007  14.38  498.570007  14.38  499.070007  15.470000
2024-02-15  502.010010  14.01  502.010010  14.01  502.200012  14.640000
2024-02-16  499.510010  14.24  499.510010  14.24  502.869995  14.710000
2024-02-20  496.760010  15.42  496.760010  15.42  498.410004  15.910000
2024-02-21  497.209991  15.34  497.209991  15.34  497.369995  16.120001
2024-02-22  507.500000  14.54  507.500000  14.54  508.489990  14.640000
2024-02-23  507.850006  13.75  507.850006  13.75  510.130005  14.310000
2024-02-26  505.989990  13.74  505.989990  13.74  508.750000  14.200000
2024-02-27  506.929993  13.43  506.929993  13.43  507.160004  13.750000
2024-02-28  506.260010  13.84  506.260010  13.84  506.859985  13.900000
2024-02-29  508.079987  13.40  508.079987  13.40  509.739990  14.150000
2024-03-01  512.849976  13.11  512.849976  13.11  513.289978  13.660000
2024-03-04  512.299988  13.49  512.299988  13.49  514.200012  13.580000
2024-03-05  507.179993  14.46  507.179993  14.46  510.700012  15.100000
2024-03-06  509.750000  14.50  509.750000  14.50  512.070007  14.930000
2024-03-07  514.809998  14.44  514.809998  14.44  515.890015  14.980000
2024-03-08  511.720001  14.74  511.720001  14.74  518.219971  15.530000
2024-03-11  511.279999  15.22  511.279999  15.22  511.880005  16.040001
2024-03-12  516.780029  13.84  516.780029  13.84  517.380005  15.200000
2024-03-13  516.650024  13.95  516.650024  13.95  517.109985  13.970000

                   Low               Open            Volume
                   SPY   ^VIX         SPY   ^VIX        SPY ^VIX
Date
2024-01-02  470.489990  13.10  472.160004  13.22  123623700    0
2024-01-03  468.170013  13.33  470.429993  13.35  103585900    0
2024-01-04  467.049988  13.64  468.299988  13.93   84232200    0
2024-01-05  466.429993  13.29  467.489990  14.24   86060800    0
2024-01-08  468.299988  13.02  468.429993  14.00   74879100    0
2024-01-09  471.350006  12.74  471.869995  13.20   65931400    0
2024-01-10  473.869995  12.67  474.160004  12.86   67310600    0
2024-01-11  472.260010  12.35  477.589996  12.64   77940700    0
2024-01-12  475.230011  12.47  477.839996  12.66   57944000    0
2024-01-16  473.059998  13.52  475.260010  14.12   85014900    0
2024-01-17  469.869995  14.38  471.820007  14.59   68843900    0
2024-01-18  472.420013  13.89  474.010010  14.85   91856200    0
2024-01-19  476.540009  13.28  477.649994  13.80  110733300    0
2024-01-22  482.779999  13.17  484.010010  13.77   75844900    0
2024-01-23  482.890015  12.53  484.010010  13.20   49945300    0
2024-01-24  484.880005  12.41  487.809998  12.66   81765000    0
2024-01-25  485.390015  13.06  487.579987  13.18   72525000    0
2024-01-26  486.540009  13.20  487.589996  13.73   76641600    0
2024-01-29  487.170013  13.59  487.730011  13.98   61322800    0
2024-01-30  490.109985  13.23  490.559998  13.69   58618400    0
2024-01-31  482.859985  13.18  488.619995  13.42  126011100    0
2024-02-01  483.799988  13.87  484.630005  14.21   91891600    0
2024-02-02  489.299988  13.39  489.649994  13.95   99147700    0
2024-02-05  490.230011  13.58  493.700012  14.37   75757100    0
2024-02-06  492.049988  12.98  493.519989  13.57   55918600    0
2024-02-07  495.359985  12.81  496.290009  13.06   70556500    0
2024-02-08  497.260010  12.74  498.100006  12.95   52343600    0
2024-02-09  498.489990  12.69  498.839996  12.79   63979400    0
2024-02-12  500.239990  13.34  501.170013  13.48   56502300    0
2024-02-13  490.720001  13.43  494.529999  13.96  113099200    0
2024-02-14  494.399994  14.22  496.790009  15.38   68387800    0
2024-02-15  498.799988  13.94  499.290009  14.27   61683000    0
2024-02-16  498.750000  13.75  501.700012  13.94   75461200    0
2024-02-20  494.450012  15.07  497.720001  15.09   71736700    0
2024-02-21  493.559998  15.22  495.420013  15.54   59603800    0
2024-02-22  503.019989  14.12  504.010010  14.28   76402500    0
2024-02-23  507.100006  13.64  509.269989  14.31   61321800    0
2024-02-26  505.859985  13.66  508.299988  14.17   50386700    0
2024-02-27  504.750000  13.41  506.700012  13.63   48854500    0
2024-02-28  504.959991  13.44  505.329987  13.52   56506600    0
2024-02-29  505.350006  13.30  508.070007  14.14   83924800    0
2024-03-01  508.559998  13.08  508.980011  13.34   76805900    0
2024-03-04  512.000000  13.32  512.030029  13.49   49799300    0
2024-03-05  504.910004  13.75  510.239990  13.75   72855600    0
2024-03-06  508.420013  13.89  510.549988  14.27   68382400    0
2024-03-07  509.809998  14.25  513.140015  14.98   58652100    0
2024-03-08  511.130005  13.97  515.460022  14.22   86425500    0
2024-03-11  508.500000  15.13  510.480011  15.51   62557200    0
2024-03-12  510.859985  13.81  513.450012  14.97   73031700    0
2024-03-13  515.669983  13.74  517.109985  13.89   14127463    0

# Buoc 2: Viet ham kiem tra dieu kien mua hay ban

In [2]:
# Định nghĩa ngưỡng cho VIX
vix_threshold_high = 15  # ví dụ, giá trị này cần được tinh chỉnh
vix_threshold_low = 13   # ví dụ, giá trị này cần được tinh chỉnh

# Xác định tín hiệu mua và bán
# Bởi vì dữ liệu được trả về từ yfinance là MultiIndex DataFrame, chúng ta cần xác định đúng cấu trúc để truy cập dữ liệu

# Điều này giả sử rằng khi VIX cao, đó là tín hiệu bán cho SPY và ngược lại
data['Buy_Signal'] = data[('Close', '^VIX')] < vix_threshold_low
data['Sell_Signal'] = data[('Close', '^VIX')] > vix_threshold_high

data

             Adj Close              Close               High             \
                   SPY   ^VIX         SPY   ^VIX         SPY       ^VIX
Date
2024-01-02  472.649994  13.20  472.649994  13.20  473.670013  14.230000
2024-01-03  468.790009  14.04  468.790009  14.04  471.190002  14.220000
2024-01-04  467.279999  14.13  467.279999  14.13  470.959991  14.200000
2024-01-05  467.920013  13.35  467.920013  13.35  470.440002  14.580000
2024-01-08  474.600006  13.08  474.600006  13.08  474.750000  14.180000
2024-01-09  473.880005  12.76  473.880005  12.76  474.929993  13.450000
2024-01-10  476.559998  12.69  476.559998  12.69  477.450012  12.950000
2024-01-11  476.350006  12.44  476.350006  12.44  478.119995  13.310000
2024-01-12  476.679993  12.70  476.679993  12.70  478.600006  13.080000
2024-01-16  474.929993  13.84  474.929993  13.84  476.609985  14.350000
2024-01-17  472.290009  14.79  472.290009  14.79  472.790009  15.400000
2024-01-18  476.489990  14.13  476.489990  14.13  477.059998  14.890000
2024-01-19  482.429993  13.30  482.429993  13.30  482.720001  14.580000
2024-01-22  483.450012  13.19  483.450012  13.19  485.220001  13.840000
2024-01-23  484.859985  12.55  484.859985  12.55  485.109985  13.290000
2024-01-24  485.390015  13.14  485.390015  13.14  488.769989  13.180000
2024-01-25  488.029999  13.45  488.029999  13.45  488.309998  13.580000
2024-01-26  487.410004  13.26  487.410004  13.26  489.119995  14.100000
2024-01-29  491.269989  13.60  491.269989  13.60  491.420013  15.350000
2024-01-30  490.890015  13.31  490.890015  13.31  491.619995  13.740000
2024-01-31  482.880005  14.35  482.880005  14.35  489.079987  14.610000
2024-02-01  489.200012  13.88  489.200012  13.88  489.230011  14.630000
2024-02-02  494.350006  13.85  494.350006  13.85  496.049988  14.230000
2024-02-05  492.549988  13.67  492.549988  13.67  494.380005  14.530000
2024-02-06  493.980011  13.06  493.980011  13.06  494.320007  13.780000
2024-02-07  498.100006  12.83  498.100006  12.83  498.529999  13.130000
2024-02-08  498.320007  12.79  498.320007  12.79  498.709991  13.170000
2024-02-09  501.200012  12.93  501.200012  12.93  501.649994  13.010000
2024-02-12  500.980011  13.93  500.980011  13.93  503.500000  13.940000
2024-02-13  494.079987  15.85  494.079987  15.85  497.089996  17.940001
2024-02-14  498.570007  14.38  498.570007  14.38  499.070007  15.470000
2024-02-15  502.010010  14.01  502.010010  14.01  502.200012  14.640000
2024-02-16  499.510010  14.24  499.510010  14.24  502.869995  14.710000
2024-02-20  496.760010  15.42  496.760010  15.42  498.410004  15.910000
2024-02-21  497.209991  15.34  497.209991  15.34  497.369995  16.120001
2024-02-22  507.500000  14.54  507.500000  14.54  508.489990  14.640000
2024-02-23  507.850006  13.75  507.850006  13.75  510.130005  14.310000
2024-02-26  505.989990  13.74  505.989990  13.74  508.750000  14.200000
2024-02-27  506.929993  13.43  506.929993  13.43  507.160004  13.750000
2024-02-28  506.260010  13.84  506.260010  13.84  506.859985  13.900000
2024-02-29  508.079987  13.40  508.079987  13.40  509.739990  14.150000
2024-03-01  512.849976  13.11  512.849976  13.11  513.289978  13.660000
2024-03-04  512.299988  13.49  512.299988  13.49  514.200012  13.580000
2024-03-05  507.179993  14.46  507.179993  14.46  510.700012  15.100000
2024-03-06  509.750000  14.50  509.750000  14.50  512.070007  14.930000
2024-03-07  514.809998  14.44  514.809998  14.44  515.890015  14.980000
2024-03-08  511.720001  14.74  511.720001  14.74  518.219971  15.530000
2024-03-11  511.279999  15.22  511.279999  15.22  511.880005  16.040001
2024-03-12  516.780029  13.84  516.780029  13.84  517.380005  15.200000
2024-03-13  516.650024  13.95  516.650024  13.95  517.109985  13.970000

                   Low               Open            Volume      Buy_Signal  \
                   SPY   ^VIX         SPY   ^VIX        SPY ^VIX
Date
2024-01-02  470.489990  13.10  472.160004  13.22  123623700    0      False
2024-01-03  468.170013  13.33  470.429993  13.35  103585900    0      False
2024-01-04  467.049988  13.64  468.299988  13.93   84232200    0      False
2024-01-05  466.429993  13.29  467.489990  14.24   86060800    0      False
2024-01-08  468.299988  13.02  468.429993  14.00   74879100    0      False
2024-01-09  471.350006  12.74  471.869995  13.20   65931400    0       True
2024-01-10  473.869995  12.67  474.160004  12.86   67310600    0       True
2024-01-11  472.260010  12.35  477.589996  12.64   77940700    0       True
2024-01-12  475.230011  12.47  477.839996  12.66   57944000    0       True
2024-01-16  473.059998  13.52  475.260010  14.12   85014900    0      False
2024-01-17  469.869995  14.38  471.820007  14.59   68843900    0      False
2024-01-18  472.420013  13.89  474.010010  14.85   91856200    0      False
2024-01-19  476.540009  13.28  477.649994  13.80  110733300    0      False
2024-01-22  482.779999  13.17  484.010010  13.77   75844900    0      False
2024-01-23  482.890015  12.53  484.010010  13.20   49945300    0       True
2024-01-24  484.880005  12.41  487.809998  12.66   81765000    0      False
2024-01-25  485.390015  13.06  487.579987  13.18   72525000    0      False
2024-01-26  486.540009  13.20  487.589996  13.73   76641600    0      False
2024-01-29  487.170013  13.59  487.730011  13.98   61322800    0      False
2024-01-30  490.109985  13.23  490.559998  13.69   58618400    0      False
2024-01-31  482.859985  13.18  488.619995  13.42  126011100    0      False
2024-02-01  483.799988  13.87  484.630005  14.21   91891600    0      False
2024-02-02  489.299988  13.39  489.649994  13.95   99147700    0      False
2024-02-05  490.230011  13.58  493.700012  14.37   75757100    0      False
2024-02-06  492.049988  12.98  493.519989  13.57   55918600    0      False
2024-02-07  495.359985  12.81  496.290009  13.06   70556500    0       True
2024-02-08  497.260010  12.74  498.100006  12.95   52343600    0       True
2024-02-09  498.489990  12.69  498.839996  12.79   63979400    0       True
2024-02-12  500.239990  13.34  501.170013  13.48   56502300    0      False
2024-02-13  490.720001  13.43  494.529999  13.96  113099200    0      False
2024-02-14  494.399994  14.22  496.790009  15.38   68387800    0      False
2024-02-15  498.799988  13.94  499.290009  14.27   61683000    0      False
2024-02-16  498.750000  13.75  501.700012  13.94   75461200    0      False
2024-02-20  494.450012  15.07  497.720001  15.09   71736700    0      False
2024-02-21  493.559998  15.22  495.420013  15.54   59603800    0      False
2024-02-22  503.019989  14.12  504.010010  14.28   76402500    0      False
2024-02-23  507.100006  13.64  509.269989  14.31   61321800    0      False
2024-02-26  505.859985  13.66  508.299988  14.17   50386700    0      False
2024-02-27  504.750000  13.41  506.700012  13.63   48854500    0      False
2024-02-28  504.959991  13.44  505.329987  13.52   56506600    0      False
2024-02-29  505.350006  13.30  508.070007  14.14   83924800    0      False
2024-03-01  508.559998  13.08  508.980011  13.34   76805900    0      False
2024-03-04  512.000000  13.32  512.030029  13.49   49799300    0      False
2024-03-05  504.910004  13.75  510.239990  13.75   72855600    0      False
2024-03-06  508.420013  13.89  510.549988  14.27   68382400    0      False
2024-03-07  509.809998  14.25  513.140015  14.98   58652100    0      False
2024-03-08  511.130005  13.97  515.460022  14.22   86425500    0      False
2024-03-11  508.500000  15.13  510.480011  15.51   62557200    0      False
2024-03-12  510.859985  13.81  513.450012  14.97   73031700    0      False
2024-03-13  515.669983  13.74  517.109985  13.89   14127463    0      False

           Sell_Signal

Date
2024-01-02       False
2024-01-03       False
2024-01-04       False
2024-01-05       False
2024-01-08       False
2024-01-09       False
2024-01-10       False
2024-01-11       False
2024-01-12       False
2024-01-16       False
2024-01-17       False
2024-01-18       False
2024-01-19       False
2024-01-22       False
2024-01-23       False
2024-01-24       False
2024-01-25       False
2024-01-26       False
2024-01-29       False
2024-01-30       False
2024-01-31       False
2024-02-01       False
2024-02-02       False
2024-02-05       False
2024-02-06       False
2024-02-07       False
2024-02-08       False
2024-02-09       False
2024-02-12       False
2024-02-13        True
2024-02-14       False
2024-02-15       False
2024-02-16       False
2024-02-20        True
2024-02-21        True
2024-02-22       False
2024-02-23       False
2024-02-26       False
2024-02-27       False
2024-02-28       False
2024-02-29       False
2024-03-01       False
2024-03-04       False
2024-03-05       False
2024-03-06       False
2024-03-07       False
2024-03-08       False
2024-03-11        True
2024-03-12       False
2024-03-13       False

# Buoc 3: Ve bieu do

In [3]:
import plotly.graph_objects as go
import pandas as pd

# Trực quan hóa dữ liệu sử dụng Plotly
fig = go.Figure()

# Lấy cột Close
close_data = data['Close']

# Thêm biểu đồ cho SPY
fig.add_trace(go.Scatter(x=close_data.index, y=close_data['SPY'], mode='lines', name='SPY'))

# Thêm biểu đồ cho VIX
fig.add_trace(go.Scatter(x=close_data.index, y=close_data['^VIX'], mode='lines', name='VIX', yaxis="y2"))

# Thêm tín hiệu mua và bán vào biểu đồ
fig.add_trace(go.Scatter(x=close_data[data['Buy_Signal']].index, y=close_data['SPY'][data['Buy_Signal']], mode='markers', marker=dict(color='Green', size=10, symbol='triangle-up'), name='Buy Signal'))
fig.add_trace(go.Scatter(x=close_data[data['Sell_Signal']].index, y=close_data['SPY'][data['Sell_Signal']], mode='markers', marker=dict(color='Red', size=10, symbol='triangle-down'), name='Sell Signal'))

# Cập nhật layout
fig.update_layout(title='SPY vs VIX with Buy & Sell Signals',
                  xaxis_title='Date',
                  yaxis=dict(title='SPY Price'),
                  yaxis2=dict(title='VIX', overlaying='y', side='right'),
                  # template='plotly_dark'
                  )

# Hiển thị biểu đồ
fig.show()