# --------------Chiến lược giao dịch theo chỉ số biến động------------------------------------------

# 1. Mã và thời gian: Du lieu cua SPY (S & P 500)

In [108]:
import pandas as pd
import yfinance as yf

symbols = ['SPY', '^VIX']  # Danh sách các ký hiệu bạn muốn lấy dữ liệu
start_date = "2024-01-01"
end_date = "2024-03-14"
timeframe = '1d'

# 2. Load data

In [109]:
def load_data(symbols, start_date, end_date):
    data = yf.download(symbols, start=start_date, end=end_date, interval=timeframe)
    
    return data

data = load_data(symbols, start_date, end_date)

data

[*********************100%%**********************]  2 of 2 completed

             Adj Close              Close               High             \
                   SPY   ^VIX         SPY   ^VIX         SPY       ^VIX
Date
2024-01-02  472.649994  13.20  472.649994  13.20  473.670013  14.230000
2024-01-03  468.790009  14.04  468.790009  14.04  471.190002  14.220000
2024-01-04  467.279999  14.13  467.279999  14.13  470.959991  14.200000
2024-01-05  467.920013  13.35  467.920013  13.35  470.440002  14.580000
2024-01-08  474.600006  13.08  474.600006  13.08  474.750000  14.180000
2024-01-09  473.880005  12.76  473.880005  12.76  474.929993  13.450000
2024-01-10  476.559998  12.69  476.559998  12.69  477.450012  12.950000
2024-01-11  476.350006  12.44  476.350006  12.44  478.119995  13.310000
2024-01-12  476.679993  12.70  476.679993  12.70  478.600006  13.080000
2024-01-16  474.929993  13.84  474.929993  13.84  476.609985  14.350000
2024-01-17  472.290009  14.79  472.290009  14.79  472.790009  15.400000
2024-01-18  476.489990  14.13  476.489990  14.13  477.059998  14.890000
2024-01-19  482.429993  13.30  482.429993  13.30  482.720001  14.580000
2024-01-22  483.450012  13.19  483.450012  13.19  485.220001  13.840000
2024-01-23  484.859985  12.55  484.859985  12.55  485.109985  13.290000
2024-01-24  485.390015  13.14  485.390015  13.14  488.769989  13.180000
2024-01-25  488.029999  13.45  488.029999  13.45  488.309998  13.580000
2024-01-26  487.410004  13.26  487.410004  13.26  489.119995  14.100000
2024-01-29  491.269989  13.60  491.269989  13.60  491.420013  15.350000
2024-01-30  490.890015  13.31  490.890015  13.31  491.619995  13.740000
2024-01-31  482.880005  14.35  482.880005  14.35  489.079987  14.610000
2024-02-01  489.200012  13.88  489.200012  13.88  489.230011  14.630000
2024-02-02  494.350006  13.85  494.350006  13.85  496.049988  14.230000
2024-02-05  492.549988  13.67  492.549988  13.67  494.380005  14.530000
2024-02-06  493.980011  13.06  493.980011  13.06  494.320007  13.780000
2024-02-07  498.100006  12.83  498.100006  12.83  498.529999  13.130000
2024-02-08  498.320007  12.79  498.320007  12.79  498.709991  13.170000
2024-02-09  501.200012  12.93  501.200012  12.93  501.649994  13.010000
2024-02-12  500.980011  13.93  500.980011  13.93  503.500000  13.940000
2024-02-13  494.079987  15.85  494.079987  15.85  497.089996  17.940001
2024-02-14  498.570007  14.38  498.570007  14.38  499.070007  15.470000
2024-02-15  502.010010  14.01  502.010010  14.01  502.200012  14.640000
2024-02-16  499.510010  14.24  499.510010  14.24  502.869995  14.710000
2024-02-20  496.760010  15.42  496.760010  15.42  498.410004  15.910000
2024-02-21  497.209991  15.34  497.209991  15.34  497.369995  16.120001
2024-02-22  507.500000  14.54  507.500000  14.54  508.489990  14.640000
2024-02-23  507.850006  13.75  507.850006  13.75  510.130005  14.310000
2024-02-26  505.989990  13.74  505.989990  13.74  508.750000  14.200000
2024-02-27  506.929993  13.43  506.929993  13.43  507.160004  13.750000
2024-02-28  506.260010  13.84  506.260010  13.84  506.859985  13.900000
2024-02-29  508.079987  13.40  508.079987  13.40  509.739990  14.150000
2024-03-01  512.849976  13.11  512.849976  13.11  513.289978  13.660000
2024-03-04  512.299988  13.49  512.299988  13.49  514.200012  13.580000
2024-03-05  507.179993  14.46  507.179993  14.46  510.700012  15.100000
2024-03-06  509.750000  14.50  509.750000  14.50  512.070007  14.930000
2024-03-07  514.809998  14.44  514.809998  14.44  515.890015  14.980000
2024-03-08  511.720001  14.74  511.720001  14.74  518.219971  15.530000
2024-03-11  511.279999  15.22  511.279999  15.22  511.880005  16.040001
2024-03-12  516.780029  13.84  516.780029  13.84  517.380005  15.200000
2024-03-13         NaN  13.89         NaN  13.89         NaN  13.950000

                   Low               Open              Volume
                   SPY   ^VIX         SPY   ^VIX          SPY ^VIX
Date
2024-01-02  470.489990  13.10  472.160004  13.22  123623700.0    0
2024-01-03  468.170013  13.33  470.429993  13.35  103585900.0    0
2024-01-04  467.049988  13.64  468.299988  13.93   84232200.0    0
2024-01-05  466.429993  13.29  467.489990  14.24   86060800.0    0
2024-01-08  468.299988  13.02  468.429993  14.00   74879100.0    0
2024-01-09  471.350006  12.74  471.869995  13.20   65931400.0    0
2024-01-10  473.869995  12.67  474.160004  12.86   67310600.0    0
2024-01-11  472.260010  12.35  477.589996  12.64   77940700.0    0
2024-01-12  475.230011  12.47  477.839996  12.66   57944000.0    0
2024-01-16  473.059998  13.52  475.260010  14.12   85014900.0    0
2024-01-17  469.869995  14.38  471.820007  14.59   68843900.0    0
2024-01-18  472.420013  13.89  474.010010  14.85   91856200.0    0
2024-01-19  476.540009  13.28  477.649994  13.80  110733300.0    0
2024-01-22  482.779999  13.17  484.010010  13.77   75844900.0    0
2024-01-23  482.890015  12.53  484.010010  13.20   49945300.0    0
2024-01-24  484.880005  12.41  487.809998  12.66   81765000.0    0
2024-01-25  485.390015  13.06  487.579987  13.18   72525000.0    0
2024-01-26  486.540009  13.20  487.589996  13.73   76641600.0    0
2024-01-29  487.170013  13.59  487.730011  13.98   61322800.0    0
2024-01-30  490.109985  13.23  490.559998  13.69   58618400.0    0
2024-01-31  482.859985  13.18  488.619995  13.42  126011100.0    0
2024-02-01  483.799988  13.87  484.630005  14.21   91891600.0    0
2024-02-02  489.299988  13.39  489.649994  13.95   99147700.0    0
2024-02-05  490.230011  13.58  493.700012  14.37   75757100.0    0
2024-02-06  492.049988  12.98  493.519989  13.57   55918600.0    0
2024-02-07  495.359985  12.81  496.290009  13.06   70556500.0    0
2024-02-08  497.260010  12.74  498.100006  12.95   52343600.0    0
2024-02-09  498.489990  12.69  498.839996  12.79   63979400.0    0
2024-02-12  500.239990  13.34  501.170013  13.48   56502300.0    0
2024-02-13  490.720001  13.43  494.529999  13.96  113099200.0    0
2024-02-14  494.399994  14.22  496.790009  15.38   68387800.0    0
2024-02-15  498.799988  13.94  499.290009  14.27   61683000.0    0
2024-02-16  498.750000  13.75  501.700012  13.94   75461200.0    0
2024-02-20  494.450012  15.07  497.720001  15.09   71736700.0    0
2024-02-21  493.559998  15.22  495.420013  15.54   59603800.0    0
2024-02-22  503.019989  14.12  504.010010  14.28   76402500.0    0
2024-02-23  507.100006  13.64  509.269989  14.31   61321800.0    0
2024-02-26  505.859985  13.66  508.299988  14.17   50386700.0    0
2024-02-27  504.750000  13.41  506.700012  13.63   48854500.0    0
2024-02-28  504.959991  13.44  505.329987  13.52   56506600.0    0
2024-02-29  505.350006  13.30  508.070007  14.14   83924800.0    0
2024-03-01  508.559998  13.08  508.980011  13.34   76805900.0    0
2024-03-04  512.000000  13.32  512.030029  13.49   49799300.0    0
2024-03-05  504.910004  13.75  510.239990  13.75   72855600.0    0
2024-03-06  508.420013  13.89  510.549988  14.27   68382400.0    0
2024-03-07  509.809998  14.25  513.140015  14.98   58652100.0    0
2024-03-08  511.130005  13.97  515.460022  14.22   86425500.0    0
2024-03-11  508.500000  15.13  510.480011  15.51   62557200.0    0
2024-03-12  510.859985  13.81  513.450012  14.97   73031700.0    0
2024-03-13         NaN  13.87         NaN  13.89          NaN    0

# 3. Chien luoc

In [110]:
# Định nghĩa ngưỡng cho VIX
vix_threshold_high = 15  # ví dụ, giá trị này cần được tinh chỉnh
vix_threshold_low = 13   # ví dụ, giá trị này cần được tinh chỉnh

# Xác định tín hiệu mua và bán
# Bởi vì dữ liệu được trả về từ yfinance là MultiIndex DataFrame, chúng ta cần xác định đúng cấu trúc để truy cập dữ liệu

# Điều này giả sử rằng khi VIX cao, đó là tín hiệu bán cho SPY và ngược lại
data['Buy_Signal'] = data[('Close', '^VIX')] < vix_threshold_low
data['Sell_Signal'] = data[('Close', '^VIX')] > vix_threshold_high

data

             Adj Close              Close               High             \
                   SPY   ^VIX         SPY   ^VIX         SPY       ^VIX
Date
2024-01-02  472.649994  13.20  472.649994  13.20  473.670013  14.230000
2024-01-03  468.790009  14.04  468.790009  14.04  471.190002  14.220000
2024-01-04  467.279999  14.13  467.279999  14.13  470.959991  14.200000
2024-01-05  467.920013  13.35  467.920013  13.35  470.440002  14.580000
2024-01-08  474.600006  13.08  474.600006  13.08  474.750000  14.180000
2024-01-09  473.880005  12.76  473.880005  12.76  474.929993  13.450000
2024-01-10  476.559998  12.69  476.559998  12.69  477.450012  12.950000
2024-01-11  476.350006  12.44  476.350006  12.44  478.119995  13.310000
2024-01-12  476.679993  12.70  476.679993  12.70  478.600006  13.080000
2024-01-16  474.929993  13.84  474.929993  13.84  476.609985  14.350000
2024-01-17  472.290009  14.79  472.290009  14.79  472.790009  15.400000
2024-01-18  476.489990  14.13  476.489990  14.13  477.059998  14.890000
2024-01-19  482.429993  13.30  482.429993  13.30  482.720001  14.580000
2024-01-22  483.450012  13.19  483.450012  13.19  485.220001  13.840000
2024-01-23  484.859985  12.55  484.859985  12.55  485.109985  13.290000
2024-01-24  485.390015  13.14  485.390015  13.14  488.769989  13.180000
2024-01-25  488.029999  13.45  488.029999  13.45  488.309998  13.580000
2024-01-26  487.410004  13.26  487.410004  13.26  489.119995  14.100000
2024-01-29  491.269989  13.60  491.269989  13.60  491.420013  15.350000
2024-01-30  490.890015  13.31  490.890015  13.31  491.619995  13.740000
2024-01-31  482.880005  14.35  482.880005  14.35  489.079987  14.610000
2024-02-01  489.200012  13.88  489.200012  13.88  489.230011  14.630000
2024-02-02  494.350006  13.85  494.350006  13.85  496.049988  14.230000
2024-02-05  492.549988  13.67  492.549988  13.67  494.380005  14.530000
2024-02-06  493.980011  13.06  493.980011  13.06  494.320007  13.780000
2024-02-07  498.100006  12.83  498.100006  12.83  498.529999  13.130000
2024-02-08  498.320007  12.79  498.320007  12.79  498.709991  13.170000
2024-02-09  501.200012  12.93  501.200012  12.93  501.649994  13.010000
2024-02-12  500.980011  13.93  500.980011  13.93  503.500000  13.940000
2024-02-13  494.079987  15.85  494.079987  15.85  497.089996  17.940001
2024-02-14  498.570007  14.38  498.570007  14.38  499.070007  15.470000
2024-02-15  502.010010  14.01  502.010010  14.01  502.200012  14.640000
2024-02-16  499.510010  14.24  499.510010  14.24  502.869995  14.710000
2024-02-20  496.760010  15.42  496.760010  15.42  498.410004  15.910000
2024-02-21  497.209991  15.34  497.209991  15.34  497.369995  16.120001
2024-02-22  507.500000  14.54  507.500000  14.54  508.489990  14.640000
2024-02-23  507.850006  13.75  507.850006  13.75  510.130005  14.310000
2024-02-26  505.989990  13.74  505.989990  13.74  508.750000  14.200000
2024-02-27  506.929993  13.43  506.929993  13.43  507.160004  13.750000
2024-02-28  506.260010  13.84  506.260010  13.84  506.859985  13.900000
2024-02-29  508.079987  13.40  508.079987  13.40  509.739990  14.150000
2024-03-01  512.849976  13.11  512.849976  13.11  513.289978  13.660000
2024-03-04  512.299988  13.49  512.299988  13.49  514.200012  13.580000
2024-03-05  507.179993  14.46  507.179993  14.46  510.700012  15.100000
2024-03-06  509.750000  14.50  509.750000  14.50  512.070007  14.930000
2024-03-07  514.809998  14.44  514.809998  14.44  515.890015  14.980000
2024-03-08  511.720001  14.74  511.720001  14.74  518.219971  15.530000
2024-03-11  511.279999  15.22  511.279999  15.22  511.880005  16.040001
2024-03-12  516.780029  13.84  516.780029  13.84  517.380005  15.200000
2024-03-13         NaN  13.89         NaN  13.89         NaN  13.950000

                   Low               Open              Volume      Buy_Signal  \
                   SPY   ^VIX         SPY   ^VIX          SPY ^VIX
Date
2024-01-02  470.489990  13.10  472.160004  13.22  123623700.0    0      False
2024-01-03  468.170013  13.33  470.429993  13.35  103585900.0    0      False
2024-01-04  467.049988  13.64  468.299988  13.93   84232200.0    0      False
2024-01-05  466.429993  13.29  467.489990  14.24   86060800.0    0      False
2024-01-08  468.299988  13.02  468.429993  14.00   74879100.0    0      False
2024-01-09  471.350006  12.74  471.869995  13.20   65931400.0    0       True
2024-01-10  473.869995  12.67  474.160004  12.86   67310600.0    0       True
2024-01-11  472.260010  12.35  477.589996  12.64   77940700.0    0       True
2024-01-12  475.230011  12.47  477.839996  12.66   57944000.0    0       True
2024-01-16  473.059998  13.52  475.260010  14.12   85014900.0    0      False
2024-01-17  469.869995  14.38  471.820007  14.59   68843900.0    0      False
2024-01-18  472.420013  13.89  474.010010  14.85   91856200.0    0      False
2024-01-19  476.540009  13.28  477.649994  13.80  110733300.0    0      False
2024-01-22  482.779999  13.17  484.010010  13.77   75844900.0    0      False
2024-01-23  482.890015  12.53  484.010010  13.20   49945300.0    0       True
2024-01-24  484.880005  12.41  487.809998  12.66   81765000.0    0      False
2024-01-25  485.390015  13.06  487.579987  13.18   72525000.0    0      False
2024-01-26  486.540009  13.20  487.589996  13.73   76641600.0    0      False
2024-01-29  487.170013  13.59  487.730011  13.98   61322800.0    0      False
2024-01-30  490.109985  13.23  490.559998  13.69   58618400.0    0      False
2024-01-31  482.859985  13.18  488.619995  13.42  126011100.0    0      False
2024-02-01  483.799988  13.87  484.630005  14.21   91891600.0    0      False
2024-02-02  489.299988  13.39  489.649994  13.95   99147700.0    0      False
2024-02-05  490.230011  13.58  493.700012  14.37   75757100.0    0      False
2024-02-06  492.049988  12.98  493.519989  13.57   55918600.0    0      False
2024-02-07  495.359985  12.81  496.290009  13.06   70556500.0    0       True
2024-02-08  497.260010  12.74  498.100006  12.95   52343600.0    0       True
2024-02-09  498.489990  12.69  498.839996  12.79   63979400.0    0       True
2024-02-12  500.239990  13.34  501.170013  13.48   56502300.0    0      False
2024-02-13  490.720001  13.43  494.529999  13.96  113099200.0    0      False
2024-02-14  494.399994  14.22  496.790009  15.38   68387800.0    0      False
2024-02-15  498.799988  13.94  499.290009  14.27   61683000.0    0      False
2024-02-16  498.750000  13.75  501.700012  13.94   75461200.0    0      False
2024-02-20  494.450012  15.07  497.720001  15.09   71736700.0    0      False
2024-02-21  493.559998  15.22  495.420013  15.54   59603800.0    0      False
2024-02-22  503.019989  14.12  504.010010  14.28   76402500.0    0      False
2024-02-23  507.100006  13.64  509.269989  14.31   61321800.0    0      False
2024-02-26  505.859985  13.66  508.299988  14.17   50386700.0    0      False
2024-02-27  504.750000  13.41  506.700012  13.63   48854500.0    0      False
2024-02-28  504.959991  13.44  505.329987  13.52   56506600.0    0      False
2024-02-29  505.350006  13.30  508.070007  14.14   83924800.0    0      False
2024-03-01  508.559998  13.08  508.980011  13.34   76805900.0    0      False
2024-03-04  512.000000  13.32  512.030029  13.49   49799300.0    0      False
2024-03-05  504.910004  13.75  510.239990  13.75   72855600.0    0      False
2024-03-06  508.420013  13.89  510.549988  14.27   68382400.0    0      False
2024-03-07  509.809998  14.25  513.140015  14.98   58652100.0    0      False
2024-03-08  511.130005  13.97  515.460022  14.22   86425500.0    0      False
2024-03-11  508.500000  15.13  510.480011  15.51   62557200.0    0      False
2024-03-12  510.859985  13.81  513.450012  14.97   73031700.0    0      False
2024-03-13         NaN  13.87         NaN  13.89          NaN    0      False

           Sell_Signal

Date
2024-01-02       False
2024-01-03       False
2024-01-04       False
2024-01-05       False
2024-01-08       False
2024-01-09       False
2024-01-10       False
2024-01-11       False
2024-01-12       False
2024-01-16       False
2024-01-17       False
2024-01-18       False
2024-01-19       False
2024-01-22       False
2024-01-23       False
2024-01-24       False
2024-01-25       False
2024-01-26       False
2024-01-29       False
2024-01-30       False
2024-01-31       False
2024-02-01       False
2024-02-02       False
2024-02-05       False
2024-02-06       False
2024-02-07       False
2024-02-08       False
2024-02-09       False
2024-02-12       False
2024-02-13        True
2024-02-14       False
2024-02-15       False
2024-02-16       False
2024-02-20        True
2024-02-21        True
2024-02-22       False
2024-02-23       False
2024-02-26       False
2024-02-27       False
2024-02-28       False
2024-02-29       False
2024-03-01       False
2024-03-04       False
2024-03-05       False
2024-03-06       False
2024-03-07       False
2024-03-08       False
2024-03-11        True
2024-03-12       False
2024-03-13       False

# 4. Backtest chien luoc dua vao Data tren

In [111]:
def backtest(data, initial_capital, shares_per_signal): # Chung khoan
        import pandas as pd
        import matplotlib.pyplot as plt
        import plotly.graph_objects as go
        import plotly.express as px

        data['Close'] = data['Close'].ffill()   
        data.dropna(subset=['Close'], inplace=True)
        
        capital = initial_capital
        shares_held = 0

        # Xác định vị thế mua/ bán
        data['Position_Buy'] = data['Buy_Signal'].shift(1)
        data['Position_Sell'] = data['Sell_Signal'].shift(1)

        data['Trade_Action'] = ''
        data['Capital'] = capital
        data['Shares_Held'] = shares_held

        data['Capital'] = data['Capital'].astype(float)
        data['Shares_Held'] = data['Shares_Held'].astype(float)

        # Lặp qua mỗi hàng trong DataFrame
        for index, row in data.iterrows():
            # Nếu có tín hiệu mua và có đủ vốn để mua
            if row['Position_Buy'] == 1 and capital >= row['Close'] * shares_per_signal and row['Trade_Action'] == '':
                # Mua cổ phiếu và cập nhật vốn và số cổ phiếu được giữ
                data.at[index, 'Trade_Action'] = 'Buy'
                capital -= row['Close'] * shares_per_signal
                data.at[index, 'Capital'] = capital
                shares_held += shares_per_signal
                data.at[index, 'Shares_Held'] = shares_held
            elif row['Position_Sell'] == 1 and shares_held > 0 and row['Trade_Action'] == '':
                data.at[index, 'Trade_Action'] = 'Sell'
                capital += row['Close'] * shares_held
                data.at[index, 'Capital'] = capital
                shares_held = 0
                data.at[index, 'Shares_Held'] = shares_held  # Giảm số lượng cổ phiếu 0
            else:
                data.at[index, 'Capital'] = capital
                data.at[index, 'Shares_Held'] = shares_held

            # Cập nhật giá trị hiện tại của vốn dựa trên số cổ phiếu đang giữ và giá đóng cửa hiện tại
            current_value = capital + shares_held * row['Close']

        # Ngày vào lệnh
        first_entry_date = data[data['Position_Buy'] == 1].index.min()
        # Tính lợi nhuận
        profit = current_value - initial_capital
        # Tính lợi nhuận thị trường
        market_return = (data['Close'].iloc[-1] - data['Close'].iloc[0]) / data['Close'].iloc[0]
        # Tính lợi nhuận chiến lược
        strategy_return = (current_value - initial_capital) / initial_capital

        print(f"Ngày vào lệnh đầu tiên: {first_entry_date}")
        print(f'Tổng lợi nhuận: {profit}')
        print(f'Tổng giá trị tài khoản: {current_value}')
        print(f'Lợi nhuận thị trường: {market_return * 100}%')
        print(f'Lợi nhuận chiến lược: {strategy_return * 100}%')

        # Tính toán lợi nhuận thị trường và chiến lược
        data['Market_Return'] = data['Close'].pct_change()
        data['Cumulative_Market_Returns'] = (1 + data['Market_Return']).cumprod()

        # Tính toán lợi nhuận lũy kế từ chiến lược
        data['Strategy_Value'] = data['Capital'] + data['Shares_Held'] * data['Close']
        data['Cumulative_Strategy_Returns'] = data['Strategy_Value'] / initial_capital       

        # Tạo biểu đồ sử dụng Plotly
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=data.index, y=data['Cumulative_Market_Returns'], mode='lines', name='Market Returns'))
        fig.add_trace(go.Scatter(x=data.index, y=data['Cumulative_Strategy_Returns'], mode='lines', name='Strategy Returns'))

        fig.update_layout(
            title='Comparison of Cumulative Returns: Market vs Strategy',
            xaxis_title='Date',
            yaxis_title='Cumulative Returns',
        )
        fig.show()

        return data

# 4. Chay backtest

In [112]:
# Lấy dữ liệu OHLCV cho SPY từ MultiIndex DataFrame
spy_data = data.loc[:, ('Open', 'SPY')].to_frame('Open')

spy_data['High'] = data.loc[:, ('High', 'SPY')]
spy_data['Low'] = data.loc[:, ('Low', 'SPY')]
spy_data['Close'] = data.loc[:, ('Close', 'SPY')]
spy_data['Volume'] = data.loc[:, ('Volume', 'SPY')]

# Đảm bảo các cột tín hiệu không phải là MultiIndex
spy_data['Buy_Signal'] = data['Buy_Signal']
spy_data['Sell_Signal'] = data['Sell_Signal']

resultBacktest = backtest(spy_data, 100000.0, 10)

Ngày vào lệnh đầu tiên: 2024-01-10 00:00:00
Tổng lợi nhuận: 981.500244140625
Tổng giá trị tài khoản: 100981.50024414062
Lợi nhuận thị trường: 9.33672611240012%
Lợi nhuận chiến lược: 0.981500244140625%

In [113]:
resultBacktest

,Open,High,Low,Close,Volume,Buy_Signal,Sell_Signal,Position_Buy,Position_Sell,Trade_Action,Capital,Shares_Held,Market_Return,Cumulative_Market_Returns,Strategy_Value,Cumulative_Strategy_Returns
Date,,,,,,,,,,,,,,,,
2024-01-02,472.160004,473.670013,470.489990,472.649994,123623700.0,False,False,NaN,NaN,,100000.000000,0.0,NaN,NaN,100000.000000,1.000000
2024-01-03,470.429993,471.190002,468.170013,468.790009,103585900.0,False,False,False,False,,100000.000000,0.0,-0.008167,0.991833,100000.000000,1.000000
2024-01-04,468.299988,470.959991,467.049988,467.279999,84232200.0,False,False,False,False,,100000.000000,0.0,-0.003221,0.988639,100000.000000,1.000000
2024-01-05,467.489990,470.440002,466.429993,467.920013,86060800.0,False,False,False,False,,100000.000000,0.0,0.001370,0.989993,100000.000000,1.000000
2024-01-08,468.429993,474.750000,468.299988,474.600006,74879100.0,False,False,False,False,,100000.000000,0.0,0.014276,1.004126,100000.000000,1.000000
2024-01-09,471.869995,474.929993,471.350006,473.880005,65931400.0,True,False,False,False,,100000.000000,0.0,-0.001517,1.002602,100000.000000,1.000000
2024-01-10,474.160004,477.450012,473.869995,476.559998,67310600.0,True,False,True,False,Buy,95234.400024,10.0,0.005655,1.008273,100000.000000,1.000000
2024-01-11,477.589996,478.119995,472.260010,476.350006,77940700.0,True,False,True,False,Buy,90470.899963,20.0,-0.000441,1.007828,99997.900085,0.999979
2024-01-12,477.839996,478.600006,475.230011,476.679993,57944000.0,True,False,True,False,Buy,85704.100037,30.0,0.000693,1.008526,100004.499817,1.000045
2024-01-16,475.260010,476.609985,473.059998,474.929993,85014900.0,False,False,True,False,Buy,80954.800110,40.0,-0.003671,1.004824,99951.999817,0.999520
2024-01-17,471.820007,472.790009,469.869995,472.290009,68843900.0,False,False,False,False,,80954.800110,40.0,-0.005559,0.999238,99846.400452,0.998464
2024-01-18,474.010010,477.059998,472.420013,476.489990,91856200.0,False,False,False,False,,80954.800110,40.0,0.008893,1.008124,100014.399719,1.000144
2024-01-19,477.649994,482.720001,476.540009,482.429993,110733300.0,False,False,False,False,,80954.800110,40.0,0.012466,1.020692,100251.999817,1.002520
2024-01-22,484.010010,485.220001,482.779999,483.450012,75844900.0,False,False,False,False,,80954.800110,40.0,0.002114,1.022850,100292.800598,1.002928
2024-01-23,484.010010,485.109985,482.890015,484.859985,49945300.0,True,False,False,False,,80954.800110,40.0,0.002916,1.025833,100349.199524,1.003492
2024-01-24,487.809998,488.769989,484.880005,485.390015,81765000.0,False,False,True,False,Buy,76100.899963,50.0,0.001093,1.026954,100370.400696,1.003704
2024-01-25,487.579987,488.309998,485.390015,488.029999,72525000.0,False,False,False,False,,76100.899963,50.0,0.005439,1.032540,100502.399902,1.005024
2024-01-26,487.589996,489.119995,486.540009,487.410004,76641600.0,False,False,False,False,,76100.899963,50.0,-0.001270,1.031228,100471.400146,1.004714
2024-01-29,487.730011,491.420013,487.170013,491.269989,61322800.0,False,False,False,False,,76100.899963,50.0,0.007919,1.039395,100664.399414,1.006644
2024-01-30,490.559998,491.619995,490.109985,490.890015,58618400.0,False,False,False,False,,76100.899963,50.0,-0.000773,1.038591,100645.400696,1.006454
2024-01-31,488.619995,489.079987,482.859985,482.880005,126011100.0,False,False,False,False,,76100.899963,50.0,-0.016317,1.021644,100244.900208,1.002449
2024-02-01,484.630005,489.230011,483.799988,489.200012,91891600.0,False,False,False,False,,76100.899963,50.0,0.013088,1.035015,100560.900574,1.005609
2024-02-02,489.649994,496.049988,489.299988,494.350006,99147700.0,False,False,False,False,,76100.899963,50.0,0.010527,1.045911,100818.400269,1.008184
2024-02-05,493.700012,494.380005,490.230011,492.549988,75757100.0,False,False,False,False,,76100.899963,50.0,-0.003641,1.042103,100728.399353,1.007284
2024-02-06,493.519989,494.320007,492.049988,493.980011,55918600.0,False,False,False,False,,76100.899963,50.0,0.002903,1.045129,100799.900513,1.007999
2024-02-07,496.290009,498.529999,495.359985,498.100006,70556500.0,True,False,False,False,,76100.899963,50.0,0.008340,1.053845,101005.900269,1.010059
2024-02-08,498.100006,498.709991,497.260010,498.320007,52343600.0,True,False,True,False,Buy,71117.699890,60.0,0.000442,1.054311,101016.900330,1.010169
2024-02-09,498.839996,501.649994,498.489990,501.200012,63979400.0,True,False,True,False,Buy,66105.699768,70.0,0.005779,1.060404,101189.700623,1.011897
2024-02-12,501.170013,503.500000,500.239990,500.980011,56502300.0,False,False,True,False,Buy,61095.899658,80.0,-0.000439,1.059939,101174.300537,1.011743
2024-02-13,494.529999,497.089996,490.720001,494.079987,113099200.0,False,True,False,False,,61095.899658,80.0,-0.013773,1.045340,100622.298584,1.006223
2024-02-14,496.790009,499.070007,494.399994,498.570007,68387800.0,False,False,False,True,Sell,100981.500244,0.0,0.009088,1.054840,100981.500244,1.009815
2024-02-15,499.290009,502.200012,498.799988,502.010010,61683000.0,False,False,False,False,,100981.500244,0.0,0.006900,1.062118,100981.500244,1.009815
2024-02-16,501.700012,502.869995,498.750000,499.510010,75461200.0,False,False,False,False,,100981.500244,0.0,-0.004980,1.056829,100981.500244,1.009815
2024-02-20,497.720001,498.410004,494.450012,496.760010,71736700.0,False,True,False,False,,100981.500244,0.0,-0.005505,1.051010,100981.500244,1.009815
2024-02-21,495.420013,497.369995,493.559998,497.209991,59603800.0,False,True,False,True,,100981.500244,0.0,0.000906,1.051962,100981.500244,1.009815
2024-02-22,504.010010,508.489990,503.019989,507.500000,76402500.0,False,False,False,True,,100981.500244,0.0,0.020695,1.073733,100981.500244,1.009815
2024-02-23,509.269989,510.130005,507.100006,507.850006,61321800.0,False,False,False,False,,100981.500244,0.0,0.000690,1.074474,100981.500244,1.009815
2024-02-26,508.299988,508.750000,505.859985,505.989990,50386700.0,False,False,False,False,,100981.500244,0.0,-0.003663,1.070538,100981.500244,1.009815
2024-02-27,506.700012,507.160004,504.750000,506.929993,48854500.0,False,False,False,False,,100981.500244,0.0,0.001858,1.072527,100981.500244,1.009815
2024-02-28,505.329987,506.859985,504.959991,506.260010,56506600.0,False,False,False,False,,100981.500244,0.0,-0.001322,1.071110,100981.500244,1.009815
2024-02-29,508.070007,509.739990,505.350006,508.079987,83924800.0,False,False,False,False,,100981.500244,0.0,0.003595,1.074960,100981.500244,1.009815
2024-03-01,508.980011,513.289978,508.559998,512.849976,76805900.0,False,False,False,False,,100981.500244,0.0,0.009388,1.085052,100981.500244,1.009815
2024-03-04,512.030029,514.200012,512.000000,512.299988,49799300.0,False,False,False,False,,100981.500244,0.0,-0.001072,1.083889,100981.500244,1.009815
2024-03-05,510.239990,510.700012,504.910004,507.179993,72855600.0,False,False,False,False,,100981.500244,0.0,-0.009994,1.073056,100981.500244,1.009815
2024-03-06,510.549988,512.070007,508.420013,509.750000,68382400.0,False,False,False,False,,100981.500244,0.0,0.005067,1.078494,100981.500244,1.009815
2024-03-07,513.140015,515.890015,509.809998,514.809998,58652100.0,False,False,False,False,,100981.500244,0.0,0.009926,1.089199,100981.500244,1.009815
2024-03-08,515.460022,518.219971,511.130005,511.720001,86425500.0,False,False,False,False,,100981.500244,0.0,-0.006002,1.082662,100981.500244,1.009815
2024-03-11,510.480011,511.880005,508.500000,511.279999,62557200.0,False,True,False,False,,100981.500244,0.0,-0.000860,1.081731,100981.500244,1.009815
2024-03-12,513.450012,517.380005,510.859985,516.780029,73031700.0,False,False,False,True,,100981.500244,0.0,0.010757,1.093367,100981.500244,1.009815
2024-03-13,NaN,NaN,NaN,516.780029,NaN,False,False,False,False,,100981.500244,0.0,0.000000,1.093367,100981.500244,1.009815