### Xác định tín hiệu mua: Mot tin hieu mua xay ra khi MA Fast > MA Slow va ATR < 1 nguong
### Xác định tín hiệu bán: Mot tin hieu ban xay ra khi MA Fast < MA Slow va ATR > 1 nguong

# Load du lieu len

In [ ]:
import pandas as pd
import ccxt
from datetime import datetime, timedelta

# Khởi tạo kết nối đến sàn Binance
exchange = ccxt.binance() # Khong can API Key, Secret Key

### Step 0: Cac tham so ##########################################################
symbol = 'ETHUSDT'
from_date = (datetime.now() - timedelta(days=0)).strftime('%Y-%m-%d')  # Lấy ngày hôm qua
to_date = (datetime.now() + timedelta(days=0)).strftime('%Y-%m-%d')
timeframe = '1m' # 1m
# Định dạng ngày tháng
since = exchange.parse8601(from_date + 'T00:00:00Z')
end = exchange.parse8601(to_date + 'T00:00:00Z')

### Step 1: Lay du lieu ##########################################################
# Lấy dữ liệu thị trường từ sàn Binance
# 1d
ohlcv = exchange.fetch_ohlcv(symbol, timeframe=timeframe, since=since, limit=1000)

# Chuyển dữ liệu thành DataFrame
data = pd.DataFrame(ohlcv, columns=['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume'])

# Chuyen kieu du lieu thanh datetime
data['Timestamp'] = pd.to_datetime(data['Timestamp'], unit='ms')  # Chieu dai cua data['Timestamp'] la 12

# Doi ten cot
data = data.rename(columns={'Timestamp': 'Datetime'})

data

               Datetime     Open     High      Low    Close    Volume
0   2025-07-31 00:00:00  3810.00  3810.00  3806.10  3807.70  595.6921
1   2025-07-31 00:01:00  3807.70  3807.71  3805.67  3807.70  281.1117
2   2025-07-31 00:02:00  3807.70  3807.73  3803.46  3803.67  533.0524
3   2025-07-31 00:03:00  3803.67  3804.91  3802.80  3803.45  263.3193
4   2025-07-31 00:04:00  3803.45  3804.19  3802.45  3803.90  224.4108
..                  ...      ...      ...      ...      ...       ...
920 2025-07-31 15:20:00  3783.87  3785.91  3783.30  3785.91  500.5173
921 2025-07-31 15:21:00  3785.90  3785.90  3780.21  3782.01  345.3445
922 2025-07-31 15:22:00  3782.01  3783.32  3779.19  3783.31  261.1914
923 2025-07-31 15:23:00  3783.31  3784.52  3779.72  3779.73  261.4875
924 2025-07-31 15:24:00  3779.72  3780.30  3779.72  3780.29   14.9960

[925 rows x 6 columns]

# Viet lai thanh ham

In [3]:
def loaddataBinance_FromTo(symbol, from_date, to_date, timeframe):
	import pandas as pd
	import ccxt
	from datetime import datetime, timedelta

	# Khởi tạo kết nối đến sàn Binance
	exchange = ccxt.binance()

	# Định dạng ngày tháng
	since = exchange.parse8601(from_date + 'T00:00:00Z')
	end = exchange.parse8601(to_date + 'T00:00:00Z')

	# Lấy dữ liệu thị trường từ sàn Binance
	# 1d
	ohlcv = exchange.fetch_ohlcv(symbol, timeframe=timeframe, since=since, limit=1000)

	# Chuyển dữ liệu thành DataFrame
	data = pd.DataFrame(ohlcv, columns=['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume'])
	data['Timestamp'] = pd.to_datetime(data['Timestamp'], unit='ms')         
	data = data.rename(columns={'Timestamp': 'Datetime'})

	return data

# Goi ham

In [4]:
# ##############################################Step 0: Các tham số để lấy dữ liệu###############################
symbol = 'ETHUSDT'
from_date = (datetime.now() - timedelta(days=0)).strftime('%Y-%m-%d')  # Lấy ngày hôm qua
to_date = (datetime.now() + timedelta(days=0)).strftime('%Y-%m-%d')
timeframe = '1m' # 1m

# ##############################################Step 1: Lấy dữ liệu##############################################
data = loaddataBinance_FromTo(symbol, from_date, to_date, timeframe)
data

               Datetime     Open     High      Low    Close    Volume
0   2025-07-31 00:00:00  3810.00  3810.00  3806.10  3807.70  595.6921
1   2025-07-31 00:01:00  3807.70  3807.71  3805.67  3807.70  281.1117
2   2025-07-31 00:02:00  3807.70  3807.73  3803.46  3803.67  533.0524
3   2025-07-31 00:03:00  3803.67  3804.91  3802.80  3803.45  263.3193
4   2025-07-31 00:04:00  3803.45  3804.19  3802.45  3803.90  224.4108
..                  ...      ...      ...      ...      ...       ...
920 2025-07-31 15:20:00  3783.87  3785.91  3783.30  3785.91  500.5173
921 2025-07-31 15:21:00  3785.90  3785.90  3780.21  3782.01  345.3445
922 2025-07-31 15:22:00  3782.01  3783.32  3779.19  3783.31  261.1914
923 2025-07-31 15:23:00  3783.31  3784.52  3779.72  3779.73  261.4875
924 2025-07-31 15:24:00  3779.72  3786.62  3779.72  3783.08  165.4817

[925 rows x 6 columns]

In [ ]:
# import sys
# sys.path.append('../Common')
# import CommonBinance
# from datetime import datetime, timedelta

# # ##############################################Step 0: Các tham số để lấy dữ liệu###############################
# symbol = 'ETHUSDT'
# from_date = (datetime.now() - timedelta(days=0)).strftime('%Y-%m-%d')  # Lấy ngày hôm qua
# print(from_date)
# to_date = (datetime.now() + timedelta(days=0)).strftime('%Y-%m-%d')
# timeframe = '1m' # 1m

# # ##############################################Step 1: Lấy dữ liệu##############################################
# # data = CommonBinance.CommonBinance.loaddataBinance_FromTo(symbol, from_date, to_date, timeframe)
# data = loaddataBinance_FromTo(symbol, from_date, to_date, timeframe)

In [5]:
data

               Datetime     Open     High      Low    Close    Volume
0   2025-07-31 00:00:00  3810.00  3810.00  3806.10  3807.70  595.6921
1   2025-07-31 00:01:00  3807.70  3807.71  3805.67  3807.70  281.1117
2   2025-07-31 00:02:00  3807.70  3807.73  3803.46  3803.67  533.0524
3   2025-07-31 00:03:00  3803.67  3804.91  3802.80  3803.45  263.3193
4   2025-07-31 00:04:00  3803.45  3804.19  3802.45  3803.90  224.4108
..                  ...      ...      ...      ...      ...       ...
920 2025-07-31 15:20:00  3783.87  3785.91  3783.30  3785.91  500.5173
921 2025-07-31 15:21:00  3785.90  3785.90  3780.21  3782.01  345.3445
922 2025-07-31 15:22:00  3782.01  3783.32  3779.19  3783.31  261.1914
923 2025-07-31 15:23:00  3783.31  3784.52  3779.72  3779.73  261.4875
924 2025-07-31 15:24:00  3779.72  3786.62  3779.72  3783.08  165.4817

[925 rows x 6 columns]

In [ ]:
# import sys
# sys.path.append('../Common')
# import CommonBinance
# # CommonBinance.CommonBinance.HelloWorld()

# Chien luoc

In [6]:
import pandas as pd
import plotly.graph_objects as go
import redis
import numpy as np
from datetime import datetime, timedelta

# ##############################################Step 0: Các tham số để lấy dữ liệu###############################
symbol = 'ETHUSDT'
from_date = (datetime.now() - timedelta(days=0)).strftime('%Y-%m-%d')  # Lấy ngày hôm qua
to_date = (datetime.now() + timedelta(days=0)).strftime('%Y-%m-%d')
timeframe = '1m' # 1m

# ##############################################Step 1: Lấy dữ liệu##############################################
data = loaddataBinance_FromTo(symbol, from_date, to_date, timeframe)
# print(data)

# ##############################################Step 2: Chiến lược##############################################  
# Đặt thời gian cho MA và ATR
ma_fast_period = 50 # Thời gian MA nhanh trung binh 50 chu ky
ma_slow_period = 200 # Thời gian MA chậm trung bình 200 chu ky
atr_period = 14
atr_threshold = 40 # Xác định ngưỡng biến động thị trường

import talib # Import vao de su dung
# MA7 > 20 and Close > MA7 => Buy
# Nguoc lai => Sell

data['RSI'] = talib.RSI(data['Close'], timeperiod=14)
data['MA14_RSI'] = talib.SMA(data['RSI'], timeperiod=14) # MA cua RSI

# Tính toán MA nhanh và MA chậm bằng TA-Lib
data['MA_Fast'] = talib.SMA(data['Close'], timeperiod=ma_fast_period) # 50
data['MA_Slow'] = talib.SMA(data['Close'], timeperiod=ma_slow_period) # 200

# Sử dụng TA-Lib để tính ATR, trong đó True Range (TR) được tính toán tự động
data['ATR'] = talib.ATR(data['High'], data['Low'], data['Close'], timeperiod=atr_period)

# ##############################################Step 3: Tín hiệu mua bán##############################################
# Xác định tín hiệu mua
data['Buy_Signal'] = (data['MA_Fast'] >= data['MA_Slow']) & (data['ATR'] <= atr_threshold)
# Xác định tín hiệu bán
data['Sell_Signal'] = (data['MA_Fast'] < data['MA_Slow']) & (data['ATR'] > atr_threshold)

data

,Datetime,Open,High,Low,Close,Volume,RSI,MA14_RSI,MA_Fast,MA_Slow,ATR,Buy_Signal,Sell_Signal
0,2025-07-31 00:00:00,3810.00,3810.00,3806.10,3807.70,595.6921,NaN,NaN,NaN,NaN,NaN,False,False
1,2025-07-31 00:01:00,3807.70,3807.71,3805.67,3807.70,281.1117,NaN,NaN,NaN,NaN,NaN,False,False
2,2025-07-31 00:02:00,3807.70,3807.73,3803.46,3803.67,533.0524,NaN,NaN,NaN,NaN,NaN,False,False
3,2025-07-31 00:03:00,3803.67,3804.91,3802.80,3803.45,263.3193,NaN,NaN,NaN,NaN,NaN,False,False
4,2025-07-31 00:04:00,3803.45,3804.19,3802.45,3803.90,224.4108,NaN,NaN,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
934,2025-07-31 15:34:00,3796.01,3796.01,3788.50,3792.24,538.2635,60.521928,58.597611,3778.9630,3801.34790,4.723741,False,False
935,2025-07-31 15:35:00,3792.24,3792.99,3789.84,3790.55,348.4650,57.789290,58.816778,3779.3970,3801.09310,4.611331,False,False
936,2025-07-31 15:36:00,3790.56,3793.33,3790.56,3792.01,405.1155,59.490948,59.061367,3779.8174,3800.86225,4.480522,False,False
937,2025-07-31 15:37:00,3792.00,3795.78,3792.00,3795.77,222.6629,63.564674,59.921335,3780.2150,3800.67695,4.430485,False,False
938,2025-07-31 15:38:00,3795.78,3796.99,3794.71,3795.86,165.8717,63.658880,60.526000,3780.4922,3800.49835,4.276879,False,False

In [10]:
import talib # Import vao de su dung
# MA7 > 20 and Close > MA7 => Buy
# Nguoc lai => Sell

data['MA7'] = talib.SMA(data['Close'], timeperiod=7)
data['MA20'] = talib.SMA(data['Close'], timeperiod=20)
data['Buy_Signal1'] = (data['MA7'] > data['MA20']) & (data['Close'] > data['MA7'])
data['Sell_Signal1'] = (data['MA7'] < data['MA20']) & (data['Close'] < data['MA7'])

data

,Datetime,Open,High,Low,Close,Volume,MA_Fast,MA_Slow,ATR,Buy_Signal,Sell_Signal,MA7,MA20,Buy_Signal1,Sell_Signal1
0,2025-06-13 00:00:00,2642.66,2645.45,2640.50,2642.03,1667.2239,NaN,NaN,NaN,False,False,NaN,NaN,False,False
1,2025-06-13 00:01:00,2642.03,2642.03,2625.00,2626.01,3402.4512,NaN,NaN,NaN,False,False,NaN,NaN,False,False
2,2025-06-13 00:02:00,2626.04,2630.80,2611.39,2618.19,5478.1297,NaN,NaN,NaN,False,False,NaN,NaN,False,False
3,2025-06-13 00:03:00,2618.18,2618.18,2602.99,2607.41,4523.1412,NaN,NaN,NaN,False,False,NaN,NaN,False,False
4,2025-06-13 00:04:00,2607.41,2619.19,2601.60,2611.47,2681.8008,NaN,NaN,NaN,False,False,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
898,2025-06-13 14:58:00,2536.00,2538.22,2535.91,2537.64,502.0443,2523.2636,2540.38140,3.742119,False,False,2534.110000,2528.9400,True,False
899,2025-06-13 14:59:00,2537.65,2540.16,2537.65,2538.06,475.5906,2523.3752,2540.42870,3.654825,False,False,2535.557143,2529.6000,True,False
900,2025-06-13 15:00:00,2538.06,2540.00,2536.20,2539.42,1084.8723,2523.6634,2540.47425,3.665195,False,False,2536.918571,2530.3655,True,False
901,2025-06-13 15:01:00,2539.41,2540.00,2536.14,2538.40,737.7815,2523.9092,2540.51495,3.679109,False,False,2537.531429,2531.2080,True,False
902,2025-06-13 15:02:00,2538.41,2539.21,2538.41,2539.15,9.4552,2524.1802,2540.55505,3.474173,False,False,2537.810000,2531.6245,True,False

In [ ]:
data.to_csv('Buoi5.1_Chienluoc MA, ATR.csv')

In [ ]:
import plotly.graph_objects as go
import plotly.subplots as sp  # Sử dụng plotly.subplots để tạo nhiều biểu đồ
import pandas as pd 

# Trực quan hóa dữ liệu (tùy chọn)
fig = go.Figure()

# Tạo subplot với 2 hàng
fig = sp.make_subplots(rows=2, cols=1, shared_xaxes=True, 
                       subplot_titles=('Price and Moving Averages', 'Average True Range (ATR)'))

# Thêm đường giá đóng cửa
fig.add_trace(go.Scatter(x=data['Datetime'], y=data['Close'], mode='lines', name='Close Price'), row=1, col=1)

# Thêm đường MA_Fast và MA_Slow vào biểu đồ hàng đầu tiên
fig.add_trace(go.Scatter(x=data['Datetime'], y=data['MA_Fast'], mode='lines', name='MA Fast'), row=1, col=1)
fig.add_trace(go.Scatter(x=data['Datetime'], y=data['MA_Slow'], mode='lines', name='MA Slow'), row=1, col=1)

# Đánh dấu các tín hiệu mua và bán
fig.add_trace(go.Scatter(x=data[data['Buy_Signal'] == 1]['Datetime'], 
                         y=data[data['Buy_Signal'] == 1]['Close'], 
                         mode='markers', name='Buy Signal', marker=dict(color='green', size=10, symbol='triangle-up')), row=1, col=1)
fig.add_trace(go.Scatter(x=data[data['Sell_Signal'] == 1]['Datetime'], 
                         y=data[data['Sell_Signal'] == 1]['Close'], 
                         mode='markers', name='Sell Signal', marker=dict(color='red', size=10, symbol='triangle-down')), row=1, col=1)

# Thêm đường ATR vào biểu đồ hàng thứ hai
fig.add_trace(go.Scatter(x=data['Datetime'], y=data['ATR'], mode='lines', name='ATR'), row=2, col=1)

# Cấu hình và hiển thị biểu đồ
fig.update_layout(title='Moving Average Crossover and ATR Signals: ' + symbol , xaxis_title='Date', yaxis_title='Price', 
    height=800  # Tăng kích thước cao của biểu đồ lên 800
)

fig.update_xaxes(title_text='Date', row=2, col=1)
fig.update_yaxes(title_text='ATR', row=2, col=1)
fig.show()

: