Một cơ hội mua có thể xuất hiện khi giá cổ phiếu chạm vào hoặc tiệm cận Lower Bollinger Band, đồng thời RSI ở dưới 30.

Một cơ hội bán tốt có thể xuất hiện khi giá chạm vào hoặc tiệm cận Upper Bollinger Band đồng thời RSI ở trên 70.

# EMA 50 >  EMA200 : Buy
# EMA 50 < EMA200 : SELL

 # SMA 6 - SMA 10 : MA6 > MA10 : Buy
 # MA6 < MA10 : SELL

# Load data

In [1]:
from ssi_fc_data import fc_md_client, model
from datetime import datetime
import pandas as pd
import json
import configDataSSI

client = fc_md_client.MarketDataClient(configDataSSI)

# Tạo Market Data Client
symbol = 'VCB'
from_date = "01/07/2025"
to_date = "29/07/2025"

req = model.daily_ohlc(symbol, from_date, to_date)
data_dict = client.daily_ohlc(configDataSSI, req)
#  print(type(data_dict))
data_list = data_dict['data']
data = pd.DataFrame(data_list)
data = data.rename(columns={'TradingDate': 'Datetime'})       
data = pd.DataFrame(data, columns=['Datetime', 'Open', 'High', 'Low', 'Close', 'Volume'])

data

      Datetime   Open   High    Low  Close    Volume
0   01/07/2025  56788  58377  56689  57781  10049500
1   02/07/2025  57880  58178  57285  57582   2913600
2   03/07/2025  57682  58377  57285  57483   7395300
3   04/07/2025  57483  58377  57384  57980   4849800
4   07/07/2025  58079  58476  57781  58178   8056200
5   08/07/2025  58377  59072  58178  58575  10394500
6   09/07/2025  58972  61355  58972  61057  16449700
7   10/07/2025  61355  61355  60561  60958   8152900
8   11/07/2025  61057  62646  61057  62249  12701900
9   14/07/2025  62447  62447  60561  61951   6475000
10  15/07/2025  61951  62149  60958  60958   6315400
11  16/07/2025  60958  61653  60660  61355   7603200
12  17/07/2025  61355  62249  61355  61752   9992700
13  18/07/2025  61851  62149  61355  61454   6915300
14  21/07/2025  61752  62249  60859  60859   6138200
15  22/07/2025  60859  61752  60462  61752   4902600
16  23/07/2025  62050  62149  61355  61653   5087300
17  24/07/2025  61752  63043  61454  61653   8710200
18  25/07/2025  61653  62050  61454  61554   4978400
19  28/07/2025  61752  62546  61653  62348  10484700
20  29/07/2025  62745  62745  60561  60561  10595600

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Datetime  21 non-null     object
 1   Open      21 non-null     object
 2   High      21 non-null     object
 3   Low       21 non-null     object
 4   Close     21 non-null     object
 5   Volume    21 non-null     object
dtypes: object(6)
memory usage: 1.1+ KB

# Viet ham

In [3]:
def loaddataSSI(symbol, from_date, to_date): # 'VCB', '27/10/2023', '27/10/2023'

	# Import các module cần thiết
	 from ssi_fc_data import fc_md_client, model
	 from datetime import datetime
	 import pandas as pd
	 import json
	 import configDataSSI

	 # Tạo Market Data Client
	 # from_date = "01/11/2023"
	 # to_date = "17/11/2023"

	 # Sử dụng datetime để phân tích chuỗi ngày tháng
	 from_date_new = datetime.strptime(from_date, '%Y-%m-%d')
	 to_date_new = datetime.strptime(to_date, '%Y-%m-%d')

	 # Định dạng lại ngày tháng sang định dạng 'dd/mm/yyyy'
	 from_date_new = from_date_new.strftime('%d/%m/%Y')
	 to_date_new = to_date_new.strftime('%d/%m/%Y')

	 client = fc_md_client.MarketDataClient(configDataSSI)

	 req = model.daily_ohlc(symbol, from_date_new, to_date_new)

	 data_dict = client.daily_ohlc(configDataSSI, req)
	#  print(type(data_dict))

	 data_list = data_dict['data']

	 data = pd.DataFrame(data_list)

	 data = data.rename(columns={'TradingDate': 'Datetime'})       

	 data = pd.DataFrame(data, columns=['Datetime', 'Open', 'High', 'Low', 'Close', 'Volume'])

	 return data

In [4]:
import pandas as pd
import plotly.graph_objects as go
import redis
import numpy as np
from datetime import datetime, timedelta

# ##############################################Step 0: Các tham số để lấy dữ liệu###############################
symbol = 'VCB'
from_date = (datetime.now() - timedelta(days=20)).strftime('%Y-%m-%d')
to_date = (datetime.now() + timedelta(days=0)).strftime('%Y-%m-%d')

# ##############################################Step 1: Lấy dữ liệu##############################################
data = loaddataSSI(symbol, from_date, to_date)

data

      Datetime   Open   High    Low  Close   Volume
0   03/11/2025  60000  60300  59300  59300  2800100
1   04/11/2025  59200  60400  59100  60100  2952400
2   05/11/2025  60000  61100  59900  60800  4601700
3   06/11/2025  60900  61300  60200  60300  2821200
4   07/11/2025  60000  60000  59000  59300  3586300
5   10/11/2025  59400  59700  58800  58800  2316500
6   11/11/2025  59100  59600  58800  58900  2540900
7   12/11/2025  59100  59700  59000  59500  2012700
8   13/11/2025  59500  60000  59200  59800  2113500
9   14/11/2025  59800  60400  59400  60000  2069600
10  17/11/2025  60000  60400  59900  60200  1585600
11  18/11/2025  60400  60400  59800  59900  2158800
12  19/11/2025  59900  60100  59300  59400  2896200
13  20/11/2025  59600  59700  59200  59400  2259400
14  21/11/2025  59100  59200  58700  59000  3452400

In [ ]:
# data.info()

# Rap tu tu

In [5]:
import pandas as pd
import plotly.graph_objects as go
import redis
import numpy as np
from datetime import datetime, timedelta
import talib 

# ##############################################Step 0: Các tham số để lấy dữ liệu###############################
symbol = 'VCB'
from_date = (datetime.now() - timedelta(days=20)).strftime('%Y-%m-%d')
to_date = (datetime.now() + timedelta(days=0)).strftime('%Y-%m-%d')

# ##############################################Step 1: Lấy dữ liệu##############################################
# Lay tu ham o tren / thay vi viet luong tuong
data = loaddataSSI(symbol, from_date, to_date)
# Thiết lập 'Datetime' làm chỉ mục của DataFrame
data.set_index('Datetime', inplace=True)
data['Close'] = pd.to_numeric(data['Close'])

# ##############################################Step 2: Chiến lược##############################################  
# Tính toán SMA và độ lệch chuẩn cho giá đóng cửa bằng TA-Lib
window1 = 6
window2 = 10
data['SMA6'] = talib.SMA(data['Close'], timeperiod=window1)
data['SMA10'] = talib.SMA(data['Close'], timeperiod=window2)

# # Tính toán Bollinger Bands bằng TA-Lib
# window = 20
# data['Upper_Band'], data['Middle_Band'], data['Lower_Band'] = talib.BBANDS(data['Close'], timeperiod=window, nbdevup=2, nbdevdn=2, matype=0)

# # Thiết lập cửa sổ thời gian và tính RSI bằng TA-Lib
# windowRSI = 14
# data['RSI'] = talib.RSI(data['Close'], timeperiod=windowRSI)

# Tạo cột tín hiệu mua và bán
# data['Buy_Signal'] = ((data['Close'] <= data['Lower_Band']) & (data['RSI'] < 30))
# data['Sell_Signal'] = ((data['Close'] >= data['Upper_Band']) & (data['RSI'] > 70))

# Buy khi SMA6 > SMA10, sell khi SMA6 < SMA10
data['Buy_Signal'] = (data['SMA6'] >= data['SMA10'])
data['Sell_Signal'] = (data['SMA6'] <= data['SMA10'])
print(data)

# ##############################################Step 3: Ve bieu do##############################################  
# Ve bieu do
# Tạo cột giá cho tín hiệu mua/bán (sử dụng giá Close thực tế)
data['Buy_Price'] = np.where(data['Buy_Signal'], data['Close'], np.nan)
data['Sell_Price'] = np.where(data['Sell_Signal'], data['Close'], np.nan)

print(data)
# ##############################################Step 3: Ve bieu do##############################################  
# Ve bieu do
fig = go.Figure()
fig.add_trace(go.Scatter(x=data.index, y=data['Close'], mode='lines', name='Close'))
fig.add_trace(go.Scatter(x=data.index, y=data['SMA6'], mode='lines', name='SMA6'))
fig.add_trace(go.Scatter(x=data.index, y=data['SMA10'], mode='lines', name='SMA10'))
fig.add_trace(go.Scatter(x=data.index, y=data['Buy_Price'], mode='markers', name='Buy Signal', marker=dict(symbol='triangle-up', size=10, color='green')))
fig.add_trace(go.Scatter(x=data.index, y=data['Sell_Price'], mode='markers', name='Sell Signal', marker=dict(symbol='triangle-down', size=10, color='red')))
fig.show()

             Open   High    Low  Close   Volume          SMA6    SMA10  \
Datetime
03/11/2025  60000  60300  59300  59300  2800100           NaN      NaN
04/11/2025  59200  60400  59100  60100  2952400           NaN      NaN
05/11/2025  60000  61100  59900  60800  4601700           NaN      NaN
06/11/2025  60900  61300  60200  60300  2821200           NaN      NaN
07/11/2025  60000  60000  59000  59300  3586300           NaN      NaN
10/11/2025  59400  59700  58800  58800  2316500  59766.666667      NaN
11/11/2025  59100  59600  58800  58900  2540900  59700.000000      NaN
12/11/2025  59100  59700  59000  59500  2012700  59600.000000      NaN
13/11/2025  59500  60000  59200  59800  2113500  59433.333333      NaN
14/11/2025  59800  60400  59400  60000  2069600  59383.333333  59680.0
17/11/2025  60000  60400  59900  60200  1585600  59533.333333  59770.0
18/11/2025  60400  60400  59800  59900  2158800  59716.666667  59750.0
19/11/2025  59900  60100  59300  59400  2896200  59800.000000  59610.0
20/11/2025  59600  59700  59200  59400  2259400  59783.333333  59520.0
21/11/2025  59100  59200  58700  59000  3452400  59650.000000  59490.0

            Buy_Signal  Sell_Signal
Datetime
03/11/2025       False        False
04/11/2025       False        False
05/11/2025       False        False
06/11/2025       False        False
07/11/2025       False        False
10/11/2025       False        False
11/11/2025       False        False
12/11/2025       False        False
13/11/2025       False        False
14/11/2025       False         True
17/11/2025       False         True
18/11/2025       False         True
19/11/2025        True        False
20/11/2025        True        False
21/11/2025        True        False
             Open   High    Low  Close   Volume          SMA6    SMA10  \
Datetime
03/11/2025  60000  60300  59300  59300  2800100           NaN      NaN
04/11/2025  59200  60400  59100  60100  2952400           NaN      NaN
05/11/2025  60000  61100  59900  60800  4601700           NaN      NaN
06/11/2025  60900  61300  60200  60300  2821200           NaN      NaN
07/11/2025  60000  60000  59000  59300  3586300           NaN      NaN
10/11/2025  59400  59700  58800  58800  2316500  59766.666667      NaN
11/11/2025  59100  59600  58800  58900  2540900  59700.000000      NaN
12/11/2025  59100  59700  59000  59500  2012700  59600.000000      NaN
13/11/2025  59500  60000  59200  59800  2113500  59433.333333      NaN
14/11/2025  59800  60400  59400  60000  2069600  59383.333333  59680.0
17/11/2025  60000  60400  59900  60200  1585600  59533.333333  59770.0
18/11/2025  60400  60400  59800  59900  2158800  59716.666667  59750.0
19/11/2025  59900  60100  59300  59400  2896200  59800.000000  59610.0
20/11/2025  59600  59700  59200  59400  2259400  59783.333333  59520.0
21/11/2025  59100  59200  58700  59000  3452400  59650.000000  59490.0

            Buy_Signal  Sell_Signal  Buy_Price  Sell_Price
Datetime
03/11/2025       False        False        NaN         NaN
04/11/2025       False        False        NaN         NaN
05/11/2025       False        False        NaN         NaN
06/11/2025       False        False        NaN         NaN
07/11/2025       False        False        NaN         NaN
10/11/2025       False        False        NaN         NaN
11/11/2025       False        False        NaN         NaN
12/11/2025       False        False        NaN         NaN
13/11/2025       False        False        NaN         NaN
14/11/2025       False         True        NaN     60000.0
17/11/2025       False         True        NaN     60200.0
18/11/2025       False         True        NaN     59900.0
19/11/2025        True        False    59400.0         NaN
20/11/2025        True        False    59400.0         NaN
21/11/2025        True        False    59000.0         NaN

# Co tin hieu Buy/ Sell => Chuyen qua Redis

In [23]:
import redis

r = redis.Redis(host='localhost', port=6379, db=0)
hash_key = 'VCB_Buy_Sell_Signal'

# Lay record cuoi cung cua Buy_Signal va Sell_Signal => Chuyen qua Redis
last_record = data.iloc[-1]

if(last_record['Buy_Signal'] == True or last_record['Sell_Signal'] == True):
	for field, value in last_record.to_dict().items():
		# Chuyển đổi giá trị uint64 và Timestamp thành chuỗi
		if isinstance(value, pd.Timestamp):
			value = value.isoformat()
		elif isinstance(value, (int, np.uint64)):
			value = str(value)
		r.hset(hash_key, field, value)  
		r.hset(hash_key, 'Symbol', symbol)
		r.hset(hash_key, 'Insertdate', datetime.now().isoformat())
	print(last_record)   
else:
	print('Không có tín hiệu!')

Open                  63200
High                  63200
Low                   61000
Close                 61000
Volume             10595600
SMA6           62033.333333
SMA10               61940.0
Buy_Signal             True
Sell_Signal           False
Buy_Price           61000.0
Sell_Price              NaN
Name: 29/07/2025, dtype: object

In [ ]:
data

In [ ]:
data.to_csv('Buoi4.3_SSI_Chienluoc.csv')

In [ ]:
import pandas as pd
import plotly.graph_objects as go

####################################################################################################
# Tạo figure
fig = go.Figure()

# Thêm đường giá đóng cửa, SMA và Bollinger Bands
fig.add_trace(go.Scatter(x=data.index, y=data['Close'], mode='lines', name='Giá Đóng Cửa'))
fig.add_trace(go.Scatter(x=data.index, y=data['SMA'], mode='lines', name='SMA'))
fig.add_trace(go.Scatter(x=data.index, y=data['Upper_Band'], mode='lines', name='Bollinger Band Trên', line=dict(dash='dash')))
fig.add_trace(go.Scatter(x=data.index, y=data['Lower_Band'], mode='lines', name='Bollinger Band Dưới', line=dict(dash='dash')))

# Điền màu giữa Upper và Lower Bands
fig.add_trace(go.Scatter(x=data.index, y=data['Upper_Band'], mode='lines', name='Upper Band', line=dict(width=0)))
fig.add_trace(go.Scatter(x=data.index, y=data['Lower_Band'], mode='lines', name='Lower Band', fill='tonexty', fillcolor='rgba(204,204,204,0.2)', line=dict(width=0)))

# Vẽ các điểm cho tín hiệu mua
buy_signals = data[data['Buy_Signal']]
fig.add_trace(go.Scatter(x=buy_signals.index, y=buy_signals['Close'], mode='markers', name='Buy Signal', marker=dict(symbol='triangle-up', size=10, color='green')))

# Vẽ các điểm cho tín hiệu bán
sell_signals = data[data['Sell_Signal']]
fig.add_trace(go.Scatter(x=sell_signals.index, y=sell_signals['Close'], mode='markers', name='Sell Signal', marker=dict(symbol='triangle-down', size=10, color='red')))

# Cập nhật thông tin layout
fig.update_layout(title='Biểu Đồ Bollinger Bands và RSI', xaxis_title='Ngày', yaxis_title='Giá', showlegend=True)

# Vẽ biểu đồ
fig.show()

####################################################################################################
# Tạo figure
fig = go.Figure()

fig.add_trace(go.Scatter(x=data.index, y=data['RSI'], mode='lines', name='RSI', line=dict(color='purple')))

# Thêm các đường ngang tại các mức 70 và 30
fig.add_hline(y=70, line_dash="dash", line_color="red", line_width=0.5)
fig.add_hline(y=30, line_dash="dash", line_color="green", line_width=0.5)

# Điền màu giữa các mức 70 và 30
fig.add_trace(go.Scatter(x=data.index, y=[70]*len(data.index), mode='lines', name='RSI70', line=dict(width=0)))
fig.add_trace(go.Scatter(x=data.index, y=[30]*len(data.index), mode='lines', name='RSI30', fill='tonexty', fillcolor='rgba(204,204,204,0.2)', line=dict(width=0)))

# Cập nhật thông tin layout cho biểu đồ RSI
fig.update_layout(title='Biểu Đồ RSI', xaxis_title='Ngày', yaxis_title='RSI', showlegend=True)

# Vẽ biểu đồ
fig.show()

# Mo rong: Them Volume (line)

In [ ]:
import plotly.graph_objs as go

# Chuyển Volume sang số
data['Volume'] = pd.to_numeric(data['Volume'])

# Làm sạch dữ liệu Volume
data['Volume'].fillna(0, inplace=True)  # Thay thế giá trị NaN bằng 0 hoặc giá trị thích hợp

# Tạo figure cho giá và Bollinger Bands
fig = go.Figure()

# Thêm các đường giá đóng cửa, SMA và Bollinger Bands
fig.add_trace(go.Scatter(x=data.index, y=data['Close'], mode='lines', name='Giá đóng cửa'))
fig.add_trace(go.Scatter(x=data.index, y=data['SMA'], mode='lines', name='SMA'))
fig.add_trace(go.Scatter(x=data.index, y=data['Upper_Band'], mode='lines', name='Bollinger Band trên', line=dict(dash='dash')))
fig.add_trace(go.Scatter(x=data.index, y=data['Lower_Band'], mode='lines', name='Bollinger Band dưới', line=dict(dash='dash')))

# Thêm các vùng Bollinger Bands
fig.add_trace(go.Scatter(x=data.index, y=data['Upper_Band'], mode='lines', name='Upper Band', line=dict(width=0)))
fig.add_trace(go.Scatter(x=data.index, y=data['Lower_Band'], mode='lines', name='Lower Band', fill='tonexty', fillcolor='rgba(204,204,204,0.2)', line=dict(width=0)))

# Thêm tín hiệu mua
buy_signals = data[data['Buy_Signal']]
fig.add_trace(go.Scatter(x=buy_signals.index, y=buy_signals['Close'], mode='markers', name='Buy Signal', marker=dict(symbol='triangle-up', size=10, color='green')))

# Thêm tín hiệu bán
sell_signals = data[data['Sell_Signal']]
fig.add_trace(go.Scatter(x=sell_signals.index, y=sell_signals['Close'], mode='markers', name='Sell Signal', marker=dict(symbol='triangle-down', size=10, color='red')))

# Thêm Volume dưới dạng đường
fig.add_trace(go.Scatter(x=data.index, y=data['Volume'], mode='lines', name='Volume', yaxis='y2', line=dict(color='blue', width=2)))

# Cập nhật thông tin layout
fig.update_layout(
	title='Biểu đồ Bollinger Bands và RSI',
	xaxis_title='Ngày',
	yaxis=dict(title='Giá'),
	yaxis2=dict(title='Volume', overlaying='y', side='right', showgrid=False),
	showlegend=True
)

# Hiển thị biểu đồ
fig.show()

# Tạo figure cho RSI
fig_rsi = go.Figure()

fig_rsi.add_trace(go.Scatter(x=data.index, y=data['RSI'], mode='lines', name='RSI', line=dict(color='purple')))

# Đường ngang cho RSI 70 và 30
fig_rsi.add_hline(y=70, line_dash='dash', line_color='red', line_width=0.5)
fig_rsi.add_hline(y=30, line_dash='dash', line_color='green', line_width=0.5)

fig_rsi.add_trace(go.Scatter(x=data.index, y=[70]*len(data.index), mode='lines', name='RSI70', line=dict(width=0)))
fig_rsi.add_trace(go.Scatter(x=data.index, y=[30]*len(data.index), mode='lines', name='RSI30', fill='tonexty', fillcolor='rgba(204,204,204,0.2)', line=dict(width=0)))

# Cập nhật thông tin layout cho biểu đồ RSI
fig_rsi.update_layout(
	title='Biểu đồ RSI',
	xaxis_title='Ngày',
	yaxis_title='RSI',
	showlegend=True
)

# Hiển thị biểu đồ RSI
fig_rsi.show()

# Mo rong: Them Volume (bar)

In [ ]:
import plotly.graph_objs as go
import pandas as pd

# Chuyển Volume sang số
data['Volume'] = pd.to_numeric(data['Volume'])

# Làm sạch dữ liệu Volume
data['Volume'].fillna(0, inplace=True)  # Thay thế giá trị NaN bằng 0 hoặc giá trị thích hợp

# Tạo figure cho giá và Bollinger Bands
fig = go.Figure()

# Thêm các đường giá đóng cửa, SMA và Bollinger Bands
fig.add_trace(go.Scatter(x=data.index, y=data['Close'], mode='lines', name='Giá đóng cửa'))
fig.add_trace(go.Scatter(x=data.index, y=data['SMA'], mode='lines', name='SMA'))
fig.add_trace(go.Scatter(x=data.index, y=data['Upper_Band'], mode='lines', name='Bollinger Band trên', line=dict(dash='dash')))
fig.add_trace(go.Scatter(x=data.index, y=data['Lower_Band'], mode='lines', name='Bollinger Band dưới', line=dict(dash='dash')))

# Thêm các vùng Bollinger Bands
fig.add_trace(go.Scatter(x=data.index, y=data['Upper_Band'], mode='lines', name='Upper Band', line=dict(width=0)))
fig.add_trace(go.Scatter(x=data.index, y=data['Lower_Band'], mode='lines', name='Lower Band', fill='tonexty', fillcolor='rgba(204,204,204,0.2)', line=dict(width=0)))

# Thêm tín hiệu mua
buy_signals = data[data['Buy_Signal']]
fig.add_trace(go.Scatter(x=buy_signals.index, y=buy_signals['Close'], mode='markers', name='Buy Signal', marker=dict(symbol='triangle-up', size=10, color='green')))

# Thêm tín hiệu bán
sell_signals = data[data['Sell_Signal']]
fig.add_trace(go.Scatter(x=sell_signals.index, y=sell_signals['Close'], mode='markers', name='Sell Signal', marker=dict(symbol='triangle-down', size=10, color='red')))

# Thêm Volume dưới dạng cột
fig.add_trace(go.Bar(x=data.index, y=data['Volume'], name='Volume', yaxis='y2', marker_color='rgba(0, 0, 255, 0.5)'))

# Cập nhật thông tin layout
fig.update_layout(
	title='Biểu đồ Bollinger Bands và RSI',
	xaxis_title='Ngày',
	yaxis=dict(title='Giá'),
	yaxis2=dict(title='Volume', overlaying='y', side='right', showgrid=False),
	showlegend=True
)

# Hiển thị biểu đồ
fig.show()

# Tạo figure cho RSI
fig_rsi = go.Figure()

fig_rsi.add_trace(go.Scatter(x=data.index, y=data['RSI'], mode='lines', name='RSI', line=dict(color='purple')))

# Đường ngang cho RSI 70 và 30
fig_rsi.add_hline(y=70, line_dash='dash', line_color='red', line_width=0.5)
fig_rsi.add_hline(y=30, line_dash='dash', line_color='green', line_width=0.5)

fig_rsi.add_trace(go.Scatter(x=data.index, y=[70]*len(data.index), mode='lines', name='RSI70', line=dict(width=0)))
fig_rsi.add_trace(go.Scatter(x=data.index, y=[30]*len(data.index), mode='lines', name='RSI30', fill='tonexty', fillcolor='rgba(204,204,204,0.2)', line=dict(width=0)))

# Cập nhật thông tin layout cho biểu đồ RSI
fig_rsi.update_layout(
	title='Biểu đồ RSI',
	xaxis_title='Ngày',
	yaxis_title='RSI',
	showlegend=True
)

# Hiển thị biểu đồ RSI
fig_rsi.show()