# Code cua ho

In [ ]:
# import ssi_fc_trading
from ssi_fc_data import fc_md_client , model
import config


client = fc_md_client.MarketDataClient(config)
def md_access_token():
	print(client.access_token(model.accessToken(config.consumerID, config.consumerSecret)))

def md_get_securities_list():
    req = model.securities('HNX', 1, 1000)
    print(client.securities(config, req))

def md_get_securities_details():
    req = model.securities_details('HNX', 'ACB', 1, 100)
    print(client.securities_details(config, req))

def md_get_index_components():
	print(client.index_components(config, model.index_components('vn100', 1, 100)))

def md_get_index_list():
	print(client.index_list(config, model.index_list('hnx', 1, 100)))

def md_get_daily_OHLC():
	print(client.daily_ohlc(config, model.daily_ohlc('acb', '29/09/2025', '01/10/2025', 1, 100, False)))

def md_get_intraday_OHLC():
	print(client.intraday_ohlc(config, model.intraday_ohlc('fpt', '15/10/2020', '15/10/2020', 1, 100, True, 1)))

def md_get_daily_index():
	print(client.daily_index(config, model.daily_index( '123', 'VN100', '15/10/2020', '15/10/2020', 1, 100, '', '')))

def md_get_stock_price():
	print(client.daily_stock_price(config, model.daily_stock_price ('fpt', '15/10/2020', '15/10/2020', 1, 100, 'hose')))



def main():
    
    while True:
        print('11  - Securities List')
        print('12  - Securities Details')
        print('13  - Index Components')
        print('14  - Index List')
        print('15  - Daily OHLC')
        print('16  - Intraday OHLC')
        print('17  - Daily index')
        print('18  - Stock price')
        value = input('Enter your choice: ')

        if value == '11':
            md_get_securities_list()
        elif value == '12':
            md_get_securities_details()
        elif value == '13':
            md_get_index_components()
        elif value == '14':
            md_get_index_list()
        elif value == '15':
            md_get_daily_OHLC()
        elif value == '16':
            md_get_intraday_OHLC()
        elif value == '17':
            md_get_daily_index()
        elif value == '18':
            md_get_stock_price()

if __name__ == '__main__':
	main()

11  - Securities List
12  - Securities Details
13  - Index Components
14  - Index List
15  - Daily OHLC
16  - Intraday OHLC
17  - Daily index
18  - Stock price

# Viet lai lay Daily OHLCV cua Symbol STB

In [27]:
# import ssi_fc_trading
import pandas as pd
from ssi_fc_data import fc_md_client , model
import config
client = fc_md_client.MarketDataClient(config)

def get_daily_OHLC_Data(symbol, from_date, to_date):
	data = client.daily_ohlc(config, model.daily_ohlc(symbol, from_date, to_date, 1, 100, False))
	data_list = data['data']
	data = pd.DataFrame(data_list)
	return data

# Goi ham

In [ ]:
symbol = 'ACB'
from_date = '29/09/2025'
to_date = '01/10/2025'
data = get_daily_OHLC_Data(symbol, from_date, to_date)
# Chuyen cot Close thanh float
data['Close'] = pd.to_numeric(data['Close'])
# Chuyen cot Volume thanh float
data['Volume'] = pd.to_numeric(data['Volume'])

data['CheckValue'] = data['Close'] * data['Volume']

data

,Symbol,Market,TradingDate,Time,Open,High,Low,Close,Volume,Value,CheckValue
0,ACB,HOSE,01/10/2025,None,25700,25950,25550,25800,10480500,270041680000,270396900000
1,ACB,HOSE,30/09/2025,None,25750,25800,25450,25500,9277900,237527205000,236586450000
2,ACB,HOSE,29/09/2025,None,25550,25800,25350,25600,8265200,211173625000,211589120000

# Goi ham trong Common

In [3]:
import sys
sys.path.append("../Common/")

import TradeSSI
symbol = 'ACB'
from_date = '29/09/2025'
to_date = '01/10/2025'
data = TradeSSI.TradeSSI.get_daily_OHLC_Data(symbol, from_date, to_date)
data

,Symbol,Market,TradingDate,Time,Open,High,Low,Close,Volume,Value
0,ACB,HOSE,01/10/2025,None,25700,25950,25550,25800,10480500,270041680000
1,ACB,HOSE,30/09/2025,None,25750,25800,25450,25500,9277900,237527205000
2,ACB,HOSE,29/09/2025,None,25550,25800,25350,25600,8265200,211173625000

# Chung ta Customize lai de su dung

## Customize lai lay Access Token

In [ ]:
# import ssi_fc_trading
from ssi_fc_data import fc_md_client , model # 1
import config # 2

# Lay y chang model cua no o tren
client = fc_md_client.MarketDataClient(config) # 3

# Khai bao ham tu model
def Xacthuc_token():
	print(client.access_token(model.accessToken(config.consumerID, config.consumerSecret)))

# Goi ham
Xacthuc_token()

In [ ]:
# import ssi_fc_trading
from ssi_fc_data import fc_md_client , model
import config

# Lay y chang model cua no o tren
client = fc_md_client.MarketDataClient(config)
print(client.access_token(model.accessToken(config.consumerID, config.consumerSecret)))

# Lay du lieu theo ngay

In [ ]:
# Lay du lieu theo ngay cua VCB
symbol = 'VCB'
from_date = '01/07/2025'
to_date = '29/07/2025'
timeframe = '1D'

In [4]:
# Import necessary modules
from ssi_fc_data import fc_md_client, model
import config
import pandas as pd  # Import Pandas for DataFrame handling
import json
# Create a Market Data Client
client = fc_md_client.MarketDataClient(config)

# Create a request for daily stock price data
req = model.daily_stock_price(symbol, from_date, to_date) # Lay 1 ngay hoac la nhieu ngay
# Request daily stock price data using the Market Data Client
data_dict = client.daily_stock_price(config, req)

print(type(data_dict))
print(data_dict)

<class 'dict'>
{'data': [{'TradingDate': '29/09/2025', 'PriceChange': '-50', 'PerPriceChange': '-0.20', 'CeilingPrice': '27400', 'FloorPrice': '23900', 'RefPrice': '25650', 'OpenPrice': '25550', 'HighestPrice': '25800', 'LowestPrice': '25350', 'ClosePrice': '25600', 'AveragePrice': '25800', 'ClosePriceAdjusted': '25600', 'TotalMatchVol': '8265200', 'TotalMatchVal': '211173625000', 'TotalDealVal': '0', 'TotalDealVol': '0', 'ForeignBuyVolTotal': '808364', 'ForeignCurrentRoom': '0', 'ForeignSellVolTotal': '298100', 'ForeignBuyValTotal': '20670221350', 'ForeignSellValTotal': '7589025000', 'TotalBuyTrade': '0', 'TotalBuyTradeVol': '0', 'TotalSellTrade': '0', 'TotalSellTradeVol': '0', 'NetBuySellVol': '510264', 'NetBuySellVal': '13081196350', 'TotalTradedVol': '8265200', 'TotalTradedValue': '211173625000', 'Symbol': 'ACB', 'Time': None}, {'TradingDate': '30/09/2025', 'PriceChange': '-100', 'PerPriceChange': '-0.40', 'CeilingPrice': '27350', 'FloorPrice': '23850', 'RefPrice': '25600', 'OpenPrice': '25750', 'HighestPrice': '25800', 'LowestPrice': '25450', 'ClosePrice': '25500', 'AveragePrice': '25800', 'ClosePriceAdjusted': '25500', 'TotalMatchVol': '9277900', 'TotalMatchVal': '237527205000', 'TotalDealVal': '17700489000', 'TotalDealVol': '686500', 'ForeignBuyVolTotal': '3034335', 'ForeignCurrentRoom': '0', 'ForeignSellVolTotal': '1782300', 'ForeignBuyValTotal': '77804923650', 'ForeignSellValTotal': '45584895900', 'TotalBuyTrade': '0', 'TotalBuyTradeVol': '0', 'TotalSellTrade': '0', 'TotalSellTradeVol': '0', 'NetBuySellVol': '1252035', 'NetBuySellVal': '32220027750', 'TotalTradedVol': '9964400', 'TotalTradedValue': '255227694000', 'Symbol': 'ACB', 'Time': None}, {'TradingDate': '01/10/2025', 'PriceChange': '300', 'PerPriceChange': '1.20', 'CeilingPrice': '27250', 'FloorPrice': '23750', 'RefPrice': '25500', 'OpenPrice': '25700', 'HighestPrice': '25950', 'LowestPrice': '25550', 'ClosePrice': '25800', 'AveragePrice': '25950', 'ClosePriceAdjusted': '25800', 'TotalMatchVol': '10480500', 'TotalMatchVal': '270041680000', 'TotalDealVal': '5834400000', 'TotalDealVol': '228800', 'ForeignBuyVolTotal': '1870400', 'ForeignCurrentRoom': '0', 'ForeignSellVolTotal': '3542400', 'ForeignBuyValTotal': '48085505900', 'ForeignSellValTotal': '91209840000', 'TotalBuyTrade': '0', 'TotalBuyTradeVol': '0', 'TotalSellTrade': '0', 'TotalSellTradeVol': '0', 'NetBuySellVol': '-1672000', 'NetBuySellVal': '-43124334100', 'TotalTradedVol': '10709300', 'TotalTradedValue': '275876080000', 'Symbol': 'ACB', 'Time': None}], 'message': 'Success', 'status': 'Success', 'totalRecord': 3}

# Parse sang dataframe

In [ ]:
# import pandas as pd

# dataFrame = pd.DataFrame(data_dict)

In [5]:
# Access the list of dictionaries in the "data" field
data_list = data_dict['data'] # Lay value cua data
data_list

print(type(data_list))

<class 'list'>

In [6]:
import pandas as pd 
# Chuyen tu danh sach sang DataFrame
df = pd.DataFrame(data_list)

# Print or work with the DataFrame
df

,TradingDate,PriceChange,PerPriceChange,CeilingPrice,FloorPrice,RefPrice,OpenPrice,HighestPrice,LowestPrice,ClosePrice,...,TotalBuyTrade,TotalBuyTradeVol,TotalSellTrade,TotalSellTradeVol,NetBuySellVol,NetBuySellVal,TotalTradedVol,TotalTradedValue,Symbol,Time
0,29/09/2025,-50,-0.20,27400,23900,25650,25550,25800,25350,25600,...,0,0,0,0,510264,13081196350,8265200,211173625000,ACB,None
1,30/09/2025,-100,-0.40,27350,23850,25600,25750,25800,25450,25500,...,0,0,0,0,1252035,32220027750,9964400,255227694000,ACB,None
2,01/10/2025,300,1.20,27250,23750,25500,25700,25950,25550,25800,...,0,0,0,0,-1672000,-43124334100,10709300,275876080000,ACB,None

In [ ]:
# Chuyen df o tren chi lay cac cot TradingDate, OpenPrice, ClosePrice, HighPrice, LowPrice, Volume
df_filtered = df[['TradingDate', 'OpenPrice', 'HighestPrice', 'LowestPrice', 'ClosePrice', 'TotalTradedVol']]
df_filtered

# Rename cot

In [ ]:
# Doi ten co TradingDate thanh Datetime , cot TotalTradedVol thanh Volume
df_filtered.rename(columns={'TradingDate': 'Datetime'}, inplace=True) # Inplace means modify df_filtered directly
df_filtered.rename(columns={'OpenPrice': 'Open'}, inplace=True) # Inplace means modify df_filtered directly
df_filtered.rename(columns={'HighestPrice': 'High'}, inplace=True)
df_filtered.rename(columns={'LowestPrice': 'Low'}, inplace=True)
df_filtered.rename(columns={'ClosePrice': 'Close'}, inplace=True)
df_filtered.rename(columns={'TotalTradedVol': 'Volume'}, inplace=True)
df_filtered

# Datatype la gi

In [ ]:
df_filtered.info()

# Chuyen datatype cua cot thanh datatype

In [ ]:
df_filtered['Volume'] = pd.to_numeric(df_filtered['Volume'])

df_filtered.info()
df_filtered.head()

df_filtered.tail()

In [ ]:
df_filtered

# Lay du lieu theo ngay

In [ ]:
# Import necessary modules
from ssi_fc_data import fc_md_client, model
import pandas as pd  # Import Pandas for DataFrame handling
import json
import config

# Create a Market Data Client
client = fc_md_client.MarketDataClient(config)

# req = model.daily_ohlc('VNINDEX', "13/11/2024", "29/07/2025", 1, 500, True)
req = model.daily_ohlc('41I1F8000', "29/07/2025", "29/07/2025", 1, 500, True)
# req = model.daily_ohlc('VCB', "01/06/2025", "11/06/2025", 1, 500, True)

# req = model.daily_ohlc('STB', "01/01/2024", "07/08/2024", 1, 500, True)
# print(client.daily_ohlc(configDataSSI, model.daily_ohlc('ssi', '15/10/2020', '15/10/2020', 1, 100, True)))

data_dict = client.daily_ohlc(config, req)

# print("Dictionary type:", type(data_dict))
# print(data_dict)
# Access the list of dictionaries in the "data" field
data_list = data_dict['data']

# Convert the list of dictionaries into a DataFrame
df = pd.DataFrame(data_list)

print("DataFrame type:", type(df))
# Print or work with the DataFrame
df

In [ ]:
print(type(df))
df.info()

In [ ]:
# Import necessary modules
from ssi_fc_data import fc_md_client, model
import pandas as pd  # Import Pandas for DataFrame handling
import json
import configDataSSI

# Create a Market Data Client
client = fc_md_client.MarketDataClient(configDataSSI)

req = model.daily_ohlc('VN30', "01/01/2023", "07/08/2024", 1, 500, True)

# req = model.daily_ohlc('STB', "01/01/2024", "07/08/2024", 1, 500, True)

# print(client.daily_ohlc(configDataSSI, model.daily_ohlc('ssi', '15/10/2020', '15/10/2020', 1, 100, True)))

data_dict = client.daily_ohlc(configDataSSI, req)
# print(data_dict)
# Access the list of dictionaries in the "data" field
data_list = data_dict['data']

# Convert the list of dictionaries into a DataFrame
df = pd.DataFrame(data_list)

# Print or work with the DataFrame
df

# Intraday

In [7]:
# Import necessary modules
from ssi_fc_data import fc_md_client, model
import pandas as pd  # Import Pandas for DataFrame handling
import json
import configDataSSI

# Create a Market Data Client
client = fc_md_client.MarketDataClient(configDataSSI)

req = model.intraday_ohlc('VCB', '29/07/2025', '29/07/2025', 1, 1000, True)

data_dict = client.intraday_ohlc(configDataSSI, req)
# Access the list of dictionaries in the "data" field
data_list = data_dict['data']
print(data_list)
# Convert the list of dictionaries into a DataFrame
df = pd.DataFrame(data_list)

# Print or work with the DataFrame
df
df.to_csv(r'G:\My Drive\0. Day ben ngoai (___)\Day Cole\Khoa Auto Trading K11 - Thanhdt (03.2025)\Buổi 7. Chung khoan VN, Forex\intraday_ohlc_VCB.csv', index=False)

[{'Symbol': 'VCB', 'Value': '63000', 'TradingDate': '29/07/2025', 'Time': '09:15:56', 'Open': '63200', 'High': '63200', 'Low': '63000', 'Close': '63000', 'Volume': '88400'}, {'Symbol': 'VCB', 'Value': '63000', 'TradingDate': '29/07/2025', 'Time': '09:16:59', 'Open': '63100', 'High': '63100', 'Low': '62900', 'Close': '63000', 'Volume': '53900'}, {'Symbol': 'VCB', 'Value': '62900', 'TradingDate': '29/07/2025', 'Time': '09:17:59', 'Open': '63000', 'High': '63000', 'Low': '62900', 'Close': '62900', 'Volume': '107600'}, {'Symbol': 'VCB', 'Value': '62900', 'TradingDate': '29/07/2025', 'Time': '09:18:58', 'Open': '63000', 'High': '63000', 'Low': '62900', 'Close': '62900', 'Volume': '19800'}, {'Symbol': 'VCB', 'Value': '62900', 'TradingDate': '29/07/2025', 'Time': '09:19:52', 'Open': '62900', 'High': '63000', 'Low': '62900', 'Close': '62900', 'Volume': '46100'}, {'Symbol': 'VCB', 'Value': '62800', 'TradingDate': '29/07/2025', 'Time': '09:20:55', 'Open': '62900', 'High': '62900', 'Low': '62800', 'Close': '62800', 'Volume': '14600'}, {'Symbol': 'VCB', 'Value': '62700', 'TradingDate': '29/07/2025', 'Time': '09:21:54', 'Open': '62800', 'High': '62800', 'Low': '62700', 'Close': '62700', 'Volume': '64600'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:22:56', 'Open': '62700', 'High': '62700', 'Low': '62500', 'Close': '62500', 'Volume': '43600'}, {'Symbol': 'VCB', 'Value': '62300', 'TradingDate': '29/07/2025', 'Time': '09:23:58', 'Open': '62500', 'High': '62600', 'Low': '62300', 'Close': '62300', 'Volume': '137900'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '09:24:57', 'Open': '62300', 'High': '62400', 'Low': '62300', 'Close': '62400', 'Volume': '72500'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:25:57', 'Open': '62300', 'High': '62500', 'Low': '62300', 'Close': '62500', 'Volume': '42500'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '09:26:53', 'Open': '62400', 'High': '62700', 'Low': '62400', 'Close': '62600', 'Volume': '55500'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '09:27:57', 'Open': '62700', 'High': '62700', 'Low': '62600', 'Close': '62600', 'Volume': '6200'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '09:28:47', 'Open': '62600', 'High': '62700', 'Low': '62600', 'Close': '62600', 'Volume': '11500'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '09:29:54', 'Open': '62600', 'High': '62700', 'Low': '62600', 'Close': '62600', 'Volume': '10700'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '09:30:47', 'Open': '62600', 'High': '62700', 'Low': '62500', 'Close': '62600', 'Volume': '35200'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '09:31:55', 'Open': '62700', 'High': '62700', 'Low': '62600', 'Close': '62600', 'Volume': '15400'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '09:32:46', 'Open': '62600', 'High': '62600', 'Low': '62600', 'Close': '62600', 'Volume': '22100'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:33:57', 'Open': '62600', 'High': '62600', 'Low': '62500', 'Close': '62500', 'Volume': '12900'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:34:59', 'Open': '62500', 'High': '62500', 'Low': '62500', 'Close': '62500', 'Volume': '5700'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '09:35:59', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62600', 'Volume': '9300'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:36:54', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62500', 'Volume': '25300'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:37:56', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62500', 'Volume': '25700'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:38:58', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62500', 'Volume': '30100'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '09:39:52', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62600', 'Volume': '57600'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '09:40:59', 'Open': '62500', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '13200'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:41:57', 'Open': '62400', 'High': '62600', 'Low': '62400', 'Close': '62500', 'Volume': '34900'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:42:59', 'Open': '62500', 'High': '62500', 'Low': '62500', 'Close': '62500', 'Volume': '13900'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:43:54', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62500', 'Volume': '16400'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:44:49', 'Open': '62500', 'High': '62500', 'Low': '62500', 'Close': '62500', 'Volume': '56400'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '09:45:57', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62600', 'Volume': '70800'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:46:52', 'Open': '62500', 'High': '62500', 'Low': '62500', 'Close': '62500', 'Volume': '49600'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:47:58', 'Open': '62500', 'High': '62500', 'Low': '62400', 'Close': '62500', 'Volume': '57500'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:48:57', 'Open': '62400', 'High': '62500', 'Low': '62400', 'Close': '62500', 'Volume': '25500'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '09:49:58', 'Open': '62400', 'High': '62400', 'Low': '62400', 'Close': '62400', 'Volume': '41400'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '09:50:59', 'Open': '62400', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '25000'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '09:51:54', 'Open': '62400', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '11800'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '09:52:55', 'Open': '62400', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '34000'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:53:59', 'Open': '62500', 'High': '62500', 'Low': '62400', 'Close': '62500', 'Volume': '87800'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '09:54:51', 'Open': '62500', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '16800'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '09:55:49', 'Open': '62400', 'High': '62400', 'Low': '62400', 'Close': '62400', 'Volume': '11600'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:56:49', 'Open': '62400', 'High': '62500', 'Low': '62400', 'Close': '62500', 'Volume': '11700'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '09:57:58', 'Open': '62400', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '24700'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '09:58:28', 'Open': '62500', 'High': '62500', 'Low': '62400', 'Close': '62500', 'Volume': '12600'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '09:59:58', 'Open': '62500', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '36500'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '10:00:53', 'Open': '62500', 'High': '62500', 'Low': '62500', 'Close': '62500', 'Volume': '30400'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '10:01:51', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62600', 'Volume': '8400'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '10:02:59', 'Open': '62600', 'High': '62600', 'Low': '62500', 'Close': '62500', 'Volume': '19200'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '10:03:57', 'Open': '62600', 'High': '62600', 'Low': '62500', 'Close': '62500', 'Volume': '46200'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '10:04:46', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62500', 'Volume': '70100'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '10:05:56', 'Open': '62500', 'High': '62500', 'Low': '62400', 'Close': '62500', 'Volume': '9900'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '10:06:59', 'Open': '62400', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '8000'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '10:07:55', 'Open': '62400', 'High': '62500', 'Low': '62400', 'Close': '62500', 'Volume': '75200'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '10:08:53', 'Open': '62500', 'High': '62500', 'Low': '62500', 'Close': '62500', 'Volume': '6000'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '10:09:58', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62500', 'Volume': '26400'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '10:10:55', 'Open': '62500', 'High': '62600', 'Low': '62500', 'Close': '62500', 'Volume': '7500'}, {'Symbol': 'VCB', 'Value': '62600', 'TradingDate': '29/07/2025', 'Time': '10:11:58', 'Open': '62600', 'High': '62600', 'Low': '62500', 'Close': '62600', 'Volume': '14400'}, {'Symbol': 'VCB', 'Value': '62500', 'TradingDate': '29/07/2025', 'Time': '10:12:46', 'Open': '62500', 'High': '62500', 'Low': '62500', 'Close': '62500', 'Volume': '7000'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '10:13:59', 'Open': '62500', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '99500'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '10:14:59', 'Open': '62400', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '5200'}, {'Symbol': 'VCB', 'Value': '62400', 'TradingDate': '29/07/2025', 'Time': '10:15:55', 'Open': '62500', 'High': '62500', 'Low': '62400', 'Close': '62400', 'Volume': '8100'}, {'Symbol': 'VCB', 'Value': '62300', 'TradingDate': '29/07/2025', 'Time': '10:16:54', 'Open': '62400', 'High': '62500', 'Low': '62300', 'Close': '62300', 'Volume': '68200'}, {'Symbol': 'VCB', 'Value': '62200', 'TradingDate': '29/07/2025', 'Time': '10:17:58', 'Open': '62300', 'High': '62300', 'Low': '62200', 'Close': '62200', 'Volume': '205100'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '10:18:51', 'Open': '62200', 'High': '62200', 'Low': '62100', 'Close': '62100', 'Volume': '73700'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '10:19:57', 'Open': '62100', 'High': '62200', 'Low': '62000', 'Close': '62100', 'Volume': '167500'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:20:59', 'Open': '62000', 'High': '62000', 'Low': '61900', 'Close': '61900', 'Volume': '122100'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:21:58', 'Open': '61900', 'High': '62000', 'Low': '61800', 'Close': '61900', 'Volume': '124800'}, {'Symbol': 'VCB', 'Value': '61800', 'TradingDate': '29/07/2025', 'Time': '10:22:59', 'Open': '61900', 'High': '61900', 'Low': '61800', 'Close': '61800', 'Volume': '53100'}, {'Symbol': 'VCB', 'Value': '61700', 'TradingDate': '29/07/2025', 'Time': '10:23:57', 'Open': '61800', 'High': '61900', 'Low': '61700', 'Close': '61700', 'Volume': '60700'}, {'Symbol': 'VCB', 'Value': '61700', 'TradingDate': '29/07/2025', 'Time': '10:24:58', 'Open': '61700', 'High': '61800', 'Low': '61600', 'Close': '61700', 'Volume': '48300'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:25:59', 'Open': '61800', 'High': '61900', 'Low': '61700', 'Close': '61900', 'Volume': '60900'}, {'Symbol': 'VCB', 'Value': '61800', 'TradingDate': '29/07/2025', 'Time': '10:26:51', 'Open': '61900', 'High': '61900', 'Low': '61700', 'Close': '61800', 'Volume': '40600'}, {'Symbol': 'VCB', 'Value': '61800', 'TradingDate': '29/07/2025', 'Time': '10:27:58', 'Open': '61900', 'High': '61900', 'Low': '61700', 'Close': '61800', 'Volume': '97400'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:28:47', 'Open': '61800', 'High': '62000', 'Low': '61800', 'Close': '61900', 'Volume': '29000'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '10:29:57', 'Open': '61900', 'High': '62100', 'Low': '61900', 'Close': '62100', 'Volume': '76400'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '10:30:55', 'Open': '62000', 'High': '62100', 'Low': '62000', 'Close': '62000', 'Volume': '26300'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '10:31:56', 'Open': '62000', 'High': '62100', 'Low': '62000', 'Close': '62100', 'Volume': '24000'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '10:32:59', 'Open': '62100', 'High': '62200', 'Low': '62000', 'Close': '62000', 'Volume': '22800'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '10:33:57', 'Open': '62000', 'High': '62200', 'Low': '62000', 'Close': '62000', 'Volume': '15700'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '10:34:54', 'Open': '62000', 'High': '62100', 'Low': '62000', 'Close': '62100', 'Volume': '15900'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '10:35:53', 'Open': '62000', 'High': '62100', 'Low': '62000', 'Close': '62100', 'Volume': '17300'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '10:36:50', 'Open': '62000', 'High': '62100', 'Low': '62000', 'Close': '62000', 'Volume': '161800'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:37:59', 'Open': '62000', 'High': '62000', 'Low': '61900', 'Close': '61900', 'Volume': '10800'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '10:38:55', 'Open': '61900', 'High': '62000', 'Low': '61900', 'Close': '62000', 'Volume': '12400'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:39:56', 'Open': '62000', 'High': '62000', 'Low': '61900', 'Close': '61900', 'Volume': '11600'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:40:55', 'Open': '61900', 'High': '62000', 'Low': '61900', 'Close': '61900', 'Volume': '20500'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:41:59', 'Open': '61900', 'High': '62000', 'Low': '61900', 'Close': '61900', 'Volume': '14700'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:42:56', 'Open': '61900', 'High': '62000', 'Low': '61900', 'Close': '61900', 'Volume': '13200'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '10:43:52', 'Open': '62000', 'High': '62000', 'Low': '61900', 'Close': '62000', 'Volume': '4800'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '10:44:48', 'Open': '62000', 'High': '62000', 'Low': '61900', 'Close': '62000', 'Volume': '2200'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '10:45:53', 'Open': '62000', 'High': '62000', 'Low': '62000', 'Close': '62000', 'Volume': '2400'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:46:58', 'Open': '62000', 'High': '62000', 'Low': '61900', 'Close': '61900', 'Volume': '17100'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:47:57', 'Open': '61900', 'High': '61900', 'Low': '61900', 'Close': '61900', 'Volume': '27100'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '10:48:55', 'Open': '61900', 'High': '62000', 'Low': '61900', 'Close': '61900', 'Volume': '35200'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '10:49:58', 'Open': '61900', 'High': '62000', 'Low': '61900', 'Close': '62000', 'Volume': '5600'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '10:50:57', 'Open': '62000', 'High': '62000', 'Low': '61900', 'Close': '62000', 'Volume': '47900'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '10:51:59', 'Open': '62000', 'High': '62100', 'Low': '62000', 'Close': '62100', 'Volume': '20800'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '10:52:57', 'Open': '62100', 'High': '62200', 'Low': '62000', 'Close': '62100', 'Volume': '30600'}, {'Symbol': 'VCB', 'Value': '62200', 'TradingDate': '29/07/2025', 'Time': '10:53:57', 'Open': '62100', 'High': '62200', 'Low': '62000', 'Close': '62200', 'Volume': '37600'}, {'Symbol': 'VCB', 'Value': '62200', 'TradingDate': '29/07/2025', 'Time': '10:54:59', 'Open': '62100', 'High': '62200', 'Low': '62100', 'Close': '62200', 'Volume': '4400'}, {'Symbol': 'VCB', 'Value': '62200', 'TradingDate': '29/07/2025', 'Time': '10:55:37', 'Open': '62100', 'High': '62200', 'Low': '62100', 'Close': '62200', 'Volume': '4800'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '10:57:57', 'Open': '62200', 'High': '62200', 'Low': '62100', 'Close': '62100', 'Volume': '1800'}, {'Symbol': 'VCB', 'Value': '62200', 'TradingDate': '29/07/2025', 'Time': '10:58:57', 'Open': '62100', 'High': '62200', 'Low': '62100', 'Close': '62200', 'Volume': '12100'}, {'Symbol': 'VCB', 'Value': '62200', 'TradingDate': '29/07/2025', 'Time': '10:59:17', 'Open': '62200', 'High': '62200', 'Low': '62100', 'Close': '62200', 'Volume': '3500'}, {'Symbol': 'VCB', 'Value': '62200', 'TradingDate': '29/07/2025', 'Time': '11:00:37', 'Open': '62200', 'High': '62200', 'Low': '62100', 'Close': '62200', 'Volume': '1900'}, {'Symbol': 'VCB', 'Value': '62300', 'TradingDate': '29/07/2025', 'Time': '11:01:57', 'Open': '62200', 'High': '62300', 'Low': '62200', 'Close': '62300', 'Volume': '97900'}, {'Symbol': 'VCB', 'Value': '62300', 'TradingDate': '29/07/2025', 'Time': '11:02:57', 'Open': '62300', 'High': '62300', 'Low': '62300', 'Close': '62300', 'Volume': '600'}, {'Symbol': 'VCB', 'Value': '62300', 'TradingDate': '29/07/2025', 'Time': '11:03:37', 'Open': '62300', 'High': '62300', 'Low': '62300', 'Close': '62300', 'Volume': '11200'}, {'Symbol': 'VCB', 'Value': '62200', 'TradingDate': '29/07/2025', 'Time': '11:04:59', 'Open': '62200', 'High': '62200', 'Low': '62100', 'Close': '62200', 'Volume': '45100'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '11:05:57', 'Open': '62200', 'High': '62200', 'Low': '62000', 'Close': '62100', 'Volume': '5500'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '11:06:49', 'Open': '62000', 'High': '62100', 'Low': '62000', 'Close': '62100', 'Volume': '9700'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '11:07:58', 'Open': '62100', 'High': '62100', 'Low': '62000', 'Close': '62000', 'Volume': '10800'}, {'Symbol': 'VCB', 'Value': '62100', 'TradingDate': '29/07/2025', 'Time': '11:08:57', 'Open': '62000', 'High': '62100', 'Low': '62000', 'Close': '62100', 'Volume': '8700'}, {'Symbol': 'VCB', 'Value': '61900', 'TradingDate': '29/07/2025', 'Time': '11:09:57', 'Open': '62000', 'High': '62100', 'Low': '61900', 'Close': '61900', 'Volume': '23300'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '11:10:58', 'Open': '61900', 'High': '62100', 'Low': '61900', 'Close': '62000', 'Volume': '16800'}, {'Symbol': 'VCB', 'Value': '62000', 'TradingDate': '29/07/2025', 'Time': '11:11:57', 'Open': '62000', 'High': '62000', 'Lo

In [9]:
df

    Symbol  Value TradingDate      Time   Open   High    Low  Close  Volume
0      VCB  63000  29/07/2025  09:15:56  63200  63200  63000  63000   88400
1      VCB  63000  29/07/2025  09:16:59  63100  63100  62900  63000   53900
2      VCB  62900  29/07/2025  09:17:59  63000  63000  62900  62900  107600
3      VCB  62900  29/07/2025  09:18:58  63000  63000  62900  62900   19800
4      VCB  62900  29/07/2025  09:19:52  62900  63000  62900  62900   46100
..     ...    ...         ...       ...    ...    ...    ...    ...     ...
220    VCB  61300  29/07/2025  14:26:56  61300  61400  61300  61300   79900
221    VCB  61400  29/07/2025  14:27:58  61300  61400  61300  61400  115200
222    VCB  61400  29/07/2025  14:28:58  61300  61400  61200  61400  142200
223    VCB  61400  29/07/2025  14:29:56  61300  61500  61200  61400  119400
224    VCB  61000  29/07/2025  14:45:00  61000  61000  61000  61000  981600

[225 rows x 9 columns]

In [ ]:
# Import necessary modules
from ssi_fc_data import fc_md_client, model
import pandas as pd  # Import Pandas for DataFrame handling
import json
import configDataSSI

# Create a Market Data Client
client = fc_md_client.MarketDataClient(configDataSSI)

# req = model.intraday_ohlc('VCB', '04/06/2024', '04/06/2024')

req = model.intraday_ohlc('VN30', '11/07/2024', '11/07/2024', 1, 1000, True)

data_dict = client.intraday_ohlc(configDataSSI, req)
# Access the list of dictionaries in the "data" field
data_list = data_dict['data']

# Convert the list of dictionaries into a DataFrame
df = pd.DataFrame(data_list)

# Print or work with the DataFrame
df

# Viet ham lay data

In [51]:
def loaddataSSI(symbol, from_date, to_date): # 'VCB', '27/10/2023', '27/10/2023'

    from ssi_fc_data import fc_md_client, model
    import pandas as pd  # Import Pandas for DataFrame handling
    import json
    import configDataSSI

    # Create a Market Data Client
    client = fc_md_client.MarketDataClient(configDataSSI)

    req = model.intraday_ohlc(symbol, from_date, to_date)

    data_dict = client.intraday_ohlc(configDataSSI, req)
    # Access the list of dictionaries in the "data" field
    data_list = data_dict['data']

    # Convert the list of dictionaries into a DataFrame
    data = pd.DataFrame(data_list)
    # print(data)
    data = data.rename(columns={'TradingDate': 'Datetime'})        
    data = data.rename(columns={'open': 'Open'})       
    data = data.rename(columns={'high': 'High'})       
    data = data.rename(columns={'low': 'Low'})       
    data = data.rename(columns={'close': 'Close'})       
    data = data.rename(columns={'tick_volume': 'Volume'})       

    data = pd.DataFrame(data, columns=['Symbol', 'Datetime', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume'])

    return data

In [52]:
loaddataSSI('VCB', '29/07/2025', '29/07/2025')

   Symbol    Datetime      Time   Open   High    Low  Close  Volume
0     VCB  29/07/2025  09:15:56  63200  63200  63000  63000   88400
1     VCB  29/07/2025  09:16:59  63100  63100  62900  63000   53900
2     VCB  29/07/2025  09:17:59  63000  63000  62900  62900  107600
3     VCB  29/07/2025  09:18:58  63000  63000  62900  62900   19800
4     VCB  29/07/2025  09:19:52  62900  63000  62900  62900   46100
..    ...         ...       ...    ...    ...    ...    ...     ...
95    VCB  29/07/2025  10:50:57  62000  62000  61900  62000   47900
96    VCB  29/07/2025  10:51:59  62000  62100  62000  62100   20800
97    VCB  29/07/2025  10:52:57  62100  62200  62000  62100   30600
98    VCB  29/07/2025  10:53:57  62100  62200  62000  62200   37600
99    VCB  29/07/2025  10:54:59  62100  62200  62100  62200    4400

[100 rows x 8 columns]

In [53]:
def loaddataSSI_Daily(symbol, from_date, to_date): # 'VCB', '27/10/2023', '27/10/2023'

    from ssi_fc_data import fc_md_client, model
    import pandas as pd  # Import Pandas for DataFrame handling
    import json
    import configDataSSI

    # Create a Market Data Client
    client = fc_md_client.MarketDataClient(configDataSSI)

    req = model.daily_ohlc(symbol, from_date, to_date)

    data_dict = client.daily_ohlc(configDataSSI, req)
    # Access the list of dictionaries in the "data" field
    data_list = data_dict['data']

    # Convert the list of dictionaries into a DataFrame
    data = pd.DataFrame(data_list)
    # print(data)
    data = data.rename(columns={'TradingDate': 'Datetime'})        
    data = data.rename(columns={'open': 'Open'})       
    data = data.rename(columns={'high': 'High'})       
    data = data.rename(columns={'low': 'Low'})       
    data = data.rename(columns={'close': 'Close'})       
    data = data.rename(columns={'tick_volume': 'Volume'})       

    data = pd.DataFrame(data, columns=['Symbol', 'Datetime', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume'])

    return data

In [55]:
loaddataSSI_Daily('VCB', '01/07/2025', '29/07/2025')

   Symbol    Datetime  Time   Open   High    Low  Close    Volume
0     VCB  01/07/2025  None  57200  58800  57100  58200  10049500
1     VCB  02/07/2025  None  58300  58600  57700  58000   2913600
2     VCB  03/07/2025  None  58100  58800  57700  57900   7395300
3     VCB  04/07/2025  None  57900  58800  57800  58400   4849800
4     VCB  07/07/2025  None  58500  58900  58200  58600   8056200
5     VCB  08/07/2025  None  58800  59500  58600  59000  10394500
6     VCB  09/07/2025  None  59400  61800  59400  61500  16449700
7     VCB  10/07/2025  None  61800  61800  61000  61400   8152900
8     VCB  11/07/2025  None  61500  63100  61500  62700  12701900
9     VCB  14/07/2025  None  62900  62900  61000  62400   6475000
10    VCB  15/07/2025  None  62400  62600  61400  61400   6315400
11    VCB  16/07/2025  None  61400  62100  61100  61800   7603200
12    VCB  17/07/2025  None  61800  62700  61800  62200   9992700
13    VCB  18/07/2025  None  62300  62600  61800  61900   6915300
14    VCB  21/07/2025  None  62200  62700  61300  61300   6138200
15    VCB  22/07/2025  None  61300  62200  60900  62200   4902600
16    VCB  23/07/2025  None  62500  62600  61800  62100   5087300
17    VCB  24/07/2025  None  62200  63500  61900  62100   8710200
18    VCB  25/07/2025  None  62100  62500  61900  62000   4978400
19    VCB  28/07/2025  None  62200  63000  62100  62800  10484700
20    VCB  29/07/2025  None  63200  63200  61000  61000  10595600