# Kiem tra ket noi MT5 thanh cong khong

In [1]:
import MetaTrader5 as mt5
# display data on the MetaTrader 5 package
print("MetaTrader5 package author: ",mt5.__author__)
print("MetaTrader5 package version: ",mt5.__version__)
 
# establish MetaTrader 5 connection to a specified trading account
if not mt5.initialize(login=6338576, server="OANDA-Demo-1",password="123456Qaz1!"):
    print("initialize() failed, error code =",mt5.last_error())
    quit()
 
# display data on connection status, server name and trading account
print(mt5.terminal_info())
# display data on MetaTrader 5 version
print(mt5.version())
 
# shut down connection to the MetaTrader 5 terminal
mt5.shutdown()

MetaTrader5 package author:  MetaQuotes Ltd.
MetaTrader5 package version:  5.0.5200
TerminalInfo(community_account=False, community_connection=False, connected=True, dlls_allowed=False, trade_allowed=True, tradeapi_disabled=False, email_enabled=False, ftp_enabled=False, notifications_enabled=False, mqid=True, build=5370, maxbars=100000, codepage=0, ping_last=238959, community_balance=0.0, retransmission=0.0, company='OANDA Corporation', name='OANDA MetaTrader 5', language='English', path='C:\\Program Files\\OANDA MetaTrader 5', data_path='C:\\Users\\TGC\\AppData\\Roaming\\MetaQuotes\\Terminal\\EE0304F13905552AE0B5EAEFB04866EB', commondata_path='C:\\Users\\TGC\\AppData\\Roaming\\MetaQuotes\\Terminal\\Common')
(500, 5370, '17 Oct 2025')

True

In [ ]:
from datetime import datetime
import MetaTrader5 as mt5

# Khoi tao ket noi den MT5
if not mt5.initialize(): # Khong thanh cong
    print("initialize() failed, error code =",mt5.last_error())
    quit()

# Lay so du tai khoan

In [ ]:
import MetaTrader5 as mt5
import pandas as pd
# display data on the MetaTrader 5 package
print("MetaTrader5 package author: ",mt5.__author__)
print("MetaTrader5 package version: ",mt5.__version__)
 
# establish connection to the MetaTrader 5 terminal
if not mt5.initialize(login=6338576, server="OANDA-Demo-1",password="123456Qaz1!"):
    print("initialize() failed, error code =",mt5.last_error())
    quit()

account_info=mt5.account_info()
print(account_info)

In [ ]:
import MetaTrader5 as mt5
import pandas as pd
# display data on the MetaTrader 5 package
print("MetaTrader5 package author: ",mt5.__author__)
print("MetaTrader5 package version: ",mt5.__version__)
 
# establish connection to the MetaTrader 5 terminal
if not mt5.initialize(login=6338576, server="OANDA-Demo-1",password="123456Qaz1!"):
    print("initialize() failed, error code =",mt5.last_error())
    quit()
 
account_info=mt5.account_info()
    
# display trading account data in the form of a dictionary
print("Show account_info()._asdict():")
account_info_dict = mt5.account_info()._asdict()

# convert the dictionary into DataFrame and print
df=pd.DataFrame(list(account_info_dict.items()),columns=['property','value'])
print("account_info() as dataframe:")
print(df)
 
# shut down connection to the MetaTrader 5 terminal
mt5.shutdown()

# Viet vao ham

In [2]:
def get_account_info():
	import MetaTrader5 as mt5
	import pandas as pd
	# display data on the MetaTrader 5 package
	# print("MetaTrader5 package author: ",mt5.__author__)
	# print("MetaTrader5 package version: ",mt5.__version__)
	
	# establish connection to the MetaTrader 5 terminal
	if not mt5.initialize(login=6338576, server="OANDA-Demo-1",password="123456Qaz1!"):
		print("initialize() failed, error code =",mt5.last_error())
		quit()
	
	account_info=mt5.account_info()
		
	# display trading account data in the form of a dictionary
	# print("Show account_info()._asdict():")
	account_info_dict = mt5.account_info()._asdict()

	# convert the dictionary into DataFrame and print
	df=pd.DataFrame(list(account_info_dict.items()),columns=['property','value'])
	# print("account_info() as dataframe:")
	# print(df)
	
	# shut down connection to the MetaTrader 5 terminal
	mt5.shutdown()

	return df

# Goi ham

In [ ]:
get_account_info()

# Lay du lieu

In [ ]:
# Su dung ham cua MT5
from datetime import datetime
import MetaTrader5 as mt5
# display data on the MetaTrader 5 package
# print("MetaTrader5 package author: ",mt5.__author__)
# print("MetaTrader5 package version: ",mt5.__version__)
 
# import the 'pandas' module for displaying data obtained in the tabular form
import pandas as pd
pd.set_option('display.max_columns', 500) # number of columns to be displayed
pd.set_option('display.width', 1500)      # max table width to display
 
# establish connection to MetaTrader 5 terminal
if not mt5.initialize(login=6338576, server="OANDA-Demo-1",password="123456Qaz1!"):
    print("initialize() failed, error code =",mt5.last_error())
    quit()
 
# get 10 GBPUSD D1 bars from the current day
rates = mt5.copy_rates_from_pos("GBPUSD.sml", mt5.TIMEFRAME_M1, 0, 100)
 
# shut down connection to the MetaTrader 5 terminal
mt5.shutdown()
# display each element of obtained data in a new line
# print("Display obtained data 'as is'")
# for rate in rates:
#     print(rate)
 
# create DataFrame out of the obtained data
rates_frame = pd.DataFrame(rates)
# convert time in seconds into the datetime format
rates_frame['time']=pd.to_datetime(rates_frame['time'], unit='s')
 
# display data
# print("\nDisplay dataframe with data")
print(rates_frame)

# Viet lai ham

In [ ]:
def getData_From_MT5_Pos(symbol, timeframe, index, nrows=100):
	# Su dung ham cua MT5
	from datetime import datetime
	import MetaTrader5 as mt5
	# display data on the MetaTrader 5 package
	# print("MetaTrader5 package author: ",mt5.__author__)
	# print("MetaTrader5 package version: ",mt5.__version__)
	
	# import the 'pandas' module for displaying data obtained in the tabular form
	import pandas as pd
	pd.set_option('display.max_columns', 500) # number of columns to be displayed
	pd.set_option('display.width', 1500)      # max table width to display
	
	# establish connection to MetaTrader 5 terminal
	if not mt5.initialize(login=6338576, server="OANDA-Demo-1",password="123456Qaz1!"):
		print("initialize() failed, error code =",mt5.last_error())
		quit()
	
	# get 10 GBPUSD D1 bars from the current day
	rates = mt5.copy_rates_from_pos(symbol, timeframe, index, nrows)
	
	# shut down connection to the MetaTrader 5 terminal
	mt5.shutdown()
	# display each element of obtained data in a new line
	# print("Display obtained data 'as is'")
	# for rate in rates:
	#     print(rate)
	
	# create DataFrame out of the obtained data
	rates_frame = pd.DataFrame(rates)
	# convert time in seconds into the datetime format
	rates_frame['time']=pd.to_datetime(rates_frame['time'], unit='s')
	# rename columns
	rates_frame.rename(columns={'time':'Datetime', 'open':'Open', 'high':'High', 'low':'Low', 'close':'Close', 'tick_volume':'Volume', 'spread':'Spread', 'real_volume':'RealVolume'}, inplace=True)
	# Chi lay cac cot can thiet
	rates_frame = rates_frame[['Datetime', 'Open', 'High', 'Low', 'Close', 'Volume']]
	
	# display data
	# print("\nDisplay dataframe with data")
	# print(rates_frame) 
	return rates_frame

In [ ]:
# Goi ham
import MetaTrader5 as mt5
symbol = "GBPUSD.sml"
timeframe = mt5.TIMEFRAME_M1
index = 0
# nrows = 50
getData_From_MT5_Pos(symbol, timeframe, index)

# Tinh toan chi bao, su dung thu vien talib

In [24]:
import talib
# Goi ham
import MetaTrader5 as mt5
symbol = "GBPUSD.sml"
timeframe = mt5.TIMEFRAME_M1
index = 0
# nrows = 50
data = getData_From_MT5_Pos(symbol, timeframe, index)

In [25]:
# Chien luoc MA10 > MA20 thi Buy, MA10 < MA20 thi Sell
data['MA10'] = talib.SMA(data['Close'], timeperiod=10)
data['MA20'] = talib.SMA(data['Close'], timeperiod=20)
data['RSI'] = talib.RSI(data['Close'], timeperiod=14)

# data.to_csv('dataCheck.csv', index=False)
data

              Datetime     Open     High      Low    Close  Volume      MA10      MA20        RSI
0  2025-09-19 15:32:00  1.34672  1.34686  1.34653  1.34686     273       NaN       NaN        NaN
1  2025-09-19 15:33:00  1.34687  1.34688  1.34666  1.34676     224       NaN       NaN        NaN
2  2025-09-19 15:34:00  1.34675  1.34687  1.34663  1.34666     178       NaN       NaN        NaN
3  2025-09-19 15:35:00  1.34666  1.34682  1.34663  1.34676     142       NaN       NaN        NaN
4  2025-09-19 15:36:00  1.34677  1.34682  1.34665  1.34673     177       NaN       NaN        NaN
..                 ...      ...      ...      ...      ...     ...       ...       ...        ...
95 2025-09-19 17:07:00  1.34943  1.34958  1.34928  1.34929     274  1.349146  1.349195  55.402332
96 2025-09-19 17:08:00  1.34929  1.34974  1.34929  1.34957     339  1.349198  1.349211  61.091196
97 2025-09-19 17:09:00  1.34956  1.34958  1.34925  1.34936     302  1.349239  1.349219  55.384943
98 2025-09-19 17:10:00  1.34937  1.34939  1.34904  1.34926     326  1.349258  1.349218  52.853259
99 2025-09-19 17:11:00  1.34926  1.34927  1.34908  1.34916     142  1.349248  1.349212  50.373526

[100 rows x 9 columns]

In [26]:
import numpy as np
data['Buy_Signal'] = (data['MA10'] > data['MA20'])
data['Sell_Signal'] = (data['MA10'] < data['MA20'])
data

              Datetime     Open     High      Low    Close  Volume      MA10      MA20        RSI  Buy_Signal  Sell_Signal
0  2025-09-19 15:32:00  1.34672  1.34686  1.34653  1.34686     273       NaN       NaN        NaN       False        False
1  2025-09-19 15:33:00  1.34687  1.34688  1.34666  1.34676     224       NaN       NaN        NaN       False        False
2  2025-09-19 15:34:00  1.34675  1.34687  1.34663  1.34666     178       NaN       NaN        NaN       False        False
3  2025-09-19 15:35:00  1.34666  1.34682  1.34663  1.34676     142       NaN       NaN        NaN       False        False
4  2025-09-19 15:36:00  1.34677  1.34682  1.34665  1.34673     177       NaN       NaN        NaN       False        False
..                 ...      ...      ...      ...      ...     ...       ...       ...        ...         ...          ...
95 2025-09-19 17:07:00  1.34943  1.34958  1.34928  1.34929     274  1.349146  1.349195  55.402332       False         True
96 2025-09-19 17:08:00  1.34929  1.34974  1.34929  1.34957     339  1.349198  1.349211  61.091196       False         True
97 2025-09-19 17:09:00  1.34956  1.34958  1.34925  1.34936     302  1.349239  1.349219  55.384943        True        False
98 2025-09-19 17:10:00  1.34937  1.34939  1.34904  1.34926     326  1.349258  1.349218  52.853259        True        False
99 2025-09-19 17:11:00  1.34926  1.34927  1.34908  1.34916     142  1.349248  1.349212  50.373526        True        False

[100 rows x 11 columns]

In [41]:
import MetaTrader5 as mt5
# display data on the MetaTrader 5 package
# print("MetaTrader5 package author: ",mt5.__author__)
# print("MetaTrader5 package version: ",mt5.__version__)
 
# establish connection to the MetaTrader 5 terminal
if not mt5.initialize():
    print("initialize() failed, error code =",mt5.last_error())
    quit()
 
# attempt to enable the display of the GBPUSD in MarketWatch
selected=mt5.symbol_select("GBPUSD.sml",True)
if not selected:
    print("Failed to select GBPUSD")
    mt5.shutdown()
    quit()
 
# display the last GBPUSD tick
lasttick=mt5.symbol_info_tick("GBPUSD.sml")
print(lasttick)
# display tick field values in the form of a list
print("Show symbol_info_tick(\"GBPUSD.sml\")._asdict():")
symbol_info_tick_dict = mt5.symbol_info_tick("GBPUSD.sml")._asdict()
for prop in symbol_info_tick_dict:
    print("  {}={}".format(prop, symbol_info_tick_dict[prop]))
 
# shut down connection to the MetaTrader 5 terminal
mt5.shutdown()

Tick(time=1758302783, bid=1.34936, ask=1.34948, last=1.34942, volume=0, time_msc=1758302783930, flags=1026, volume_real=0.0)
Show symbol_info_tick("GBPUSD.sml")._asdict():
  time=1758302783
  bid=1.34936
  ask=1.34948
  last=1.34942
  volume=0
  time_msc=1758302783930
  flags=1026
  volume_real=0.0

True

# Neu thanh cong thi chay tiep de lay du lieu

In [ ]:
utc_from = datetime(2020, 1, 10)
utc_to = datetime(2020, 1, 11)

# Lay du lieu
rates = mt5.copy_rates_range("US30", mt5.TIMEFRAME_D1, utc_from, utc_to)

In [ ]:
print(rates)

In [ ]:
print(type(rates))

# Parse kieu du lieu tu ... thanh dataframe

In [ ]:
import pandas as pd

rateDataFrame = pd.DataFrame(rates)
rateDataFrame

In [ ]:
# Parse time thanh datetime 

rateDataFrame['time'] = pd.to_datetime(rateDataFrame['time'], unit='s') # Timestamp thanh Datetime

rateDataFrame