In [1]:
import math # Thu vien nam trong (built-in) python
import talib

In [ ]:
# ! pip install matplotlib
! pip install numpy

# Vi du tao dataframe tu dictionary

In [ ]:
# Khai bao 1 dict
thisdict = { # Co 2 phan tu: key va value
    'apples': [1,2,3],
    'oranges': [2,3,4]
}

print(type(thisdict))
print(thisdict)

# Chuyen tu Dictionary sang Dataframe

In [ ]:
import pandas as pd # as tuc la alias, tuc la ta co the su dung pd thay cho pandas

dataFrame = pd.DataFrame(thisdict)
print(dataFrame)
dataFrame

# Xuat ra csv

# Xuat ra du lieu

In [ ]:
import pandas as pd

dataFrame = pd.DataFrame(thisdict)
print(dataFrame)
dataFrame.to_csv('dataFrame.csv')
dataFrame.to_excel('dataFrame.xlsx')
dataFrame.to_json('dataFrame.json')
dataFrame.to_html('dataFrame.html')

In [ ]:
from fpdf import FPDF
from tabulate import tabulate

pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=10)

table = tabulate(dataFrame.values, headers=dataFrame.columns, tablefmt="grid")
for row in table.split('\n'):
    pdf.cell(0, 5, row, ln=1)
pdf.output("dataFrame.pdf")

In [ ]:
import pandas as pd
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from reportlab.lib import colors

# Giả sử bạn đã có DataFrame tên là dataFrame
dataFrame = pd.DataFrame({
    'Tên': ['A', 'B', 'C'],
    'Tuổi': [23, 34, 45],
    'Điểm': [8.5, 7.0, 9.0]
})

pdf_file = "dataFrame1.pdf"
doc = SimpleDocTemplate(pdf_file, pagesize=landscape(letter))

# Chuyển DataFrame thành list cho Table
data = [dataFrame.columns.to_list()] + dataFrame.values.tolist()

# Tạo bảng
table = Table(data)
style = TableStyle([
    ('BACKGROUND', (0,0), (-1,0), colors.grey),
    ('TEXTCOLOR',(0,0),(-1,0),colors.whitesmoke),
    ('ALIGN',(0,0),(-1,-1),'CENTER'),
    ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
    ('BOTTOMPADDING', (0,0), (-1,0), 12),
    ('BACKGROUND',(0,1),(-1,-1),colors.beige),
    ('GRID', (0,0), (-1,-1), 1, colors.black),
])
table.setStyle(style)

elements = [table]
doc.build(elements)
print("Đã xuất ra file PDF đẹp:", pdf_file)

In [ ]:
import pandas as pd
# List of dictionary to dataframe
list_of_dicts = [ {'apples': 1, 'oranges': 2},{'apples': 2, 'oranges': 3}, {'apples': 3, 'oranges': 4} ]

print(type(list_of_dicts)) # <class 'dict'>

dataFrame = pd.DataFrame(list_of_dicts)
dataFrame

In [ ]:
print(type(thisdict)) # Dung ham type() de kiem tra kieu du lieu
print(thisdict['apples']) # Lay ra phan tu co key = 'apples'
print(thisdict)

# Chuyen dictionary thanh Dataframe

In [ ]:
import pandas as pd # Thu vien https://pandas.pydata.org/pandas-docs/stable/getting_started/overview.html
dataFrame = pd.DataFrame(thisdict)

print("Dict la", thisdict)
print("DataFrame la", dataFrame)

In [ ]:
print(type(dataFrame))

In [ ]:
dataFrame

# Lay du lieu tu file: excel, csv, API San: MT5, Crypto, Chung khoan

Lay du lieu tu CSV

In [45]:
import pandas as pd # Khai bao thu vien pandas
# ! pip install pandas

dataCSV = pd.read_csv('data/data.csv') # Thuoc tinh read_csv de doc file csv
dataCSV

,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal
0,2023-09-05,89100.0,90700.0,89100.0,90100.0,2013202,NaN,90100.000000,90100.000000,0.000000,0.000000,NaN,False
1,2023-09-06,90200.0,90200.0,89700.0,90200.0,2057603,NaN,90115.384615,90107.407407,7.977208,1.595442,False,False
2,2023-09-07,90000.0,90800.0,89500.0,89500.0,1958302,NaN,90020.710059,90062.414266,-41.704207,-7.064488,False,False
3,2023-09-08,89500.0,89500.0,89100.0,89500.0,1381905,NaN,89940.600819,90020.753950,-80.153131,-21.682217,False,False
4,2023-09-11,89600.0,90000.0,88000.0,88500.0,2592500,NaN,89718.969924,89908.105509,-189.135585,-55.172890,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2023-12-20,81200.0,81300.0,80500.0,81100.0,2014300,84510.0,83235.492267,84495.439681,-1259.947415,-835.252482,False,True
76,2023-12-21,81000.0,81000.0,80300.0,80900.0,2148400,84220.0,82876.185764,84229.110816,-1352.925052,-938.786996,False,True
77,2023-12-22,80900.0,81100.0,80400.0,80900.0,1721800,83990.0,82572.157185,83982.510015,-1410.352830,-1033.100163,False,True
78,2023-12-25,80900.0,81800.0,80700.0,81800.0,1480000,83780.0,82453.363772,83820.842606,-1367.478834,-1099.975897,False,True
79,2023-12-26,82000.0,82800.0,82000.0,82800.0,1113200,83630.0,82506.692422,83745.224636,-1238.532213,-1127.687160,False,True

In [16]:
import pandas as pd # Khai bao thu vien pandas
# ! pip install pandas

dataExcel = pd.read_excel('data/dataCSV_2025.05.24.xlsx') # Thuoc tinh read_csv de doc file csv
dataExcel

,Unnamed: 0,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal
0,0,2023-09-05,89100,90700,89100,90100,2013202,NaN,90100.000000,90100.000000,0.000000,0.000000,NaN,False
1,1,2023-09-06,90200,90200,89700,90200,2057603,NaN,90115.384615,90107.407407,7.977208,1.595442,0.0,False
2,2,2023-09-07,90000,90800,89500,89500,1958302,NaN,90020.710059,90062.414266,-41.704207,-7.064488,0.0,False
3,3,2023-09-08,89500,89500,89100,89500,1381905,NaN,89940.600819,90020.753950,-80.153131,-21.682217,0.0,False
4,4,2023-09-11,89600,90000,88000,88500,2592500,NaN,89718.969924,89908.105509,-189.135585,-55.172890,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,75,2023-12-20,81200,81300,80500,81100,2014300,84510.0,83235.492267,84495.439681,-1259.947415,-835.252482,0.0,True
76,76,2023-12-21,81000,81000,80300,80900,2148400,84220.0,82876.185764,84229.110816,-1352.925052,-938.786996,0.0,True
77,77,2023-12-22,80900,81100,80400,80900,1721800,83990.0,82572.157185,83982.510015,-1410.352830,-1033.100163,0.0,True
78,78,2023-12-25,80900,81800,80700,81800,1480000,83780.0,82453.363772,83820.842606,-1367.478834,-1099.975897,0.0,True
79,79,2023-12-26,82000,82800,82000,82800,1113200,83630.0,82506.692422,83745.224636,-1238.532213,-1127.687160,0.0,True

In [17]:
dataCSV

,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal
0,2023-09-05,89100.0,90700.0,89100.0,90100.0,2013202,NaN,90100.000000,90100.000000,0.000000,0.000000,NaN,False
1,2023-09-06,90200.0,90200.0,89700.0,90200.0,2057603,NaN,90115.384615,90107.407407,7.977208,1.595442,False,False
2,2023-09-07,90000.0,90800.0,89500.0,89500.0,1958302,NaN,90020.710059,90062.414266,-41.704207,-7.064488,False,False
3,2023-09-08,89500.0,89500.0,89100.0,89500.0,1381905,NaN,89940.600819,90020.753950,-80.153131,-21.682217,False,False
4,2023-09-11,89600.0,90000.0,88000.0,88500.0,2592500,NaN,89718.969924,89908.105509,-189.135585,-55.172890,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2023-12-20,81200.0,81300.0,80500.0,81100.0,2014300,84510.0,83235.492267,84495.439681,-1259.947415,-835.252482,False,True
76,2023-12-21,81000.0,81000.0,80300.0,80900.0,2148400,84220.0,82876.185764,84229.110816,-1352.925052,-938.786996,False,True
77,2023-12-22,80900.0,81100.0,80400.0,80900.0,1721800,83990.0,82572.157185,83982.510015,-1410.352830,-1033.100163,False,True
78,2023-12-25,80900.0,81800.0,80700.0,81800.0,1480000,83780.0,82453.363772,83820.842606,-1367.478834,-1099.975897,False,True
79,2023-12-26,82000.0,82800.0,82000.0,82800.0,1113200,83630.0,82506.692422,83745.224636,-1238.532213,-1127.687160,False,True

In [19]:
# print(dataCSV.head()) # Ham head() de xem 5 dong dau tien cua file csv
print(dataCSV.tail()) # Ham tail() de xem 5 dong cuoi cung cua file csv

      Datetime     Open     High      Low    Close   Volume      SMA  \
75  2023-12-20  81200.0  81300.0  80500.0  81100.0  2014300  84510.0
76  2023-12-21  81000.0  81000.0  80300.0  80900.0  2148400  84220.0
77  2023-12-22  80900.0  81100.0  80400.0  80900.0  1721800  83990.0
78  2023-12-25  80900.0  81800.0  80700.0  81800.0  1480000  83780.0
79  2023-12-26  82000.0  82800.0  82000.0  82800.0  1113200  83630.0

       short_ema      long_ema         MACD  Signal_Line Buy_Signal  \
75  83235.492267  84495.439681 -1259.947415  -835.252482      False
76  82876.185764  84229.110816 -1352.925052  -938.786996      False
77  82572.157185  83982.510015 -1410.352830 -1033.100163      False
78  82453.363772  83820.842606 -1367.478834 -1099.975897      False
79  82506.692422  83745.224636 -1238.532213 -1127.687160      False

    Sell_Signal
75         True
76         True
77         True
78         True
79         True

In [20]:
print(dataCSV.info()) # Ham info() de xem thong tin cua file csv

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Datetime     80 non-null     object
 1   Open         80 non-null     float64
 2   High         80 non-null     float64
 3   Low          80 non-null     float64
 4   Close        80 non-null     float64
 5   Volume       80 non-null     int64
 6   SMA          61 non-null     float64
 7   short_ema    80 non-null     float64
 8   long_ema     80 non-null     float64
 9   MACD         80 non-null     float64
 10  Signal_Line  80 non-null     float64
 11  Buy_Signal   79 non-null     object
 12  Sell_Signal  80 non-null     bool
dtypes: bool(1), float64(9), int64(1), object(2)
memory usage: 7.7+ KB
None

In [21]:
dataCSV.shape # Ham shape() de xem kich thuoc cua file csv

(80, 13)

In [22]:
dataCSV.describe() # Ham describe() de xem thong tin thong ke cua file csv
dataCSV.columns # Ham columns() de xem cac cot cua file csv
dataCSV.index # Ham index() de xem cac dong cua file csv

dataCSV.dtypes # Ham dtypes() de xem kieu du lieu cua cac cot cua file csv

Datetime        object
Open           float64
High           float64
Low            float64
Close          float64
Volume           int64
SMA            float64
short_ema      float64
long_ema       float64
MACD           float64
Signal_Line    float64
Buy_Signal      object
Sell_Signal       bool
dtype: object

In [23]:
dataCSV.isnull() # Ham isnull() de xem co null hay khong

,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal
0,False,False,False,False,False,False,True,False,False,False,False,True,False
1,False,False,False,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,False,False,False,False,False,False,False,False,False,False,False,False,False
76,False,False,False,False,False,False,False,False,False,False,False,False,False
77,False,False,False,False,False,False,False,False,False,False,False,False,False
78,False,False,False,False,False,False,False,False,False,False,False,False,False
79,False,False,False,False,False,False,False,False,False,False,False,False,False

Lay tu Excel

In [ ]:
dataExcel = pd.read_excel('dataCSVAfter.xlsx') # Thuoc tinh read_excel
dataExcel

# Doc excel

In [ ]:
# Ngoai ra thi chung ta co the dung try..except de xu ly loi ngoai le
import pandas as pd
try:
	dataExcel = pd.read_excel('dataCSVAfter .xlsx') # Thuoc tinh read_excel
	print(dataExcel)
except Exception as e:
	print("Error: ", e)

# Muon lay 5 record dau

In [ ]:
dataCSV.head(10)

# Biet thong tin cua dataframe

In [ ]:
dataCSV.info() # Ham nay cho ta biet thong tin ve cac cot trong dataCSV

In [ ]:
dataExcel.info() # Ham nay cho ta biet thong tin ve cac cot trong dataExcel

# Luu dataFrame xuong o dia

In [ ]:
dataCSV.to_csv('dataCSV_2025.05.24.csv')
dataCSV.to_excel('dataCSV_2025.05.24.xlsx')

In [ ]:
dataCSV.describe() # Mo ta biet thong tin ve cac cot trong dataCSV

# Thong tin

In [ ]:
# show shape of data, index and columns
print('- shape:', dataCSV.shape) # Shape cho ta biet kich thuoc cua dataCSV
print('- index:', dataCSV.index)
print('- columns:', dataCSV.columns)

In [24]:
dataCSV

,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal
0,2023-09-05,89100.0,90700.0,89100.0,90100.0,2013202,NaN,90100.000000,90100.000000,0.000000,0.000000,NaN,False
1,2023-09-06,90200.0,90200.0,89700.0,90200.0,2057603,NaN,90115.384615,90107.407407,7.977208,1.595442,False,False
2,2023-09-07,90000.0,90800.0,89500.0,89500.0,1958302,NaN,90020.710059,90062.414266,-41.704207,-7.064488,False,False
3,2023-09-08,89500.0,89500.0,89100.0,89500.0,1381905,NaN,89940.600819,90020.753950,-80.153131,-21.682217,False,False
4,2023-09-11,89600.0,90000.0,88000.0,88500.0,2592500,NaN,89718.969924,89908.105509,-189.135585,-55.172890,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2023-12-20,81200.0,81300.0,80500.0,81100.0,2014300,84510.0,83235.492267,84495.439681,-1259.947415,-835.252482,False,True
76,2023-12-21,81000.0,81000.0,80300.0,80900.0,2148400,84220.0,82876.185764,84229.110816,-1352.925052,-938.786996,False,True
77,2023-12-22,80900.0,81100.0,80400.0,80900.0,1721800,83990.0,82572.157185,83982.510015,-1410.352830,-1033.100163,False,True
78,2023-12-25,80900.0,81800.0,80700.0,81800.0,1480000,83780.0,82453.363772,83820.842606,-1367.478834,-1099.975897,False,True
79,2023-12-26,82000.0,82800.0,82000.0,82800.0,1113200,83630.0,82506.692422,83745.224636,-1238.532213,-1127.687160,False,True

# Lay gia tri 1 cot ra

In [25]:
volume = dataCSV['Volume'] # Lay gia tri cot Volume ra
print(volume)

0     2013202
1     2057603
2     1958302
3     1381905
4     2592500
       ...
75    2014300
76    2148400
77    1721800
78    1480000
79    1113200
Name: Volume, Length: 80, dtype: int64

# Lay nguyen 1 dong ra

In [ ]:
# dataCSV.iloc[0] # first row
dataCSV.iloc[2] # Iloc la index location, dong 3

Datetime         2023-09-07
Open                90000.0
High                90800.0
Low                 89500.0
Close               89500.0
Volume              1958302
SMA                     NaN
short_ema      90020.710059
long_ema       90062.414266
MACD             -41.704207
Signal_Line       -7.064488
Buy_Signal            False
Sell_Signal           False
Name: 2, dtype: object

In [27]:
dataCSV.iloc[2, 12] # Iloc la index location, 2 la dong, 0 la cot

False

In [28]:
dataCSV.iloc[2, 1] # Iloc la index location, 2 la dong, 0 la cot

90000.0

In [30]:
dataCSV.iloc[2, 0:3] # Iloc la index location, 2 la dong, 0:3 la cot
dataCSV.iloc[2, 0:5] # Iloc la index location, 2 la dong, 0:3 la cot

Datetime    2023-09-07
Open           90000.0
High           90800.0
Low            89500.0
Close          89500.0
Name: 2, dtype: object

In [31]:
dataCSV.iloc[79] # Lay 1 dong thu 2 - hay la dong co index = 1

Datetime         2023-12-26
Open                82000.0
High                82800.0
Low                 82000.0
Close               82800.0
Volume              1113200
SMA                 83630.0
short_ema      82506.692422
long_ema       83745.224636
MACD           -1238.532213
Signal_Line     -1127.68716
Buy_Signal            False
Sell_Signal            True
Name: 79, dtype: object

# Lay dong cuoi cung

In [32]:
dataCSV.iloc[-1] # Bat cu kieu du lieu nao cung co the lay duoc -1 la dong cuoi cung

Datetime         2023-12-26
Open                82000.0
High                82800.0
Low                 82000.0
Close               82800.0
Volume              1113200
SMA                 83630.0
short_ema      82506.692422
long_ema       83745.224636
MACD           -1238.532213
Signal_Line     -1127.68716
Buy_Signal            False
Sell_Signal            True
Name: 79, dtype: object

In [ ]:
dataCSV.iloc[79]

In [ ]:
dataCSV.iloc[77:79] # Hang index 77 cho den truoc hang thu 79

In [ ]:
dataCSV.loc[78, 'Open'] # row thu 78, column Open

In [ ]:
dataCSV.iloc[78, 1] # row thu 78, column Open

In [ ]:
dataCSV.iloc[78, 2] # row 78, column 1

# Tinh toan Buy, Sell

Filter

In [33]:
dataCSV

,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal
0,2023-09-05,89100.0,90700.0,89100.0,90100.0,2013202,NaN,90100.000000,90100.000000,0.000000,0.000000,NaN,False
1,2023-09-06,90200.0,90200.0,89700.0,90200.0,2057603,NaN,90115.384615,90107.407407,7.977208,1.595442,False,False
2,2023-09-07,90000.0,90800.0,89500.0,89500.0,1958302,NaN,90020.710059,90062.414266,-41.704207,-7.064488,False,False
3,2023-09-08,89500.0,89500.0,89100.0,89500.0,1381905,NaN,89940.600819,90020.753950,-80.153131,-21.682217,False,False
4,2023-09-11,89600.0,90000.0,88000.0,88500.0,2592500,NaN,89718.969924,89908.105509,-189.135585,-55.172890,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2023-12-20,81200.0,81300.0,80500.0,81100.0,2014300,84510.0,83235.492267,84495.439681,-1259.947415,-835.252482,False,True
76,2023-12-21,81000.0,81000.0,80300.0,80900.0,2148400,84220.0,82876.185764,84229.110816,-1352.925052,-938.786996,False,True
77,2023-12-22,80900.0,81100.0,80400.0,80900.0,1721800,83990.0,82572.157185,83982.510015,-1410.352830,-1033.100163,False,True
78,2023-12-25,80900.0,81800.0,80700.0,81800.0,1480000,83780.0,82453.363772,83820.842606,-1367.478834,-1099.975897,False,True
79,2023-12-26,82000.0,82800.0,82000.0,82800.0,1113200,83630.0,82506.692422,83745.224636,-1238.532213,-1127.687160,False,True

In [37]:
dataCSV.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Datetime     80 non-null     object
 1   Open         80 non-null     float64
 2   High         80 non-null     float64
 3   Low          80 non-null     float64
 4   Close        80 non-null     float64
 5   Volume       80 non-null     int64
 6   SMA          61 non-null     float64
 7   short_ema    80 non-null     float64
 8   long_ema     80 non-null     float64
 9   MACD         80 non-null     float64
 10  Signal_Line  80 non-null     float64
 11  Buy_Signal   79 non-null     object
 12  Sell_Signal  80 non-null     bool
dtypes: bool(1), float64(9), int64(1), object(2)
memory usage: 7.7+ KB

In [41]:
# Filter nhung Volume > 1,000,000
dieukien = ( dataCSV['Sell_Signal'] == False ) # Loc ra nhung dong co Volume > 1000000
dataCSV[dieukien] # Loc ra nhung phan tu co Volume > 1000000

,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal
0,2023-09-05,89100.0,90700.0,89100.0,90100.0,2013202,NaN,90100.000000,90100.000000,0.000000,0.000000,NaN,False
1,2023-09-06,90200.0,90200.0,89700.0,90200.0,2057603,NaN,90115.384615,90107.407407,7.977208,1.595442,False,False
2,2023-09-07,90000.0,90800.0,89500.0,89500.0,1958302,NaN,90020.710059,90062.414266,-41.704207,-7.064488,False,False
3,2023-09-08,89500.0,89500.0,89100.0,89500.0,1381905,NaN,89940.600819,90020.753950,-80.153131,-21.682217,False,False
4,2023-09-11,89600.0,90000.0,88000.0,88500.0,2592500,NaN,89718.969924,89908.105509,-189.135585,-55.172890,False,False
5,2023-09-12,89000.0,90000.0,88900.0,89900.0,1612100,NaN,89746.820705,89907.505101,-160.684396,-76.275192,False,False
6,2023-09-13,90000.0,90000.0,88900.0,89100.0,1675000,NaN,89647.309827,89847.689909,-200.380081,-101.096170,False,False
7,2023-09-14,89000.0,89500.0,88100.0,89100.0,1552600,NaN,89563.108315,89792.305471,-229.197156,-126.716367,False,False
8,2023-09-15,88900.0,89800.0,88600.0,89800.0,2235400,NaN,89599.553190,89792.875436,-193.322246,-140.037543,False,False
9,2023-09-18,89500.0,89700.0,88300.0,88800.0,789102,NaN,89476.545007,89719.329107,-242.784101,-160.586854,False,False
10,2023-09-19,88800.0,89200.0,86000.0,88100.0,1210203,NaN,89264.768852,89599.378803,-334.609951,-195.391474,False,False
11,2023-09-20,88100.0,88400.0,86400.0,88000.0,1057027,NaN,89070.189029,89480.906299,-410.717271,-238.456633,False,False
12,2023-09-21,88000.0,88000.0,86800.0,87000.0,1359910,NaN,88751.698409,89297.135462,-545.437053,-299.852717,False,False
13,2023-09-22,86400.0,89500.0,86000.0,89300.0,2679610,NaN,88836.052500,89297.347650,-461.295150,-332.141204,False,False
14,2023-09-25,89000.0,89500.0,88300.0,89300.0,2303421,NaN,88907.429038,89297.544121,-390.115082,-343.735979,False,False
15,2023-09-26,89200.0,89400.0,86900.0,87000.0,1663215,NaN,88613.978417,89127.355667,-513.377250,-377.664234,False,False
16,2023-09-27,87600.0,89000.0,87000.0,87800.0,1368902,NaN,88488.750968,89029.033025,-540.282057,-410.187798,False,False
17,2023-09-28,87200.0,88300.0,86600.0,88000.0,1065102,NaN,88413.558512,88952.808357,-539.249845,-436.000208,False,False
18,2023-09-29,88300.0,88300.0,87100.0,87500.0,613316,NaN,88273.011048,88845.192923,-572.181875,-463.236541,False,False
28,2023-10-13,86000.0,86600.0,85500.0,86600.0,788100,86980.0,86392.777336,87266.960667,-874.183331,-913.222270,False,False
29,2023-10-16,85600.0,86600.0,85600.0,86100.0,551300,86845.0,86347.734669,87180.519137,-832.784468,-897.134709,False,False
30,2023-10-17,86100.0,86500.0,85500.0,85900.0,488400,86735.0,86278.852412,87085.665867,-806.813455,-879.070459,False,False
31,2023-10-18,85500.0,86000.0,85000.0,85900.0,1266400,86630.0,86220.567426,86997.838766,-777.271340,-858.710635,False,False
32,2023-10-19,85500.0,86000.0,84100.0,84500.0,1408600,86505.0,85955.864745,86812.813672,-856.948927,-858.358293,False,False
35,2023-10-24,84500.0,86500.0,83900.0,86000.0,994000,85990.0,85645.815191,86466.149145,-820.333954,-864.436588,True,False
36,2023-10-25,85100.0,85800.0,84600.0,85800.0,924100,85890.0,85669.535931,86416.804764,-747.268833,-841.003037,False,False
37,2023-10-26,85000.0,86000.0,83500.0,84500.0,1520300,85715.0,85489.607326,86274.819226,-785.211900,-829.844810,False,False
38,2023-10-27,84600.0,85000.0,83800.0,85000.0,911400,85590.0,85414.283122,86180.388172,-766.105050,-817.096858,False,False
39,2023-10-30,83500.0,86000.0,83500.0,85900.0,618900,85560.0,85489.008796,86159.618678,-670.609882,-787.799463,True,False
40,2023-10-31,85900.0,86900.0,84900.0,86800.0,1438300,85585.0,85690.699750,86207.054332,-516.354581,-733.510486,True,False
41,2023-11-01,86800.0,87800.0,86100.0,87800.0,1550100,85660.0,86015.207481,86325.050307,-309.842826,-648.776954,True,False
42,2023-11-02,88000.0,89000.0,86600.0,89000.0,1114500,85885.0,86474.406330,86523.194729,-48.788399,-528.779243,True,False
43,2023-11-03,89000.0,89400.0,88100.0,88900.0,1157600,86060.0,86847.574587,86699.254378,148.320209,-393.359353,True,False
44,2023-11-06,88900.0,89800.0,88500.0,89500.0,833800,86305.0,87255.640035,86906.717017,348.923018,-244.902879,True,False
45,2023-11-07,89000.0,89300.0,88300.0,88300.0,518900,86415.0,87416.310799,87009.923164,406.387635,-114.644776,True,False
46,2023-11-08,88000.0,89700.0,87900.0,89500.0,1329300,86565.0,87736.878368,87194.373300,542.505068,16.785193,True,False
47,2023-11-09,89500.0,89500.0,87900.0,87900.0,2291800,86660.0,87761.974004,87246.641944,515.332060,116.494566,True,False
48,2023-11-10,87100.0,87500.0,86000.0,86000.0,1411000,86630.0,87490.901080,87154.298097,336.602984,160.516250,False,False
51,2023-11-15,86500.0,87700.0,86500.0,87700.0,4172800,86695.0,87109.690186,87010.491681,99.198504,129.113781,False,False
52,2023-11-16,87000.0,88000.0,86700.0,88000.0,1343800,86870.0,87246.660926,87083.788594,162.872333,135.865491,True,False

In [ ]:
dieukien = (dataCSV['Sell_Signal'] == True) # Buy_Signal = True
dataCSV[dieukien]

In [ ]:
dataCSV[dataCSV['Buy_Signal'] == True]

In [ ]:
dataCSV.info()

In [ ]:
filter1 = dataCSV['Sell_Signal'] == True
dataCSV[filter1]

# Chuyen kieu du lieu

In [ ]:
dataCSV.info()

In [ ]:
dataCSV

# Chuyen kieu du lieu cua 1 cot

In [47]:
dataCSV['Sell_Signal'] = pd.to_numeric(dataCSV['Sell_Signal'], errors='coerce') # Chuyen doi ve kieu so  
# filter2 = (dataCSV['Buy_Signal'] == True) | (dataCSV['Sell_Signal'] == True)
dataCSV

,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal
0,2023-09-05,89100.0,90700.0,89100.0,90100.0,2013202,NaN,90100.000000,90100.000000,0.000000,0.000000,NaN,False
1,2023-09-06,90200.0,90200.0,89700.0,90200.0,2057603,NaN,90115.384615,90107.407407,7.977208,1.595442,False,False
2,2023-09-07,90000.0,90800.0,89500.0,89500.0,1958302,NaN,90020.710059,90062.414266,-41.704207,-7.064488,False,False
3,2023-09-08,89500.0,89500.0,89100.0,89500.0,1381905,NaN,89940.600819,90020.753950,-80.153131,-21.682217,False,False
4,2023-09-11,89600.0,90000.0,88000.0,88500.0,2592500,NaN,89718.969924,89908.105509,-189.135585,-55.172890,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2023-12-20,81200.0,81300.0,80500.0,81100.0,2014300,84510.0,83235.492267,84495.439681,-1259.947415,-835.252482,False,True
76,2023-12-21,81000.0,81000.0,80300.0,80900.0,2148400,84220.0,82876.185764,84229.110816,-1352.925052,-938.786996,False,True
77,2023-12-22,80900.0,81100.0,80400.0,80900.0,1721800,83990.0,82572.157185,83982.510015,-1410.352830,-1033.100163,False,True
78,2023-12-25,80900.0,81800.0,80700.0,81800.0,1480000,83780.0,82453.363772,83820.842606,-1367.478834,-1099.975897,False,True
79,2023-12-26,82000.0,82800.0,82000.0,82800.0,1113200,83630.0,82506.692422,83745.224636,-1238.532213,-1127.687160,False,True

In [48]:
dataCSV.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Datetime     80 non-null     object
 1   Open         80 non-null     float64
 2   High         80 non-null     float64
 3   Low          80 non-null     float64
 4   Close        80 non-null     float64
 5   Volume       80 non-null     int64
 6   SMA          61 non-null     float64
 7   short_ema    80 non-null     float64
 8   long_ema     80 non-null     float64
 9   MACD         80 non-null     float64
 10  Signal_Line  80 non-null     float64
 11  Buy_Signal   79 non-null     object
 12  Sell_Signal  80 non-null     bool
dtypes: bool(1), float64(9), int64(1), object(2)
memory usage: 7.7+ KB

In [ ]:
dataCSV.to_csv('dataCSVAfter.csv')
dataCSV.to_excel('dataCSVAfter.xlsx')

# Them 1 cot vao dataframe

In [ ]:
dataCSV.head(5) # Lay ra 5 dong dau tien

In [ ]:
dataCSV.info()

In [ ]:
dataCSV

In [ ]:
dataCSV['Volume']

In [ ]:
dataCSV['Volume'] = 123456789 # Neu ten cot khong ton tai thi se tao ra mot cot moi, nguoc lai thi se gan gia tri cho cot do

In [ ]:
dataCSV

In [ ]:
dataCSV.info()

In [ ]:
dataCSV

# Them 1 cot

In [ ]:
dataCSV

In [49]:
dataCSV

,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal
0,2023-09-05,89100.0,90700.0,89100.0,90100.0,2013202,NaN,90100.000000,90100.000000,0.000000,0.000000,NaN,False
1,2023-09-06,90200.0,90200.0,89700.0,90200.0,2057603,NaN,90115.384615,90107.407407,7.977208,1.595442,False,False
2,2023-09-07,90000.0,90800.0,89500.0,89500.0,1958302,NaN,90020.710059,90062.414266,-41.704207,-7.064488,False,False
3,2023-09-08,89500.0,89500.0,89100.0,89500.0,1381905,NaN,89940.600819,90020.753950,-80.153131,-21.682217,False,False
4,2023-09-11,89600.0,90000.0,88000.0,88500.0,2592500,NaN,89718.969924,89908.105509,-189.135585,-55.172890,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2023-12-20,81200.0,81300.0,80500.0,81100.0,2014300,84510.0,83235.492267,84495.439681,-1259.947415,-835.252482,False,True
76,2023-12-21,81000.0,81000.0,80300.0,80900.0,2148400,84220.0,82876.185764,84229.110816,-1352.925052,-938.786996,False,True
77,2023-12-22,80900.0,81100.0,80400.0,80900.0,1721800,83990.0,82572.157185,83982.510015,-1410.352830,-1033.100163,False,True
78,2023-12-25,80900.0,81800.0,80700.0,81800.0,1480000,83780.0,82453.363772,83820.842606,-1367.478834,-1099.975897,False,True
79,2023-12-26,82000.0,82800.0,82000.0,82800.0,1113200,83630.0,82506.692422,83745.224636,-1238.532213,-1127.687160,False,True

In [50]:
dataCSV['GiaTriGiaoDich'] = dataCSV['Close'] * dataCSV['Volume'] # Them cot, lay gia tri tu 2 cot khac

dataCSV

,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal,GiaTriGiaoDich
0,2023-09-05,89100.0,90700.0,89100.0,90100.0,2013202,NaN,90100.000000,90100.000000,0.000000,0.000000,NaN,False,1.813895e+11
1,2023-09-06,90200.0,90200.0,89700.0,90200.0,2057603,NaN,90115.384615,90107.407407,7.977208,1.595442,False,False,1.855958e+11
2,2023-09-07,90000.0,90800.0,89500.0,89500.0,1958302,NaN,90020.710059,90062.414266,-41.704207,-7.064488,False,False,1.752680e+11
3,2023-09-08,89500.0,89500.0,89100.0,89500.0,1381905,NaN,89940.600819,90020.753950,-80.153131,-21.682217,False,False,1.236805e+11
4,2023-09-11,89600.0,90000.0,88000.0,88500.0,2592500,NaN,89718.969924,89908.105509,-189.135585,-55.172890,False,False,2.294362e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2023-12-20,81200.0,81300.0,80500.0,81100.0,2014300,84510.0,83235.492267,84495.439681,-1259.947415,-835.252482,False,True,1.633597e+11
76,2023-12-21,81000.0,81000.0,80300.0,80900.0,2148400,84220.0,82876.185764,84229.110816,-1352.925052,-938.786996,False,True,1.738056e+11
77,2023-12-22,80900.0,81100.0,80400.0,80900.0,1721800,83990.0,82572.157185,83982.510015,-1410.352830,-1033.100163,False,True,1.392936e+11
78,2023-12-25,80900.0,81800.0,80700.0,81800.0,1480000,83780.0,82453.363772,83820.842606,-1367.478834,-1099.975897,False,True,1.210640e+11
79,2023-12-26,82000.0,82800.0,82000.0,82800.0,1113200,83630.0,82506.692422,83745.224636,-1238.532213,-1127.687160,False,True,9.217296e+10

In [51]:
dataCSV['GiaTriGiaoDich'] = 0 
dataCSV

,Datetime,Open,High,Low,Close,Volume,SMA,short_ema,long_ema,MACD,Signal_Line,Buy_Signal,Sell_Signal,GiaTriGiaoDich
0,2023-09-05,89100.0,90700.0,89100.0,90100.0,2013202,NaN,90100.000000,90100.000000,0.000000,0.000000,NaN,False,0
1,2023-09-06,90200.0,90200.0,89700.0,90200.0,2057603,NaN,90115.384615,90107.407407,7.977208,1.595442,False,False,0
2,2023-09-07,90000.0,90800.0,89500.0,89500.0,1958302,NaN,90020.710059,90062.414266,-41.704207,-7.064488,False,False,0
3,2023-09-08,89500.0,89500.0,89100.0,89500.0,1381905,NaN,89940.600819,90020.753950,-80.153131,-21.682217,False,False,0
4,2023-09-11,89600.0,90000.0,88000.0,88500.0,2592500,NaN,89718.969924,89908.105509,-189.135585,-55.172890,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2023-12-20,81200.0,81300.0,80500.0,81100.0,2014300,84510.0,83235.492267,84495.439681,-1259.947415,-835.252482,False,True,0
76,2023-12-21,81000.0,81000.0,80300.0,80900.0,2148400,84220.0,82876.185764,84229.110816,-1352.925052,-938.786996,False,True,0
77,2023-12-22,80900.0,81100.0,80400.0,80900.0,1721800,83990.0,82572.157185,83982.510015,-1410.352830,-1033.100163,False,True,0
78,2023-12-25,80900.0,81800.0,80700.0,81800.0,1480000,83780.0,82453.363772,83820.842606,-1367.478834,-1099.975897,False,True,0
79,2023-12-26,82000.0,82800.0,82000.0,82800.0,1113200,83630.0,82506.692422,83745.224636,-1238.532213,-1127.687160,False,True,0

In [ ]:
# Set lai Volume = 0
dataCSV['Low'] = 0
dataCSV

# Bai tap DataFrame

In [ ]:
# In ra nhung dong co Volume > 1000000
# Load du lieu len dataframe
# Filter du lieu tren dataframe do