# Hồi quy tuyến tính 1 Biến

<img src="figs/homepricetable.jpeg" style="width:370px;height:250px">

Xây dựng một mô hình học máy dự đoán giá nhà dựa trên diện tích đất (tính bằng feet vuông). Đây là một ví dụ điển hình của bài toán hồi quy, trong đó biến đầu vào (tính năng) là diện tích nhà và biến đầu ra (mục tiêu) là giá của nhà. Một mô hình hồi quy tuyến tính đơn giản có thể được sử dụng để hiểu và dự đoán mối quan hệ này, vì giá nhà thường tăng theo diện tích.

# Biểu diễn các giá trị trong bảng trên dưới dạng một biểu đồ phân tán, với các giá trị được hiển thị bởi các điểm đánh dấu màu đỏ

Nhiem vu la tim ra duong hoi quy

<img src="figs/scatterplot.jpeg" style="width:600px;height:370px">

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Các giá trị cho 'area' (được lấy từ trục hoành của scatter plot)
area = np.array([2600, 2800, 3000, 3200, 3400, 3600, 3800, 4000])

# Áp dụng phương trình hồi quy để tính 'price'
price = 135.78767123 * area + 180616.43835616432

# Tạo scatter plot với dữ liệu hiện có
plt.scatter(area, price, color='red')  # Các điểm dữ liệu

# Tạo và vẽ đường hồi quy
plt.plot(area, price, color='blue', linewidth=3)  # Đường hồi quy

# Đặt nhãn cho trục x và y
plt.xlabel('Area')
plt.ylabel('Price')

# Hiển thị biểu đồ
plt.show()

Quá trình tối ưu hóa một mô hình hồi quy tuyến tính, nơi chúng ta cố gắng tìm ra đường thẳng phù hợp nhất với các điểm dữ liệu. Mục tiêu là để "tổng bình phương sai số" (tổng bình phương của các khoảng cách từ từng điểm dữ liệu đến đường hồi quy) là nhỏ nhất. Các khoảng cách này, thường được gọi là "sai số" hoặc "residuals" (A1, A2 trên hình), thể hiện sai số giữa giá trị thực tế và giá trị dự đoán bởi mô hình. Việc tối thiểu hóa tổng bình phương của các sai số này giúp đảm bảo rằng mô hình là tốt nhất có thể, phản ánh đúng mối quan hệ giữa biến độc lập và biến phụ thuộc trong dữ liệu.

<img src="figs/equation.png" style="width:600px;height:370px" >

Cách tìm: Dựa trên phương trình dạng tổng quát

<img src="figs/linear_equation.png" >

# Cac buoc de tim bang code manual

In [ ]:
# Code
# Danh cho ban nao code + toan

# Cac buoc de tim bang mo hinh ML

In [ ]:
!pip install scikit-learn
# scikit-learn là thư viện python dùng để học máy

In [ ]:
import pandas as pd # Cài đặt thư viện cần thiết: Load dữ liệu và xử lý
import numpy as np 
import matplotlib.pyplot as plt
from sklearn import linear_model # Hồi quy tuyến tính

In [ ]:
df = pd.read_csv('homeprices.csv')
df

In [ ]:
plt.xlabel('area')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='.')

# Lay bien doc lap

In [ ]:
X = df.drop('price', axis='columns') # Xóa cột 'price' để chỉ giữ lại cột 'area'
X

# Lay bien phu thuoc

In [ ]:
Y = df.price
Y

# Khoi tao

In [ ]:
# Tạo đối tượng hồi quy tuyến tính
model = linear_model.LinearRegression() # Tạo mô hình hồi quy tuyến tính

model.fit(X, Y) # Huấn luyện mô hình với dữ liệu

In [ ]:
df

**(1) Dự đoán giá nhà với diện tích = 5000**

In [ ]:
# Chung ta co mo hinh model
# In hệ số góc và hệ số chặn của đường hồi quy
model.predict([[8000]])  # Dự đoán giá cho diện tích 5000

# Tinh ra he so goc

In [ ]:
model.coef_ # In hệ số góc (slope): m

# Tinh ra he so chan

In [ ]:
model.intercept_ # In hệ số chặn (intercept): b

# The vao ham so y = mx +

In [ ]:
model.coef_ * 8000 + model.intercept_

# The vao duong hoi quy

In [ ]:
# O tren: du doan bang model.predict([[5000]])
model.predict([[5000]])  # Dự đoán giá cho diện tích 5000
# O duoi: phuong trinh du doan bang model.coef_ va model.intercept_

In [ ]:
# The vao cong thuc y = mx + b
model.coef_[0] * 5000 + model.intercept_  # Tính giá dự đoán cho diện tích 5000

In [ ]:
model.predict([[5000]])

**Y = m * X + b (m la he so goc va b la he so chan)**

In [ ]:
135.78767123 * 2000 + 180616.43835616432

# Chung ta co the du doan 1 list dien tich

In [ ]:
area_df = pd.read_csv("areas.csv")
area_df

In [ ]:
p = model.predict(area_df)
p

# In ra list du doan

In [ ]:
area_df['prices']=p
area_df

In [ ]:
area_df.to_csv("prediction.csv")

# Bai tap: Xuat ra dataframe bao gom dien tich, gia thuc te, gia du doan cua du lieu homeprices.csv

### Co data dau vao

In [21]:
df

   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

# DataFrame cu

In [22]:
df

   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

Them cot du doan vao

In [23]:
pH = model.predict(X)
df['Ph'] = pH

df

   area   price             Ph
0  2600  550000  533664.383562
1  3000  565000  587979.452055
2  3200  610000  615136.986301
3  3600  680000  669452.054795
4  4000  725000  723767.123288

In [ ]:
df.info()

Tinh % chenh lech giua gia thuc te va gia du doan

In [ ]:
df

# Bai tap: Tinh chenh lech giua gia thuc te va gia du doan

In [24]:
# Them 1 cot: (Gia thuc te - Gia du doan)/ Gia thuc te
df['PC'] = (df['price'] - df['Ph']) * 100/ df['price']

In [25]:
df

   area   price             Ph        PC
0  2600  550000  533664.383562  2.970112
1  3000  565000  587979.452055 -4.067160
2  3200  610000  615136.986301 -0.842129
3  3600  680000  669452.054795  1.551168
4  4000  725000  723767.123288  0.170052